// Generated by scripts/generate.mts from specs/openapi.json. Do not edit.
import type { INodeProperties } from 'n8n-workflow';

export const angelNumbersDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['angelNumbers'],
			},
		},
		options: [
			{
				name: 'Analyze Number Sequence',
				value: 'analyzeNumberSequence',
				action: 'Analyze number sequence',
				description: 'Analyze any number sequence: Angel number analysis API',
				routing: {
					request: {
						method: 'GET',
						url: '/angel-numbers/lookup',
					},
				},
			},
			{
				name: 'Get Angel Number',
				value: 'getAngelNumber',
				action: 'Get angel number',
				description: 'Get angel number meaning: Angel number lookup API',
				routing: {
					request: {
						method: 'GET',
						url: '=/angel-numbers/numbers/{{encodeURIComponent($parameter["number"])}}',
					},
				},
			},
			{
				name: 'Get Daily Angel Number',
				value: 'getDailyAngelNumber',
				action: 'Get daily angel number',
				description: 'Daily angel number: Angel number of the day API',
				routing: {
					request: {
						method: 'POST',
						url: '/angel-numbers/daily',
					},
				},
			},
			{
				name: 'List Angel Numbers',
				value: 'listAngelNumbers',
				action: 'List angel numbers',
				description: 'List all angel numbers: Angel number catalog API',
				routing: {
					request: {
						method: 'GET',
						url: '/angel-numbers/numbers',
					},
				},
			},
		],
		default: 'analyzeNumberSequence',
	},
	{
		displayName: 'Number',
		name: 'number',
		type: 'string',
		default: '',
		placeholder: 'e.g. 1234',
		required: true,
		description:
			'Number sequence to analyze (1-8 digits). Can be any number the user has encountered: clock times (1111), addresses (717), receipts (888), license plates (4444), or any repeating pattern.',
		routing: {
			send: {
				type: 'query',
				property: 'number',
			},
		},
		displayOptions: {
			show: {
				resource: ['angelNumbers'],
				operation: ['analyzeNumberSequence'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['angelNumbers'],
				operation: ['analyzeNumberSequence'],
			},
		},
		options: [
			{
				displayName: 'Context',
				name: 'context',
				type: 'options',
				options: [
					{
						name: 'Address',
						value: 'address',
					},
					{
						name: 'Clock',
						value: 'clock',
					},
					{
						name: 'License Plate',
						value: 'license-plate',
					},
					{
						name: 'Phone',
						value: 'phone',
					},
					{
						name: 'Price',
						value: 'price',
					},
					{
						name: 'Receipt',
						value: 'receipt',
					},
				],
				default: 'clock',
				description:
					'Where the number was seen. When supplied, the response adds a contextNote tailoring the reading to the sighting: clock (a glanced time), receipt (a purchase), license-plate (in transit), phone (a call or notification), address (a home or place), price (a total or amount).',
				routing: {
					send: {
						type: 'query',
						property: 'context',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Number',
		name: 'number',
		type: 'string',
		default: '',
		placeholder: 'e.g. 444',
		required: true,
		description:
			'Angel number sequence to look up (e.g., "111", "444", "1212", "1234"). Must match an entry in the database.',
		displayOptions: {
			show: {
				resource: ['angelNumbers'],
				operation: ['getAngelNumber'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['angelNumbers'],
				operation: ['getAngelNumber'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['angelNumbers'],
				operation: ['getDailyAngelNumber'],
			},
		},
		options: [
			{
				displayName: 'Date',
				name: 'date',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-03-06',
				description: 'Date for the reading in YYYY-MM-DD format. Defaults to today (UTC).',
				routing: {
					send: {
						type: 'body',
						property: 'date',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Seed',
				name: 'seed',
				type: 'string',
				default: '',
				placeholder: 'e.g. user123',
				description:
					'Optional seed for reproducible readings. Same seed + same date = same angel number every time.',
				routing: {
					send: {
						type: 'body',
						property: 'seed',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['angelNumbers'],
				operation: ['listAngelNumbers'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Limit',
				name: 'maxResults',
				type: 'number',
				default: 20,
				typeOptions: {
					minValue: 1,
					maxValue: 50,
				},
				description: 'Maximum items to return per page. Range: 1-50, default 20.',
				routing: {
					send: {
						type: 'query',
						property: 'limit',
					},
				},
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: 0,
				},
				description: 'Number of items to skip for pagination. Default 0.',
				routing: {
					send: {
						type: 'query',
						property: 'offset',
					},
				},
			},
			{
				displayName: 'Type',
				name: 'type',
				type: 'options',
				options: [
					{
						name: 'Compound',
						value: 'compound',
					},
					{
						name: 'Master',
						value: 'master',
					},
					{
						name: 'Mirror',
						value: 'mirror',
					},
					{
						name: 'Repeating',
						value: 'repeating',
					},
					{
						name: 'Root',
						value: 'root',
					},
					{
						name: 'Sequential',
						value: 'sequential',
					},
				],
				default: 'repeating',
				description:
					'Filter results by angel number pattern type. "repeating" returns numbers like 111, 444, 7777.',
				routing: {
					send: {
						type: 'query',
						property: 'type',
					},
				},
			},
		],
	},
];
