// Generated by scripts/generate.mts from specs/openapi.json. Do not edit.
import type { INodeProperties } from 'n8n-workflow';

export const ayurvedaDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['ayurveda'],
			},
		},
		options: [
			{
				name: 'Calculate Ayurvedic Constitution',
				value: 'calculateAyurvedicConstitution',
				action: 'Calculate ayurvedic constitution',
				description: 'Ayurvedic constitution from a birth chart: Dosha profile API',
				routing: {
					request: {
						method: 'POST',
						url: '/ayurveda/constitution',
					},
				},
			},
			{
				name: 'Get Daily Ayurveda Reading',
				value: 'getDailyAyurvedaReading',
				action: 'Get daily ayurveda reading',
				description: 'Daily Ayurveda reading: Dosha clock and brahma muhurta by location API',
				routing: {
					request: {
						method: 'GET',
						url: '/ayurveda/daily',
					},
				},
			},
			{
				name: 'Get Dinacharya Schedule',
				value: 'getDinacharyaSchedule',
				action: 'Get dinacharya schedule',
				description: 'Dinacharya daily routine: Brahma muhurta and dosha clock API',
				routing: {
					request: {
						method: 'POST',
						url: '/ayurveda/dinacharya',
					},
				},
			},
			{
				name: 'Get Dosha',
				value: 'getDosha',
				action: 'Get dosha',
				description: 'Get one dosha: Vata pitta kapha profile API',
				routing: {
					request: {
						method: 'GET',
						url: '=/ayurveda/doshas/{{encodeURIComponent($parameter["id"])}}',
					},
				},
			},
			{
				name: 'Get Ritucharya',
				value: 'getRitucharya',
				action: 'Get ritucharya',
				description: 'Ayurveda seasonal regimen: Ritucharya and ritu resolution API',
				routing: {
					request: {
						method: 'POST',
						url: '/ayurveda/ritucharya',
					},
				},
			},
			{
				name: 'List Doshas',
				value: 'listDoshas',
				action: 'List doshas',
				description: 'List the three doshas: Dosha catalogue API',
				routing: {
					request: {
						method: 'GET',
						url: '/ayurveda/doshas',
					},
				},
			},
			{
				name: 'List Gunas',
				value: 'listGunas',
				action: 'List gunas',
				description: 'List the twenty qualities: Ayurveda guna pairs API',
				routing: {
					request: {
						method: 'GET',
						url: '/ayurveda/qualities',
					},
				},
			},
			{
				name: 'List Rasas',
				value: 'listRasas',
				action: 'List rasas',
				description: 'List the six tastes: Ayurveda rasa and dosha matrix API',
				routing: {
					request: {
						method: 'GET',
						url: '/ayurveda/tastes',
					},
				},
			},
		],
		default: 'calculateAyurvedicConstitution',
	},
	{
		displayName: 'Date',
		name: 'date',
		type: 'string',
		default: '',
		placeholder: 'e.g. 1990-07-04',
		required: true,
		description:
			'Birth date in YYYY-MM-DD format. It sets the sidereal positions the whole reading is built from, so an approximate date gives an approximate constitution.',
		routing: {
			send: {
				type: 'body',
				property: 'date',
			},
		},
		displayOptions: {
			show: {
				resource: ['ayurveda'],
				operation: ['calculateAyurvedicConstitution'],
			},
		},
	},
	{
		displayName: 'Time',
		name: 'time',
		type: 'string',
		default: '',
		placeholder: 'e.g. 10:12:00',
		required: true,
		description:
			'Birth time in 24-hour HH:MM:SS format. The rising sign turns roughly every two hours and carries the heaviest weight of the three factors, so time is the input a reading is most sensitive to.',
		routing: {
			send: {
				type: 'body',
				property: 'time',
			},
		},
		displayOptions: {
			show: {
				resource: ['ayurveda'],
				operation: ['calculateAyurvedicConstitution'],
			},
		},
	},
	{
		displayName: 'Latitude',
		name: 'latitude',
		type: 'number',
		default: 28.6139,
		typeOptions: {
			minValue: -90,
			maxValue: 90,
			numberPrecision: 6,
		},
		required: true,
		description:
			'Birth latitude in decimal degrees. It sets the local sidereal time behind the rising sign, and it feeds the strength of each graha through the sunrise at that place.',
		routing: {
			send: {
				type: 'body',
				property: 'latitude',
			},
		},
		displayOptions: {
			show: {
				resource: ['ayurveda'],
				operation: ['calculateAyurvedicConstitution'],
			},
		},
	},
	{
		displayName: 'Longitude',
		name: 'longitude',
		type: 'number',
		default: 77.209,
		typeOptions: {
			minValue: -180,
			maxValue: 180,
			numberPrecision: 6,
		},
		required: true,
		description:
			'Birth longitude in decimal degrees. It sets the local sidereal time behind the rising sign, together with the latitude.',
		routing: {
			send: {
				type: 'body',
				property: 'longitude',
			},
		},
		displayOptions: {
			show: {
				resource: ['ayurveda'],
				operation: ['calculateAyurvedicConstitution'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['ayurveda'],
				operation: ['calculateAyurvedicConstitution'],
			},
		},
		options: [
			{
				displayName: 'Ayanamsa',
				name: 'ayanamsa',
				type: 'options',
				options: [
					{
						name: 'Custom',
						value: 'custom',
					},
					{
						name: 'Kp Newcomb',
						value: 'kp-newcomb',
					},
					{
						name: 'Kp Old',
						value: 'kp-old',
					},
					{
						name: 'Lahiri',
						value: 'lahiri',
					},
					{
						name: 'Raman',
						value: 'raman',
					},
				],
				default: 'lahiri',
				description:
					'Sidereal frame the chart is cast in. "lahiri" is the traditional Vedic standard used by most software and is the default. "raman" sits about 1.45 degrees below it. "kp-newcomb" and "kp-old" are the two Krishnamurti Paddhati frames. "custom" takes your own value in degrees via ayanamsaValue. The...',
				routing: {
					send: {
						type: 'body',
						property: 'ayanamsa',
					},
				},
			},
			{
				displayName: 'Ayanamsa Value',
				name: 'ayanamsaValue',
				type: 'number',
				default: 24,
				typeOptions: {
					numberPrecision: 6,
				},
				description:
					'Custom sidereal frame value in degrees. Required when ayanamsa is "custom" and ignored otherwise.',
				routing: {
					send: {
						type: 'body',
						property: 'ayanamsaValue',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Sign Dosha Scheme',
				name: 'signDoshaScheme',
				type: 'options',
				options: [
					{
						name: 'Bphs',
						value: 'bphs',
					},
					{
						name: 'Satyacharya',
						value: 'satyacharya',
					},
				],
				default: 'satyacharya',
				description:
					'Which classical sign table the rising sign and the Moon sign are read through. "satyacharya" is the twelve-sign extract appended to Brihat Jataka 18.20, carried in two independent public-domain translations that agree on all twelve rows, and is the default. "bphs" is the Brihat Parasara Hora...',
				routing: {
					send: {
						type: 'body',
						property: 'signDoshaScheme',
					},
				},
			},
			{
				displayName: 'Timezone',
				name: 'timezone',
				type: 'string',
				default: '',
				placeholder: 'e.g. America/New_York or 5.5',
				description:
					'Timezone as an IANA name such as "Asia/Kolkata", or as decimal hours from UTC such as 5.5. An IANA name is resolved to the offset in force on the birth date, so a summer-time birth is placed correctly.',
				routing: {
					send: {
						type: 'body',
						property: 'timezone',
						value: '={{ $value !== "" && !isNaN(Number($value)) ? Number($value) : $value }}',
					},
				},
			},
		],
	},
	{
		displayName: 'Latitude',
		name: 'latitude',
		type: 'number',
		default: 51.5074,
		typeOptions: {
			minValue: -90,
			maxValue: 90,
			numberPrecision: 6,
		},
		required: true,
		description:
			'Latitude in decimal degrees. It sets how long the day and the night actually are, which is what the dosha periods are cut from.',
		routing: {
			send: {
				type: 'query',
				property: 'latitude',
			},
		},
		displayOptions: {
			show: {
				resource: ['ayurveda'],
				operation: ['getDailyAyurvedaReading'],
			},
		},
	},
	{
		displayName: 'Longitude',
		name: 'longitude',
		type: 'number',
		default: -0.1278,
		typeOptions: {
			minValue: -180,
			maxValue: 180,
			numberPrecision: 6,
		},
		required: true,
		description: 'Longitude in decimal degrees. It sets the clock time of sunrise at this place.',
		routing: {
			send: {
				type: 'query',
				property: 'longitude',
			},
		},
		displayOptions: {
			show: {
				resource: ['ayurveda'],
				operation: ['getDailyAyurvedaReading'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['ayurveda'],
				operation: ['getDailyAyurvedaReading'],
			},
		},
		options: [
			{
				displayName: 'Date',
				name: 'date',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-06-21',
				description:
					'Reading date in YYYY-MM-DD format. Past and future dates are both supported, for editorial scheduling and backfill.',
				routing: {
					send: {
						type: 'query',
						property: 'date',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Timezone',
				name: 'timezone',
				type: 'string',
				default: '',
				placeholder: 'e.g. Europe/London',
				description:
					'Selects which day counts as current when date is omitted, and which local day sunrise is computed for. Defaults to UTC, so the reading rolls over at 00:00 UTC.',
				routing: {
					send: {
						type: 'query',
						property: 'timezone',
					},
				},
			},
		],
	},
	{
		displayName: 'Date',
		name: 'date',
		type: 'string',
		default: '',
		placeholder: 'e.g. 2026-06-21',
		required: true,
		description:
			'The local calendar date, in YYYY-MM-DD format. Sunrise and sunset are computed for this date at the given place, and the whole routine follows from them, so the answer changes through the year at any latitude away from the equator.',
		routing: {
			send: {
				type: 'body',
				property: 'date',
			},
		},
		displayOptions: {
			show: {
				resource: ['ayurveda'],
				operation: ['getDinacharyaSchedule'],
			},
		},
	},
	{
		displayName: 'Latitude',
		name: 'latitude',
		type: 'number',
		default: 51.5074,
		typeOptions: {
			minValue: -90,
			maxValue: 90,
			numberPrecision: 6,
		},
		required: true,
		description:
			'Latitude in decimal degrees. It sets how long the day and the night actually are, which is the whole difference between this and a printed timetable: at 51 north in June the day runs about sixteen and a half hours and its thirds are five and a half hours each.',
		routing: {
			send: {
				type: 'body',
				property: 'latitude',
			},
		},
		displayOptions: {
			show: {
				resource: ['ayurveda'],
				operation: ['getDinacharyaSchedule'],
			},
		},
	},
	{
		displayName: 'Longitude',
		name: 'longitude',
		type: 'number',
		default: -0.1278,
		typeOptions: {
			minValue: -180,
			maxValue: 180,
			numberPrecision: 6,
		},
		required: true,
		description: 'Longitude in decimal degrees. It sets the clock time of sunrise at this place.',
		routing: {
			send: {
				type: 'body',
				property: 'longitude',
			},
		},
		displayOptions: {
			show: {
				resource: ['ayurveda'],
				operation: ['getDinacharyaSchedule'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['ayurveda'],
				operation: ['getDinacharyaSchedule'],
			},
		},
		options: [
			{
				displayName: 'Dosha Clock',
				name: 'doshaClock',
				type: 'options',
				options: [
					{
						name: 'Clock Hours',
						value: 'clock-hours',
					},
					{
						name: 'Sunrise Anchored',
						value: 'sunrise-anchored',
					},
				],
				default: 'sunrise-anchored',
				description:
					'How the six dosha periods are cut. "sunrise-anchored" divides the actual day and the actual night at this place into thirds, which is the division the frame chapter states, and is the default. "clock-hours" is the modern grid of six four-hour blocks from six in the morning; no classical text...',
				routing: {
					send: {
						type: 'body',
						property: 'doshaClock',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Timezone',
				name: 'timezone',
				type: 'string',
				default: '',
				placeholder: 'e.g. America/New_York or Europe/London',
				description:
					'Timezone as an IANA name such as "Europe/London", or as decimal hours from UTC such as 5.5. An IANA name is resolved to the offset in force on the requested date, and on the clock-hour grid at the local hour each block opens, so on a daylight-saving change every block keeps its printed hour and...',
				routing: {
					send: {
						type: 'body',
						property: 'timezone',
						value: '={{ $value !== "" && !isNaN(Number($value)) ? Number($value) : $value }}',
					},
				},
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'options',
		options: [
			{
				name: 'Kapha',
				value: 'kapha',
			},
			{
				name: 'Pitta',
				value: 'pitta',
			},
			{
				name: 'Vata',
				value: 'vata',
			},
		],
		default: 'vata',
		required: true,
		description: 'Dosha identifier, case-insensitive. One of vata, pitta or kapha.',
		displayOptions: {
			show: {
				resource: ['ayurveda'],
				operation: ['getDosha'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['ayurveda'],
				operation: ['getDosha'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Date',
		name: 'date',
		type: 'string',
		default: '',
		placeholder: 'e.g. 2026-03-01',
		required: true,
		description:
			'The date to resolve, in YYYY-MM-DD format. The season is read at midday UTC on this date, because a season boundary is an instant and a calendar day has to be reduced to one; on a day that carries a boundary, the half the midday falls in is the answer.',
		routing: {
			send: {
				type: 'body',
				property: 'date',
			},
		},
		displayOptions: {
			show: {
				resource: ['ayurveda'],
				operation: ['getRitucharya'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['ayurveda'],
				operation: ['getRitucharya'],
			},
		},
		options: [
			{
				displayName: 'Hemisphere',
				name: 'hemisphere',
				type: 'options',
				options: [
					{
						name: 'Northern',
						value: 'northern',
					},
					{
						name: 'Southern',
						value: 'southern',
					},
				],
				default: 'northern',
				description:
					'Which half of the world the season names are stated for. Defaults to "northern", which is the half the primary text describes.',
				routing: {
					send: {
						type: 'body',
						property: 'hemisphere',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Ritu Zodiac',
				name: 'rituZodiac',
				type: 'options',
				options: [
					{
						name: 'Nirayana',
						value: 'nirayana',
					},
					{
						name: 'Sayana',
						value: 'sayana',
					},
				],
				default: 'sayana',
				description:
					'Which zodiac the solar-month boundaries are measured in. "sayana" is the tropical reading, which is what published almanacs use for seasons and is the default. "nirayana" is the sidereal reading in the Lahiri frame, which runs about 24 days later. The gap is the size of the ayanamsa, so near a...',
				routing: {
					send: {
						type: 'body',
						property: 'rituZodiac',
					},
				},
			},
			{
				displayName: 'Ritucharya Scheme',
				name: 'ritucharyaScheme',
				type: 'options',
				options: [
					{
						name: 'Sutrasthana 6',
						value: 'sutrasthana-6',
					},
					{
						name: 'Vimana 8',
						value: 'vimana-8',
					},
				],
				default: 'sutrasthana-6',
				description:
					'Which six-season division the year is cut into. "sutrasthana-6" is the standard set of sisira, vasanta, grisma, varsa, sarad and hemanta, and is the default. "vimana-8" is the alternate division in which three seasons of extreme character alternate with three of moderate character and pravrt,...',
				routing: {
					send: {
						type: 'body',
						property: 'ritucharyaScheme',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['ayurveda'],
				operation: ['listDoshas'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Limit',
				name: 'maxResults',
				type: 'number',
				default: 3,
				typeOptions: {
					minValue: 1,
					maxValue: 3,
				},
				description: 'Maximum items to return per page. Range: 1-3, default 3.',
				routing: {
					send: {
						type: 'query',
						property: 'limit',
					},
				},
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: 0,
				},
				description: 'Number of items to skip for pagination. Default 0.',
				routing: {
					send: {
						type: 'query',
						property: 'offset',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['ayurveda'],
				operation: ['listGunas'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Limit',
				name: 'maxResults',
				type: 'number',
				default: 10,
				typeOptions: {
					minValue: 1,
					maxValue: 10,
				},
				description: 'Maximum items to return per page. Range: 1-10, default 10.',
				routing: {
					send: {
						type: 'query',
						property: 'limit',
					},
				},
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: 0,
				},
				description: 'Number of items to skip for pagination. Default 0.',
				routing: {
					send: {
						type: 'query',
						property: 'offset',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['ayurveda'],
				operation: ['listRasas'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Limit',
				name: 'maxResults',
				type: 'number',
				default: 6,
				typeOptions: {
					minValue: 1,
					maxValue: 6,
				},
				description: 'Maximum items to return per page. Range: 1-6, default 6.',
				routing: {
					send: {
						type: 'query',
						property: 'limit',
					},
				},
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: 0,
				},
				description: 'Number of items to skip for pagination. Default 0.',
				routing: {
					send: {
						type: 'query',
						property: 'offset',
					},
				},
			},
		],
	},
];
