// Generated by scripts/generate.mts from specs/openapi.json. Do not edit.
import type { INodeProperties } from 'n8n-workflow';

export const biorhythmDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['biorhythm'],
			},
		},
		options: [
			{
				name: 'Calculate Biorhythm Compatibility',
				value: 'calculateBioCompatibility',
				action: 'Calculate biorhythm compatibility',
				description: 'Calculate compatibility: Biorhythm alignment between two people',
				routing: {
					request: {
						method: 'POST',
						url: '/biorhythm/compatibility',
					},
				},
			},
			{
				name: 'Get Critical Days',
				value: 'getCriticalDays',
				action: 'Get critical days',
				description: 'Find critical days: Zero crossing detection for any date range',
				routing: {
					request: {
						method: 'POST',
						url: '/biorhythm/critical-days',
					},
				},
			},
			{
				name: 'Get Daily Biorhythm',
				value: 'getDailyBiorhythm',
				action: 'Get daily biorhythm',
				description: 'Get daily biorhythm: Seeded reading for daily check-in features',
				routing: {
					request: {
						method: 'POST',
						url: '/biorhythm/daily',
					},
				},
			},
			{
				name: 'Get Forecast',
				value: 'getForecast',
				action: 'Get forecast',
				description: 'Get biorhythm forecast: Multi-day cycle predictions with best and worst days',
				routing: {
					request: {
						method: 'POST',
						url: '/biorhythm/forecast',
					},
				},
			},
			{
				name: 'Get Phases',
				value: 'getPhases',
				action: 'Get phases',
				description: 'Get phase info: Lightweight cycle status for dashboards and widgets',
				routing: {
					request: {
						method: 'POST',
						url: '/biorhythm/phases',
					},
				},
			},
			{
				name: 'Get Reading',
				value: 'getReading',
				action: 'Get reading',
				description: 'Get biorhythm reading: Complete cycle analysis for any date',
				routing: {
					request: {
						method: 'POST',
						url: '/biorhythm/reading',
					},
				},
			},
		],
		default: 'calculateBioCompatibility',
	},
	{
		displayName: 'Person1',
		name: 'person1',
		type: 'json',
		default: '{\n  "birthDate": "1990-07-15"\n}',
		required: true,
		routing: {
			send: {
				type: 'body',
				property: 'person1',
				value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['biorhythm'],
				operation: ['calculateBioCompatibility'],
			},
		},
	},
	{
		displayName: 'Person2',
		name: 'person2',
		type: 'json',
		default: '{\n  "birthDate": "1992-03-22"\n}',
		required: true,
		routing: {
			send: {
				type: 'body',
				property: 'person2',
				value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['biorhythm'],
				operation: ['calculateBioCompatibility'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['biorhythm'],
				operation: ['calculateBioCompatibility'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Target Date',
				name: 'targetDate',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-04-10',
				description:
					'Date to evaluate compatibility on in YYYY-MM-DD format. Defaults to today (UTC).',
				routing: {
					send: {
						type: 'body',
						property: 'targetDate',
					},
				},
			},
		],
	},
	{
		displayName: 'Birth Date',
		name: 'birthDate',
		type: 'string',
		default: '',
		placeholder: 'e.g. 1990-07-15',
		required: true,
		description: 'Birth date of the person in YYYY-MM-DD format',
		routing: {
			send: {
				type: 'body',
				property: 'birthDate',
			},
		},
		displayOptions: {
			show: {
				resource: ['biorhythm'],
				operation: ['getCriticalDays'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['biorhythm'],
				operation: ['getCriticalDays'],
			},
		},
		options: [
			{
				displayName: 'End Date',
				name: 'endDate',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-06-30',
				description:
					'End date of the search range in YYYY-MM-DD format. Defaults to startDate + 90 days.',
				routing: {
					send: {
						type: 'body',
						property: 'endDate',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Start Date',
				name: 'startDate',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-04-01',
				description:
					'Start date of the search range in YYYY-MM-DD format. Defaults to today (UTC).',
				routing: {
					send: {
						type: 'body',
						property: 'startDate',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['biorhythm'],
				operation: ['getDailyBiorhythm'],
			},
		},
		options: [
			{
				displayName: 'Date',
				name: 'date',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-03-06',
				description: 'Date for the reading in YYYY-MM-DD format. Defaults to today (UTC).',
				routing: {
					send: {
						type: 'body',
						property: 'date',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Seed',
				name: 'seed',
				type: 'string',
				default: '',
				placeholder: 'e.g. user123',
				description:
					'Optional seed for reproducible readings. Same seed + same date = same reading every time.',
				routing: {
					send: {
						type: 'body',
						property: 'seed',
					},
				},
			},
		],
	},
	{
		displayName: 'Birth Date',
		name: 'birthDate',
		type: 'string',
		default: '',
		placeholder: 'e.g. 1990-07-15',
		required: true,
		description: 'Birth date of the person in YYYY-MM-DD format',
		routing: {
			send: {
				type: 'body',
				property: 'birthDate',
			},
		},
		displayOptions: {
			show: {
				resource: ['biorhythm'],
				operation: ['getForecast'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['biorhythm'],
				operation: ['getForecast'],
			},
		},
		options: [
			{
				displayName: 'End Date',
				name: 'endDate',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-04-30',
				description:
					'End date of the forecast range in YYYY-MM-DD format. Defaults to startDate + 30 days.',
				routing: {
					send: {
						type: 'body',
						property: 'endDate',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Start Date',
				name: 'startDate',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-04-01',
				description:
					'Start date of the forecast range in YYYY-MM-DD format. Defaults to today (UTC).',
				routing: {
					send: {
						type: 'body',
						property: 'startDate',
					},
				},
			},
		],
	},
	{
		displayName: 'Birth Date',
		name: 'birthDate',
		type: 'string',
		default: '',
		placeholder: 'e.g. 1990-07-15',
		required: true,
		description: 'Birth date of the person in YYYY-MM-DD format',
		routing: {
			send: {
				type: 'body',
				property: 'birthDate',
			},
		},
		displayOptions: {
			show: {
				resource: ['biorhythm'],
				operation: ['getPhases'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['biorhythm'],
				operation: ['getPhases'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Target Date',
				name: 'targetDate',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-04-10',
				description:
					'Date to get phase information for in YYYY-MM-DD format. Defaults to today (UTC).',
				routing: {
					send: {
						type: 'body',
						property: 'targetDate',
					},
				},
			},
		],
	},
	{
		displayName: 'Birth Date',
		name: 'birthDate',
		type: 'string',
		default: '',
		placeholder: 'e.g. 1990-07-15',
		required: true,
		description:
			'Birth date of the person in YYYY-MM-DD format. This is the anchor for all biorhythm cycle calculations.',
		routing: {
			send: {
				type: 'body',
				property: 'birthDate',
			},
		},
		displayOptions: {
			show: {
				resource: ['biorhythm'],
				operation: ['getReading'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['biorhythm'],
				operation: ['getReading'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Target Date',
				name: 'targetDate',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-04-10',
				description:
					'Date to calculate the reading for in YYYY-MM-DD format. Defaults to today (UTC) if omitted.',
				routing: {
					send: {
						type: 'body',
						property: 'targetDate',
					},
				},
			},
		],
	},
];
