// Generated by scripts/generate.mts from specs/openapi.json. Do not edit.
import type { INodeProperties } from 'n8n-workflow';

export const chineseAstrologyDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
			},
		},
		options: [
			{
				name: 'Calculate Annual Forecast',
				value: 'calculateAnnualForecast',
				action: 'Calculate annual forecast',
				description: 'Calculate BaZi annual forecast: Liu Nian yearly pillar API',
				routing: {
					request: {
						method: 'POST',
						url: '/chinese-astrology/bazi/annual-forecast',
					},
				},
			},
			{
				name: 'Calculate Bazi Compatibility',
				value: 'calculateBaziCompatibility',
				action: 'Calculate bazi compatibility',
				description: 'Calculate BaZi compatibility: Four Pillars matchmaking API',
				routing: {
					request: {
						method: 'POST',
						url: '/chinese-astrology/bazi/compatibility',
					},
				},
			},
			{
				name: 'Calculate Day Master Strength',
				value: 'calculateDayMasterStrength',
				action: 'Calculate day master strength',
				description: 'Calculate Day Master strength: BaZi favorable element API',
				routing: {
					request: {
						method: 'POST',
						url: '/chinese-astrology/bazi/day-master',
					},
				},
			},
			{
				name: 'Calculate Luck Pillars',
				value: 'calculateLuckPillars',
				action: 'Calculate luck pillars',
				description: 'Calculate luck pillars: BaZi Da Yun ten-year cycle API',
				routing: {
					request: {
						method: 'POST',
						url: '/chinese-astrology/bazi/luck-pillars',
					},
				},
			},
			{
				name: 'Calculate Lunar Date',
				value: 'calculateLunarDate',
				action: 'Calculate lunar date',
				description: 'Convert lunar and Gregorian dates: Chinese lunisolar calendar API',
				routing: {
					request: {
						method: 'POST',
						url: '/chinese-astrology/calendar/lunar-date',
					},
				},
			},
			{
				name: 'Calculate Zodiac Animal',
				value: 'calculateZodiacAnimal',
				action: 'Calculate zodiac animal',
				description: 'Find the Chinese zodiac animal for a birth date: Sheng Xiao calculator',
				routing: {
					request: {
						method: 'POST',
						url: '/chinese-astrology/zodiac/sign',
					},
				},
			},
			{
				name: 'Generate Bazi Chart',
				value: 'generateBaziChart',
				action: 'Generate bazi chart',
				description: 'Generate BaZi chart: Four Pillars of Destiny calculator API',
				routing: {
					request: {
						method: 'POST',
						url: '/chinese-astrology/bazi/chart',
					},
				},
			},
			{
				name: 'Get Almanac Day',
				value: 'getAlmanacDay',
				action: 'Get almanac day',
				description: 'Get the almanac for a day: Tong Shu API with day officers and mansions',
				routing: {
					request: {
						method: 'GET',
						url: '=/chinese-astrology/calendar/day/{{encodeURIComponent($parameter["date"])}}',
					},
				},
			},
			{
				name: 'Get Daily Zodiac Reading',
				value: 'getDailyZodiacReading',
				action: 'Get daily zodiac reading',
				description: 'Daily Chinese zodiac reading: Day pillar forecast by animal sign',
				routing: {
					request: {
						method: 'GET',
						url: '=/chinese-astrology/zodiac/{{encodeURIComponent($parameter["id"])}}/daily',
					},
				},
			},
			{
				name: 'Get Monthly Almanac',
				value: 'getMonthlyAlmanac',
				action: 'Get monthly almanac',
				description: 'Get a month of almanac days: Chinese calendar month view API',
				routing: {
					request: {
						method: 'GET',
						url: '/chinese-astrology/calendar/monthly',
					},
				},
			},
			{
				name: 'Get Zodiac Animal',
				value: 'getZodiacAnimal',
				action: 'Get zodiac animal',
				description: 'Get one Chinese zodiac animal: Full sign profile with compatibility partners',
				routing: {
					request: {
						method: 'GET',
						url: '=/chinese-astrology/zodiac/animals/{{encodeURIComponent($parameter["id"])}}',
					},
				},
			},
			{
				name: 'Get Zodiac Compatibility',
				value: 'getZodiacCompatibility',
				action: 'Get zodiac compatibility',
				description: 'Chinese zodiac compatibility: Trine, six harmony, clash and harm analysis',
				routing: {
					request: {
						method: 'GET',
						url: '=/chinese-astrology/zodiac/compatibility/{{encodeURIComponent($parameter["sign1"])}}/{{encodeURIComponent($parameter["sign2"])}}',
					},
				},
			},
			{
				name: 'List Five Elements',
				value: 'listFiveElements',
				action: 'List five elements',
				description: 'List the five elements: Wu Xing API with generating and controlling cycles',
				routing: {
					request: {
						method: 'GET',
						url: '/chinese-astrology/elements',
					},
				},
			},
			{
				name: 'List Solar Terms',
				value: 'listSolarTerms',
				action: 'List solar terms',
				description: 'List the 24 solar terms: Jie Qi calendar API with exact instants',
				routing: {
					request: {
						method: 'GET',
						url: '=/chinese-astrology/calendar/solar-terms/{{encodeURIComponent($parameter["year"])}}',
					},
				},
			},
			{
				name: 'List Zodiac Animals',
				value: 'listZodiacAnimals',
				action: 'List zodiac animals',
				description: 'List the 12 Chinese zodiac animals: Sheng Xiao sign catalogue',
				routing: {
					request: {
						method: 'GET',
						url: '/chinese-astrology/zodiac/animals',
					},
				},
			},
			{
				name: 'Lookup Auspicious Days',
				value: 'lookupAuspiciousDays',
				action: 'Lookup auspicious days',
				description: 'Find auspicious days: Chinese date selection API for weddings and openings',
				routing: {
					request: {
						method: 'POST',
						url: '/chinese-astrology/calendar/auspicious-days',
					},
				},
			},
		],
		default: 'calculateAnnualForecast',
	},
	{
		displayName: 'Date',
		name: 'date',
		type: 'string',
		default: '',
		placeholder: 'e.g. 1990-06-15',
		required: true,
		description: 'Birth date in YYYY-MM-DD format. Sets the year, month and day pillars.',
		routing: {
			send: {
				type: 'body',
				property: 'date',
			},
		},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['calculateAnnualForecast'],
			},
		},
	},
	{
		displayName: 'Time',
		name: 'time',
		type: 'string',
		default: '',
		placeholder: 'e.g. 14:30:00',
		required: true,
		description:
			'Birth time in 24-hour HH:MM:SS format. Sets the hour pillar, which is one of the four and carries the whole picture of later life and offspring.',
		routing: {
			send: {
				type: 'body',
				property: 'time',
			},
		},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['calculateAnnualForecast'],
			},
		},
	},
	{
		displayName: 'Timezone',
		name: 'timezone',
		type: 'string',
		default: '',
		placeholder: 'e.g. America/New_York or -5',
		required: true,
		description:
			'IANA name (e.g. "America/New_York", "Europe/London", "UTC"), decimal hours (e.g. -5 for EST, 1 for CET), or a fixed UTC offset (e.g. "-05:00", "+01:00").',
		routing: {
			send: {
				type: 'body',
				property: 'timezone',
				value: '={{ $value !== "" && !isNaN(Number($value)) ? Number($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['calculateAnnualForecast'],
			},
		},
	},
	{
		displayName: 'Year',
		name: 'year',
		type: 'number',
		default: 2026,
		typeOptions: {
			minValue: 1551,
			maxValue: 2649,
		},
		required: true,
		description:
			'Gregorian year to read against the natal chart. The annual pillar for that year is resolved under the same year boundary the request selected, so a li-chun reading and a lunar-new-year reading of the same calendar year can differ.',
		routing: {
			send: {
				type: 'body',
				property: 'year',
			},
		},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['calculateAnnualForecast'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['calculateAnnualForecast'],
			},
		},
		options: [
			{
				displayName: 'Day Boundary',
				name: 'dayBoundary',
				type: 'options',
				options: [
					{
						name: 'Early Zi',
						value: 'early-zi',
					},
					{
						name: 'Midnight',
						value: 'midnight',
					},
					{
						name: 'Split Zi',
						value: 'split-zi',
					},
				],
				default: 'split-zi',
				description:
					'Which instant starts the sexagenary DAY, which only matters for a birth between 23:00 and 23:59',
				routing: {
					send: {
						type: 'body',
						property: 'dayBoundary',
					},
				},
			},
			{
				displayName: 'Hour Clock',
				name: 'hourClock',
				type: 'options',
				options: [
					{
						name: 'Clock',
						value: 'clock',
					},
					{
						name: 'Local Mean',
						value: 'local-mean',
					},
					{
						name: 'Solar',
						value: 'solar',
					},
				],
				default: 'clock',
				description:
					'Which clock the day boundary and the hour branch are read from, so a correction that carries a birth across midnight moves the day pillar with the hour. "clock" is civil time exactly as a birth certificate records it, which is what most calculators use and the default here.',
				routing: {
					send: {
						type: 'body',
						property: 'hourClock',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Latitude',
				name: 'latitude',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: -90,
					maxValue: 90,
					numberPrecision: 6,
				},
				description:
					'Birth latitude in decimal degrees. Accepted for consistency with the other birth-data endpoints and does not affect any part of a BaZi chart.',
				routing: {
					send: {
						type: 'body',
						property: 'latitude',
					},
				},
			},
			{
				displayName: 'Longitude',
				name: 'longitude',
				type: 'number',
				default: 116.4,
				typeOptions: {
					minValue: -180,
					maxValue: 180,
					numberPrecision: 6,
				},
				description: 'Birth longitude in decimal degrees. Positive is East, negative is West.',
				routing: {
					send: {
						type: 'body',
						property: 'longitude',
					},
				},
			},
			{
				displayName: 'Year Boundary',
				name: 'yearBoundary',
				type: 'options',
				options: [
					{
						name: 'Li Chun',
						value: 'li-chun',
					},
					{
						name: 'Lunar New Year',
						value: 'lunar-new-year',
					},
				],
				default: 'li-chun',
				description:
					'Which instant starts the sexagenary YEAR. "li-chun" is Beginning of Spring, around 4 February, and is the classical rule every BaZi text uses, so it is the default on this endpoint.',
				routing: {
					send: {
						type: 'body',
						property: 'yearBoundary',
					},
				},
			},
		],
	},
	{
		displayName: 'Person A',
		name: 'personA',
		type: 'json',
		default:
			'{\n  "date": "1990-06-15",\n  "time": "14:30:00",\n  "timezone": "America/New_York",\n  "latitude": 0,\n  "longitude": 116.4,\n  "dayBoundary": "split-zi",\n  "yearBoundary": "li-chun",\n  "hourClock": "clock"\n}',
		required: true,
		description:
			'Birth moment of the first person. Each subject carries its own school switches, so two charts built under different conventions can still be compared.',
		routing: {
			send: {
				type: 'body',
				property: 'personA',
				value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['calculateBaziCompatibility'],
			},
		},
	},
	{
		displayName: 'Person B',
		name: 'personB',
		type: 'json',
		default:
			'{\n  "date": "1990-06-15",\n  "time": "14:30:00",\n  "timezone": "America/New_York",\n  "latitude": 0,\n  "longitude": 116.4,\n  "dayBoundary": "split-zi",\n  "yearBoundary": "li-chun",\n  "hourClock": "clock"\n}',
		required: true,
		description: 'Birth moment of the second person',
		routing: {
			send: {
				type: 'body',
				property: 'personB',
				value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['calculateBaziCompatibility'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['calculateBaziCompatibility'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Date',
		name: 'date',
		type: 'string',
		default: '',
		placeholder: 'e.g. 1990-06-15',
		required: true,
		description: 'Birth date in YYYY-MM-DD format. Sets the year, month and day pillars.',
		routing: {
			send: {
				type: 'body',
				property: 'date',
			},
		},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['calculateDayMasterStrength'],
			},
		},
	},
	{
		displayName: 'Time',
		name: 'time',
		type: 'string',
		default: '',
		placeholder: 'e.g. 14:30:00',
		required: true,
		description:
			'Birth time in 24-hour HH:MM:SS format. Sets the hour pillar, which is one of the four and carries the whole picture of later life and offspring.',
		routing: {
			send: {
				type: 'body',
				property: 'time',
			},
		},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['calculateDayMasterStrength'],
			},
		},
	},
	{
		displayName: 'Timezone',
		name: 'timezone',
		type: 'string',
		default: '',
		placeholder: 'e.g. America/New_York or -5',
		required: true,
		description:
			'IANA name (e.g. "America/New_York", "Europe/London", "UTC"), decimal hours (e.g. -5 for EST, 1 for CET), or a fixed UTC offset (e.g. "-05:00", "+01:00").',
		routing: {
			send: {
				type: 'body',
				property: 'timezone',
				value: '={{ $value !== "" && !isNaN(Number($value)) ? Number($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['calculateDayMasterStrength'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['calculateDayMasterStrength'],
			},
		},
		options: [
			{
				displayName: 'Day Boundary',
				name: 'dayBoundary',
				type: 'options',
				options: [
					{
						name: 'Early Zi',
						value: 'early-zi',
					},
					{
						name: 'Midnight',
						value: 'midnight',
					},
					{
						name: 'Split Zi',
						value: 'split-zi',
					},
				],
				default: 'split-zi',
				description:
					'Which instant starts the sexagenary DAY, which only matters for a birth between 23:00 and 23:59',
				routing: {
					send: {
						type: 'body',
						property: 'dayBoundary',
					},
				},
			},
			{
				displayName: 'Hour Clock',
				name: 'hourClock',
				type: 'options',
				options: [
					{
						name: 'Clock',
						value: 'clock',
					},
					{
						name: 'Local Mean',
						value: 'local-mean',
					},
					{
						name: 'Solar',
						value: 'solar',
					},
				],
				default: 'clock',
				description:
					'Which clock the day boundary and the hour branch are read from, so a correction that carries a birth across midnight moves the day pillar with the hour. "clock" is civil time exactly as a birth certificate records it, which is what most calculators use and the default here.',
				routing: {
					send: {
						type: 'body',
						property: 'hourClock',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Latitude',
				name: 'latitude',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: -90,
					maxValue: 90,
					numberPrecision: 6,
				},
				description:
					'Birth latitude in decimal degrees. Accepted for consistency with the other birth-data endpoints and does not affect any part of a BaZi chart.',
				routing: {
					send: {
						type: 'body',
						property: 'latitude',
					},
				},
			},
			{
				displayName: 'Longitude',
				name: 'longitude',
				type: 'number',
				default: 116.4,
				typeOptions: {
					minValue: -180,
					maxValue: 180,
					numberPrecision: 6,
				},
				description: 'Birth longitude in decimal degrees. Positive is East, negative is West.',
				routing: {
					send: {
						type: 'body',
						property: 'longitude',
					},
				},
			},
			{
				displayName: 'Year Boundary',
				name: 'yearBoundary',
				type: 'options',
				options: [
					{
						name: 'Li Chun',
						value: 'li-chun',
					},
					{
						name: 'Lunar New Year',
						value: 'lunar-new-year',
					},
				],
				default: 'li-chun',
				description:
					'Which instant starts the sexagenary YEAR. "li-chun" is Beginning of Spring, around 4 February, and is the classical rule every BaZi text uses, so it is the default on this endpoint.',
				routing: {
					send: {
						type: 'body',
						property: 'yearBoundary',
					},
				},
			},
		],
	},
	{
		displayName: 'Date',
		name: 'date',
		type: 'string',
		default: '',
		placeholder: 'e.g. 1990-06-15',
		required: true,
		description: 'Birth date in YYYY-MM-DD format. Sets the year, month and day pillars.',
		routing: {
			send: {
				type: 'body',
				property: 'date',
			},
		},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['calculateLuckPillars'],
			},
		},
	},
	{
		displayName: 'Time',
		name: 'time',
		type: 'string',
		default: '',
		placeholder: 'e.g. 14:30:00',
		required: true,
		description:
			'Birth time in 24-hour HH:MM:SS format. Sets the hour pillar, which is one of the four and carries the whole picture of later life and offspring.',
		routing: {
			send: {
				type: 'body',
				property: 'time',
			},
		},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['calculateLuckPillars'],
			},
		},
	},
	{
		displayName: 'Timezone',
		name: 'timezone',
		type: 'string',
		default: '',
		placeholder: 'e.g. America/New_York or -5',
		required: true,
		description:
			'IANA name (e.g. "America/New_York", "Europe/London", "UTC"), decimal hours (e.g. -5 for EST, 1 for CET), or a fixed UTC offset (e.g. "-05:00", "+01:00").',
		routing: {
			send: {
				type: 'body',
				property: 'timezone',
				value: '={{ $value !== "" && !isNaN(Number($value)) ? Number($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['calculateLuckPillars'],
			},
		},
	},
	{
		displayName: 'Gender',
		name: 'gender',
		type: 'options',
		options: [
			{
				name: 'Female',
				value: 'female',
			},
			{
				name: 'Male',
				value: 'male',
			},
		],
		default: 'male',
		required: true,
		description:
			'Subject sex, used only to pick the luck-pillar direction: a male born in a yang-stem year and a female born in a yin-stem year run forward through the sexagenary cycle, and the other two combinations run backward. It affects nothing else in the response.',
		routing: {
			send: {
				type: 'body',
				property: 'gender',
			},
		},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['calculateLuckPillars'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['calculateLuckPillars'],
			},
		},
		options: [
			{
				displayName: 'Annual From Year',
				name: 'annualFromYear',
				type: 'number',
				default: 2026,
				typeOptions: {
					minValue: 1551,
					maxValue: 2649,
				},
				description:
					'First Gregorian year of the annual pillar overlay. Omit it to leave annualPillars out of the response entirely.',
				routing: {
					send: {
						type: 'body',
						property: 'annualFromYear',
					},
				},
			},
			{
				displayName: 'Annual Years',
				name: 'annualYears',
				type: 'number',
				default: 10,
				typeOptions: {
					minValue: 1,
					maxValue: 20,
				},
				description:
					'How many consecutive years the annual overlay covers, 1 to 20. Ignored unless annualFromYear is present.',
				routing: {
					send: {
						type: 'body',
						property: 'annualYears',
					},
				},
			},
			{
				displayName: 'Count',
				name: 'count',
				type: 'number',
				default: 8,
				typeOptions: {
					minValue: 1,
					maxValue: 12,
				},
				description:
					'How many ten-year luck pillars to return, 1 to 12. Eight covers eighty years from the start age, which reaches past a normal lifetime for most start ages.',
				routing: {
					send: {
						type: 'body',
						property: 'count',
					},
				},
			},
			{
				displayName: 'Day Boundary',
				name: 'dayBoundary',
				type: 'options',
				options: [
					{
						name: 'Early Zi',
						value: 'early-zi',
					},
					{
						name: 'Midnight',
						value: 'midnight',
					},
					{
						name: 'Split Zi',
						value: 'split-zi',
					},
				],
				default: 'split-zi',
				description:
					'Which instant starts the sexagenary DAY, which only matters for a birth between 23:00 and 23:59',
				routing: {
					send: {
						type: 'body',
						property: 'dayBoundary',
					},
				},
			},
			{
				displayName: 'Hour Clock',
				name: 'hourClock',
				type: 'options',
				options: [
					{
						name: 'Clock',
						value: 'clock',
					},
					{
						name: 'Local Mean',
						value: 'local-mean',
					},
					{
						name: 'Solar',
						value: 'solar',
					},
				],
				default: 'clock',
				description:
					'Which clock the day boundary and the hour branch are read from, so a correction that carries a birth across midnight moves the day pillar with the hour. "clock" is civil time exactly as a birth certificate records it, which is what most calculators use and the default here.',
				routing: {
					send: {
						type: 'body',
						property: 'hourClock',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Latitude',
				name: 'latitude',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: -90,
					maxValue: 90,
					numberPrecision: 6,
				},
				description:
					'Birth latitude in decimal degrees. Accepted for consistency with the other birth-data endpoints and does not affect any part of a BaZi chart.',
				routing: {
					send: {
						type: 'body',
						property: 'latitude',
					},
				},
			},
			{
				displayName: 'Longitude',
				name: 'longitude',
				type: 'number',
				default: 116.4,
				typeOptions: {
					minValue: -180,
					maxValue: 180,
					numberPrecision: 6,
				},
				description: 'Birth longitude in decimal degrees. Positive is East, negative is West.',
				routing: {
					send: {
						type: 'body',
						property: 'longitude',
					},
				},
			},
			{
				displayName: 'Year Boundary',
				name: 'yearBoundary',
				type: 'options',
				options: [
					{
						name: 'Li Chun',
						value: 'li-chun',
					},
					{
						name: 'Lunar New Year',
						value: 'lunar-new-year',
					},
				],
				default: 'li-chun',
				description:
					'Which instant starts the sexagenary YEAR. "li-chun" is Beginning of Spring, around 4 February, and is the classical rule every BaZi text uses, so it is the default on this endpoint.',
				routing: {
					send: {
						type: 'body',
						property: 'yearBoundary',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['calculateLunarDate'],
			},
		},
		options: [
			{
				displayName: 'Date',
				name: 'date',
				type: 'string',
				default: '',
				placeholder: 'e.g. 1990-06-15',
				description:
					'Gregorian date to convert to the lunisolar calendar. Send this OR the lunar fields, never both.',
				routing: {
					send: {
						type: 'body',
						property: 'date',
					},
				},
			},
			{
				displayName: 'Is Leap Month',
				name: 'isLeapMonth',
				type: 'boolean',
				default: false,
				description:
					'Whether to address the leap repetition of lunarMonth rather than the first pass. Requesting a leap month a year does not have returns 400.',
				routing: {
					send: {
						type: 'body',
						property: 'isLeapMonth',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Lunar Day',
				name: 'lunarDay',
				type: 'number',
				default: 23,
				typeOptions: {
					minValue: 1,
					maxValue: 30,
				},
				description: 'Day of the lunar month, 1 to 30. Requires lunarYear and lunarMonth.',
				routing: {
					send: {
						type: 'body',
						property: 'lunarDay',
					},
				},
			},
			{
				displayName: 'Lunar Month',
				name: 'lunarMonth',
				type: 'number',
				default: 5,
				typeOptions: {
					minValue: 1,
					maxValue: 12,
				},
				description: 'Lunar month, 1 to 12. Requires lunarYear and lunarDay.',
				routing: {
					send: {
						type: 'body',
						property: 'lunarMonth',
					},
				},
			},
			{
				displayName: 'Lunar Year',
				name: 'lunarYear',
				type: 'number',
				default: 1990,
				typeOptions: {
					minValue: 1900,
					maxValue: 2100,
				},
				description:
					'Lunisolar year to convert back to a Gregorian date. Requires lunarMonth and lunarDay.',
				routing: {
					send: {
						type: 'body',
						property: 'lunarYear',
					},
				},
			},
		],
	},
	{
		displayName: 'Date',
		name: 'date',
		type: 'string',
		default: '',
		placeholder: 'e.g. 1990-06-15',
		required: true,
		description:
			'Birth date in YYYY-MM-DD format. Only the date is needed: the zodiac animal is a property of the year, so no time, timezone or place changes the answer.',
		routing: {
			send: {
				type: 'body',
				property: 'date',
			},
		},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['calculateZodiacAnimal'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['calculateZodiacAnimal'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Year Boundary',
				name: 'yearBoundary',
				type: 'options',
				options: [
					{
						name: 'Li Chun',
						value: 'li-chun',
					},
					{
						name: 'Lunar New Year',
						value: 'lunar-new-year',
					},
				],
				default: 'lunar-new-year',
				description:
					'Which instant starts the zodiac year. lunar-new-year is the folk rule and the default on this route, because it is the rule people mean when they say what animal they are: the sign turns on Chinese New Year, between late January and late February. li-chun is the classical rule every Four Pillars...',
				routing: {
					send: {
						type: 'body',
						property: 'yearBoundary',
					},
				},
			},
		],
	},
	{
		displayName: 'Date',
		name: 'date',
		type: 'string',
		default: '',
		placeholder: 'e.g. 1990-06-15',
		required: true,
		description: 'Birth date in YYYY-MM-DD format. Sets the year, month and day pillars.',
		routing: {
			send: {
				type: 'body',
				property: 'date',
			},
		},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['generateBaziChart'],
			},
		},
	},
	{
		displayName: 'Time',
		name: 'time',
		type: 'string',
		default: '',
		placeholder: 'e.g. 14:30:00',
		required: true,
		description:
			'Birth time in 24-hour HH:MM:SS format. Sets the hour pillar, which is one of the four and carries the whole picture of later life and offspring.',
		routing: {
			send: {
				type: 'body',
				property: 'time',
			},
		},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['generateBaziChart'],
			},
		},
	},
	{
		displayName: 'Timezone',
		name: 'timezone',
		type: 'string',
		default: '',
		placeholder: 'e.g. America/New_York or -5',
		required: true,
		description:
			'IANA name (e.g. "America/New_York", "Europe/London", "UTC"), decimal hours (e.g. -5 for EST, 1 for CET), or a fixed UTC offset (e.g. "-05:00", "+01:00").',
		routing: {
			send: {
				type: 'body',
				property: 'timezone',
				value: '={{ $value !== "" && !isNaN(Number($value)) ? Number($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['generateBaziChart'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['generateBaziChart'],
			},
		},
		options: [
			{
				displayName: 'Day Boundary',
				name: 'dayBoundary',
				type: 'options',
				options: [
					{
						name: 'Early Zi',
						value: 'early-zi',
					},
					{
						name: 'Midnight',
						value: 'midnight',
					},
					{
						name: 'Split Zi',
						value: 'split-zi',
					},
				],
				default: 'split-zi',
				description:
					'Which instant starts the sexagenary DAY, which only matters for a birth between 23:00 and 23:59',
				routing: {
					send: {
						type: 'body',
						property: 'dayBoundary',
					},
				},
			},
			{
				displayName: 'Hour Clock',
				name: 'hourClock',
				type: 'options',
				options: [
					{
						name: 'Clock',
						value: 'clock',
					},
					{
						name: 'Local Mean',
						value: 'local-mean',
					},
					{
						name: 'Solar',
						value: 'solar',
					},
				],
				default: 'clock',
				description:
					'Which clock the day boundary and the hour branch are read from, so a correction that carries a birth across midnight moves the day pillar with the hour. "clock" is civil time exactly as a birth certificate records it, which is what most calculators use and the default here.',
				routing: {
					send: {
						type: 'body',
						property: 'hourClock',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Latitude',
				name: 'latitude',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: -90,
					maxValue: 90,
					numberPrecision: 6,
				},
				description:
					'Birth latitude in decimal degrees. Accepted for consistency with the other birth-data endpoints and does not affect any part of a BaZi chart.',
				routing: {
					send: {
						type: 'body',
						property: 'latitude',
					},
				},
			},
			{
				displayName: 'Longitude',
				name: 'longitude',
				type: 'number',
				default: 116.4,
				typeOptions: {
					minValue: -180,
					maxValue: 180,
					numberPrecision: 6,
				},
				description: 'Birth longitude in decimal degrees. Positive is East, negative is West.',
				routing: {
					send: {
						type: 'body',
						property: 'longitude',
					},
				},
			},
			{
				displayName: 'Year Boundary',
				name: 'yearBoundary',
				type: 'options',
				options: [
					{
						name: 'Li Chun',
						value: 'li-chun',
					},
					{
						name: 'Lunar New Year',
						value: 'lunar-new-year',
					},
				],
				default: 'li-chun',
				description:
					'Which instant starts the sexagenary YEAR. "li-chun" is Beginning of Spring, around 4 February, and is the classical rule every BaZi text uses, so it is the default on this endpoint.',
				routing: {
					send: {
						type: 'body',
						property: 'yearBoundary',
					},
				},
			},
		],
	},
	{
		displayName: 'Date',
		name: 'date',
		type: 'string',
		default: '',
		placeholder: 'e.g. 1990-06-15',
		required: true,
		description:
			'Gregorian date in YYYY-MM-DD format, evaluated at the reference meridian. Years 1900 to 2100.',
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['getAlmanacDay'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['getAlmanacDay'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'options',
		options: [
			{
				name: 'Dog',
				value: 'dog',
			},
			{
				name: 'Dragon',
				value: 'dragon',
			},
			{
				name: 'Goat',
				value: 'goat',
			},
			{
				name: 'Horse',
				value: 'horse',
			},
			{
				name: 'Monkey',
				value: 'monkey',
			},
			{
				name: 'Ox',
				value: 'ox',
			},
			{
				name: 'Pig',
				value: 'pig',
			},
			{
				name: 'Rabbit',
				value: 'rabbit',
			},
			{
				name: 'Rat',
				value: 'rat',
			},
			{
				name: 'Rooster',
				value: 'rooster',
			},
			{
				name: 'Snake',
				value: 'snake',
			},
			{
				name: 'Tiger',
				value: 'tiger',
			},
		],
		default: 'rat',
		required: true,
		description:
			'Animal ID, case-insensitive. One of rat, ox, tiger, rabbit, dragon, snake, horse, goat, monkey, rooster, dog, pig.',
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['getDailyZodiacReading'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['getDailyZodiacReading'],
			},
		},
		options: [
			{
				displayName: 'Date',
				name: 'date',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-04-03',
				description:
					'Reading date in YYYY-MM-DD format. Past and future dates are both supported, for editorial scheduling and backfill.',
				routing: {
					send: {
						type: 'query',
						property: 'date',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Timezone',
				name: 'timezone',
				type: 'string',
				default: '',
				placeholder: 'e.g. America/New_York',
				description:
					'Selects which day counts as current when date is omitted. Defaults to UTC, so the reading rolls over at 00:00 UTC each day.',
				routing: {
					send: {
						type: 'query',
						property: 'timezone',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['getMonthlyAlmanac'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Month',
				name: 'month',
				type: 'number',
				default: 6,
				typeOptions: {
					minValue: 1,
					maxValue: 12,
				},
				description:
					'Gregorian month, 1 to 12. Defaults to the current UTC month when omitted, together with year.',
				routing: {
					send: {
						type: 'query',
						property: 'month',
					},
				},
			},
			{
				displayName: 'Year',
				name: 'year',
				type: 'number',
				default: 1990,
				typeOptions: {
					minValue: 1900,
					maxValue: 2100,
				},
				description:
					'Gregorian year, 1900 to 2100. Defaults to the current UTC year when omitted, together with month.',
				routing: {
					send: {
						type: 'query',
						property: 'year',
					},
				},
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'options',
		options: [
			{
				name: 'Dog',
				value: 'dog',
			},
			{
				name: 'Dragon',
				value: 'dragon',
			},
			{
				name: 'Goat',
				value: 'goat',
			},
			{
				name: 'Horse',
				value: 'horse',
			},
			{
				name: 'Monkey',
				value: 'monkey',
			},
			{
				name: 'Ox',
				value: 'ox',
			},
			{
				name: 'Pig',
				value: 'pig',
			},
			{
				name: 'Rabbit',
				value: 'rabbit',
			},
			{
				name: 'Rat',
				value: 'rat',
			},
			{
				name: 'Rooster',
				value: 'rooster',
			},
			{
				name: 'Snake',
				value: 'snake',
			},
			{
				name: 'Tiger',
				value: 'tiger',
			},
		],
		default: 'rat',
		required: true,
		description:
			'Animal ID, case-insensitive and punctuation-insensitive. One of rat, ox, tiger, rabbit, dragon, snake, horse, goat, monkey, rooster, dog, pig.',
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['getZodiacAnimal'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['getZodiacAnimal'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Sign1',
		name: 'sign1',
		type: 'options',
		options: [
			{
				name: 'Dog',
				value: 'dog',
			},
			{
				name: 'Dragon',
				value: 'dragon',
			},
			{
				name: 'Goat',
				value: 'goat',
			},
			{
				name: 'Horse',
				value: 'horse',
			},
			{
				name: 'Monkey',
				value: 'monkey',
			},
			{
				name: 'Ox',
				value: 'ox',
			},
			{
				name: 'Pig',
				value: 'pig',
			},
			{
				name: 'Rabbit',
				value: 'rabbit',
			},
			{
				name: 'Rat',
				value: 'rat',
			},
			{
				name: 'Rooster',
				value: 'rooster',
			},
			{
				name: 'Snake',
				value: 'snake',
			},
			{
				name: 'Tiger',
				value: 'tiger',
			},
		],
		default: 'rat',
		required: true,
		description:
			'First animal ID, case-insensitive. One of rat, ox, tiger, rabbit, dragon, snake, horse, goat, monkey, rooster, dog, pig.',
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['getZodiacCompatibility'],
			},
		},
	},
	{
		displayName: 'Sign2',
		name: 'sign2',
		type: 'options',
		options: [
			{
				name: 'Dog',
				value: 'dog',
			},
			{
				name: 'Dragon',
				value: 'dragon',
			},
			{
				name: 'Goat',
				value: 'goat',
			},
			{
				name: 'Horse',
				value: 'horse',
			},
			{
				name: 'Monkey',
				value: 'monkey',
			},
			{
				name: 'Ox',
				value: 'ox',
			},
			{
				name: 'Pig',
				value: 'pig',
			},
			{
				name: 'Rabbit',
				value: 'rabbit',
			},
			{
				name: 'Rat',
				value: 'rat',
			},
			{
				name: 'Rooster',
				value: 'rooster',
			},
			{
				name: 'Snake',
				value: 'snake',
			},
			{
				name: 'Tiger',
				value: 'tiger',
			},
		],
		default: 'dragon',
		required: true,
		description:
			'Second animal ID, case-insensitive. The relation is symmetric, so swapping the two returns the same relationship and the same score, with the reading written from the first sign point of view.',
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['getZodiacCompatibility'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['getZodiacCompatibility'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['listFiveElements'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Limit',
				name: 'maxResults',
				type: 'number',
				default: 5,
				typeOptions: {
					minValue: 1,
					maxValue: 5,
				},
				description: 'Maximum items to return per page. Range: 1-5, default 5.',
				routing: {
					send: {
						type: 'query',
						property: 'limit',
					},
				},
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: 0,
				},
				description: 'Number of items to skip for pagination. Default 0.',
				routing: {
					send: {
						type: 'query',
						property: 'offset',
					},
				},
			},
		],
	},
	{
		displayName: 'Year',
		name: 'year',
		type: 'number',
		default: 2026,
		typeOptions: {
			minValue: 1900,
			maxValue: 2100,
		},
		required: true,
		description:
			'Solar year, 1900 to 2100. The year opens at Li Chun rather than on 1 January, so its last two terms fall in the following January.',
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['listSolarTerms'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['listSolarTerms'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['listZodiacAnimals'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Limit',
				name: 'maxResults',
				type: 'number',
				default: 12,
				typeOptions: {
					minValue: 1,
					maxValue: 12,
				},
				description: 'Maximum items to return per page. Range: 1-12, default 12.',
				routing: {
					send: {
						type: 'query',
						property: 'limit',
					},
				},
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: 0,
				},
				description: 'Number of items to skip for pagination. Default 0.',
				routing: {
					send: {
						type: 'query',
						property: 'offset',
					},
				},
			},
		],
	},
	{
		displayName: 'Activity',
		name: 'activity',
		type: 'options',
		options: [
			{
				name: 'Burial',
				value: 'burial',
			},
			{
				name: 'Construction',
				value: 'construction',
			},
			{
				name: 'Groundbreaking',
				value: 'groundbreaking',
			},
			{
				name: 'Medical Treatment',
				value: 'medical-treatment',
			},
			{
				name: 'Moving House',
				value: 'moving-house',
			},
			{
				name: 'Opening Business',
				value: 'opening-business',
			},
			{
				name: 'Praying',
				value: 'praying',
			},
			{
				name: 'Signing Contracts',
				value: 'signing-contracts',
			},
			{
				name: 'Travel',
				value: 'travel',
			},
			{
				name: 'Wedding',
				value: 'wedding',
			},
		],
		default: 'wedding',
		required: true,
		description:
			'Activity to choose a date for. One of wedding, travel, moving-house, opening-business, signing-contracts, construction, groundbreaking, burial, medical-treatment, praying.',
		routing: {
			send: {
				type: 'body',
				property: 'activity',
			},
		},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['lookupAuspiciousDays'],
			},
		},
	},
	{
		displayName: 'Start Date',
		name: 'startDate',
		type: 'string',
		default: '',
		placeholder: 'e.g. 2026-03-01',
		required: true,
		description: 'First date of the range to search, inclusive',
		routing: {
			send: {
				type: 'body',
				property: 'startDate',
			},
		},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['lookupAuspiciousDays'],
			},
		},
	},
	{
		displayName: 'End Date',
		name: 'endDate',
		type: 'string',
		default: '',
		placeholder: 'e.g. 2026-04-30',
		required: true,
		description: 'Last date of the range to search, inclusive. The range may not exceed 93 days.',
		routing: {
			send: {
				type: 'body',
				property: 'endDate',
			},
		},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['lookupAuspiciousDays'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['chineseAstrology'],
				operation: ['lookupAuspiciousDays'],
			},
		},
		options: [
			{
				displayName: 'Avoid Animal',
				name: 'avoidAnimal',
				type: 'options',
				options: [
					{
						name: 'Dog',
						value: 'dog',
					},
					{
						name: 'Dragon',
						value: 'dragon',
					},
					{
						name: 'Goat',
						value: 'goat',
					},
					{
						name: 'Horse',
						value: 'horse',
					},
					{
						name: 'Monkey',
						value: 'monkey',
					},
					{
						name: 'Ox',
						value: 'ox',
					},
					{
						name: 'Pig',
						value: 'pig',
					},
					{
						name: 'Rabbit',
						value: 'rabbit',
					},
					{
						name: 'Rat',
						value: 'rat',
					},
					{
						name: 'Rooster',
						value: 'rooster',
					},
					{
						name: 'Snake',
						value: 'snake',
					},
					{
						name: 'Tiger',
						value: 'tiger',
					},
				],
				default: 'rat',
				description:
					'Zodiac animal to protect. Days that clash with this animal are dropped from the results, which is how a date is chosen around the people attending rather than in the abstract.',
				routing: {
					send: {
						type: 'body',
						property: 'avoidAnimal',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
];
