// Generated by scripts/generate.mts from specs/openapi.json. Do not edit.
import type { INodeProperties } from 'n8n-workflow';

export const crystalsDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['crystals'],
			},
		},
		options: [
			{
				name: 'Get Birthstones',
				value: 'getBirthstones',
				action: 'Get birthstones',
				description: 'Birthstones by month: Birthstone lookup API',
				routing: {
					request: {
						method: 'GET',
						url: '=/crystals/birthstone/{{encodeURIComponent($parameter["month"])}}',
					},
				},
			},
			{
				name: 'Get Crystal',
				value: 'getCrystal',
				action: 'Get crystal',
				description: 'Get crystal by ID: Crystal healing properties API',
				routing: {
					request: {
						method: 'GET',
						url: '=/crystals/{{encodeURIComponent($parameter["id"])}}',
					},
				},
			},
			{
				name: 'Get Crystal Pairings',
				value: 'getCrystalPairings',
				action: 'Get crystal pairings',
				description: 'Crystal pairings: Crystal combination API',
				routing: {
					request: {
						method: 'GET',
						url: '=/crystals/pairings/{{encodeURIComponent($parameter["id"])}}',
					},
				},
			},
			{
				name: 'Get Crystals by Chakra',
				value: 'getCrystalsByChakra',
				action: 'Get crystals by chakra',
				description: 'Crystals by chakra: Chakra healing stones API',
				routing: {
					request: {
						method: 'GET',
						url: '=/crystals/chakra/{{encodeURIComponent($parameter["chakra"])}}',
					},
				},
			},
			{
				name: 'Get Crystals by Element',
				value: 'getCrystalsByElement',
				action: 'Get crystals by element',
				description: 'Crystals by element: Elemental crystal lookup API',
				routing: {
					request: {
						method: 'GET',
						url: '=/crystals/element/{{encodeURIComponent($parameter["element"])}}',
					},
				},
			},
			{
				name: 'Get Crystals by Zodiac',
				value: 'getCrystalsByZodiac',
				action: 'Get crystals by zodiac',
				description: 'Crystals by zodiac sign: Zodiac birthstone API',
				routing: {
					request: {
						method: 'GET',
						url: '=/crystals/zodiac/{{encodeURIComponent($parameter["sign"])}}',
					},
				},
			},
			{
				name: 'Get Daily Crystal',
				value: 'getDailyCrystal',
				action: 'Get daily crystal',
				description: 'Daily crystal: Crystal of the day API',
				routing: {
					request: {
						method: 'POST',
						url: '/crystals/daily',
					},
				},
			},
			{
				name: 'Get Random Crystal',
				value: 'getRandomCrystal',
				action: 'Get random crystal',
				description: 'Random crystal: Crystal discovery API',
				routing: {
					request: {
						method: 'GET',
						url: '/crystals/random',
					},
				},
			},
			{
				name: 'List Crystal Colors',
				value: 'listCrystalColors',
				action: 'List crystal colors',
				description: 'List crystal colors: Crystal color filter API',
				routing: {
					request: {
						method: 'GET',
						url: '/crystals/colors',
					},
				},
			},
			{
				name: 'List Crystal Planets',
				value: 'listCrystalPlanets',
				action: 'List crystal planets',
				description: 'List crystal planets: Planetary ruler filter API',
				routing: {
					request: {
						method: 'GET',
						url: '/crystals/planets',
					},
				},
			},
			{
				name: 'List Crystals',
				value: 'listCrystals',
				action: 'List crystals',
				description: 'List all crystals: Crystal healing database API',
				routing: {
					request: {
						method: 'GET',
						url: '/crystals',
					},
				},
			},
			{
				name: 'Search Crystals',
				value: 'searchCrystals',
				action: 'Search crystals',
				description: 'Search crystals: Crystal search API',
				routing: {
					request: {
						method: 'GET',
						url: '/crystals/search',
					},
				},
			},
		],
		default: 'getBirthstones',
	},
	{
		displayName: 'Month',
		name: 'month',
		type: 'number',
		default: 2,
		typeOptions: {
			minValue: 1,
			maxValue: 12,
		},
		required: true,
		description: 'Birth month as a number from 1 (January) to 12 (December)',
		displayOptions: {
			show: {
				resource: ['crystals'],
				operation: ['getBirthstones'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['crystals'],
				operation: ['getBirthstones'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		placeholder: 'e.g. amethyst',
		required: true,
		description:
			'URL-safe crystal identifier, case-insensitive (e.g., "amethyst", "Amethyst", "rose-quartz" all resolve). Must match an entry in the database.',
		displayOptions: {
			show: {
				resource: ['crystals'],
				operation: ['getCrystal'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['crystals'],
				operation: ['getCrystal'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		placeholder: 'e.g. amethyst',
		required: true,
		description:
			'URL-safe crystal identifier to find pairings for, case-insensitive (e.g., "amethyst", "Amethyst", "rose-quartz" all resolve)',
		displayOptions: {
			show: {
				resource: ['crystals'],
				operation: ['getCrystalPairings'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['crystals'],
				operation: ['getCrystalPairings'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Chakra',
		name: 'chakra',
		type: 'options',
		options: [
			{
				name: 'Crown',
				value: 'Crown',
			},
			{
				name: 'Heart',
				value: 'Heart',
			},
			{
				name: 'Root',
				value: 'Root',
			},
			{
				name: 'Sacral',
				value: 'Sacral',
			},
			{
				name: 'Solar Plexus',
				value: 'Solar Plexus',
			},
			{
				name: 'Third Eye',
				value: 'Third Eye',
			},
			{
				name: 'Throat',
				value: 'Throat',
			},
		],
		default: 'Heart',
		required: true,
		description:
			'Chakra name, case-insensitive (e.g., heart, Heart, HEART all work). Valid: Root, Sacral, Solar Plexus, Heart, Throat, Third Eye, Crown.',
		displayOptions: {
			show: {
				resource: ['crystals'],
				operation: ['getCrystalsByChakra'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['crystals'],
				operation: ['getCrystalsByChakra'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Limit',
				name: 'maxResults',
				type: 'number',
				default: 20,
				typeOptions: {
					minValue: 1,
					maxValue: 30,
				},
				description: 'Maximum items to return per page. Range: 1-30, default 20.',
				routing: {
					send: {
						type: 'query',
						property: 'limit',
					},
				},
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: 0,
				},
				description: 'Number of items to skip for pagination. Default 0.',
				routing: {
					send: {
						type: 'query',
						property: 'offset',
					},
				},
			},
		],
	},
	{
		displayName: 'Element',
		name: 'element',
		type: 'options',
		options: [
			{
				name: 'Air',
				value: 'Air',
			},
			{
				name: 'Earth',
				value: 'Earth',
			},
			{
				name: 'Fire',
				value: 'Fire',
			},
			{
				name: 'Storm',
				value: 'Storm',
			},
			{
				name: 'Water',
				value: 'Water',
			},
		],
		default: 'Water',
		required: true,
		description:
			'Element name, case-insensitive (e.g., water, Water, WATER all work). Valid: Earth, Water, Fire, Air, Storm.',
		displayOptions: {
			show: {
				resource: ['crystals'],
				operation: ['getCrystalsByElement'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['crystals'],
				operation: ['getCrystalsByElement'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Limit',
				name: 'maxResults',
				type: 'number',
				default: 20,
				typeOptions: {
					minValue: 1,
					maxValue: 30,
				},
				description: 'Maximum items to return per page. Range: 1-30, default 20.',
				routing: {
					send: {
						type: 'query',
						property: 'limit',
					},
				},
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: 0,
				},
				description: 'Number of items to skip for pagination. Default 0.',
				routing: {
					send: {
						type: 'query',
						property: 'offset',
					},
				},
			},
		],
	},
	{
		displayName: 'Sign',
		name: 'sign',
		type: 'options',
		options: [
			{
				name: 'Aquarius',
				value: 'aquarius',
			},
			{
				name: 'Aries',
				value: 'aries',
			},
			{
				name: 'Cancer',
				value: 'cancer',
			},
			{
				name: 'Capricorn',
				value: 'capricorn',
			},
			{
				name: 'Gemini',
				value: 'gemini',
			},
			{
				name: 'Leo',
				value: 'leo',
			},
			{
				name: 'Libra',
				value: 'libra',
			},
			{
				name: 'Pisces',
				value: 'pisces',
			},
			{
				name: 'Sagittarius',
				value: 'sagittarius',
			},
			{
				name: 'Scorpio',
				value: 'scorpio',
			},
			{
				name: 'Taurus',
				value: 'taurus',
			},
			{
				name: 'Virgo',
				value: 'virgo',
			},
		],
		default: 'pisces',
		required: true,
		description:
			'Zodiac sign name, case-insensitive (e.g., pisces, Pisces, PISCES all work). Valid: aries, taurus, gemini, cancer, leo, virgo, libra, scorpio, sagittarius, capricorn, aquarius, pisces.',
		displayOptions: {
			show: {
				resource: ['crystals'],
				operation: ['getCrystalsByZodiac'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['crystals'],
				operation: ['getCrystalsByZodiac'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Limit',
				name: 'maxResults',
				type: 'number',
				default: 20,
				typeOptions: {
					minValue: 1,
					maxValue: 30,
				},
				description: 'Maximum items to return per page. Range: 1-30, default 20.',
				routing: {
					send: {
						type: 'query',
						property: 'limit',
					},
				},
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: 0,
				},
				description: 'Number of items to skip for pagination. Default 0.',
				routing: {
					send: {
						type: 'query',
						property: 'offset',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['crystals'],
				operation: ['getDailyCrystal'],
			},
		},
		options: [
			{
				displayName: 'Date',
				name: 'date',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-03-06',
				description: 'Date for the reading in YYYY-MM-DD format. Defaults to today (UTC).',
				routing: {
					send: {
						type: 'body',
						property: 'date',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Seed',
				name: 'seed',
				type: 'string',
				default: '',
				placeholder: 'e.g. user123',
				description:
					'Optional seed for reproducible readings. Same seed + same date = same crystal every time.',
				routing: {
					send: {
						type: 'body',
						property: 'seed',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['crystals'],
				operation: ['getRandomCrystal'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['crystals'],
				operation: ['listCrystalColors'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['crystals'],
				operation: ['listCrystalPlanets'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['crystals'],
				operation: ['listCrystals'],
			},
		},
		options: [
			{
				displayName: 'Chakra',
				name: 'chakra',
				type: 'options',
				options: [
					{
						name: 'Crown',
						value: 'Crown',
					},
					{
						name: 'Heart',
						value: 'Heart',
					},
					{
						name: 'Root',
						value: 'Root',
					},
					{
						name: 'Sacral',
						value: 'Sacral',
					},
					{
						name: 'Solar Plexus',
						value: 'Solar Plexus',
					},
					{
						name: 'Third Eye',
						value: 'Third Eye',
					},
					{
						name: 'Throat',
						value: 'Throat',
					},
				],
				default: 'Heart',
				description:
					'Filter by chakra association, case-insensitive. Valid values: Root, Sacral, Solar Plexus, Heart, Throat, Third Eye, Crown.',
				routing: {
					send: {
						type: 'query',
						property: 'chakra',
					},
				},
			},
			{
				displayName: 'Color',
				name: 'shade',
				type: 'string',
				default: '',
				placeholder: 'e.g. pink',
				description:
					'Filter by crystal color (partial match, case-insensitive). E.g., "pink", "green", "blue", "purple".',
				routing: {
					send: {
						type: 'query',
						property: 'color',
					},
				},
			},
			{
				displayName: 'Element',
				name: 'element',
				type: 'options',
				options: [
					{
						name: 'Air',
						value: 'Air',
					},
					{
						name: 'Earth',
						value: 'Earth',
					},
					{
						name: 'Fire',
						value: 'Fire',
					},
					{
						name: 'Storm',
						value: 'Storm',
					},
					{
						name: 'Water',
						value: 'Water',
					},
				],
				default: 'Water',
				description:
					'Filter by elemental association, case-insensitive. Valid values: Earth, Water, Fire, Air, Storm.',
				routing: {
					send: {
						type: 'query',
						property: 'element',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Limit',
				name: 'maxResults',
				type: 'number',
				default: 20,
				typeOptions: {
					minValue: 1,
					maxValue: 100,
				},
				description: 'Maximum items to return per page. Range: 1-100, default 20.',
				routing: {
					send: {
						type: 'query',
						property: 'limit',
					},
				},
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: 0,
				},
				description: 'Number of items to skip for pagination. Default 0.',
				routing: {
					send: {
						type: 'query',
						property: 'offset',
					},
				},
			},
			{
				displayName: 'Planet',
				name: 'planet',
				type: 'string',
				default: '',
				placeholder: 'e.g. Venus',
				description:
					'Filter by planetary association (partial match, case-insensitive). E.g., "Venus", "Moon", "Jupiter".',
				routing: {
					send: {
						type: 'query',
						property: 'planet',
					},
				},
			},
			{
				displayName: 'Zodiac',
				name: 'zodiac',
				type: 'options',
				options: [
					{
						name: 'Aquarius',
						value: 'aquarius',
					},
					{
						name: 'Aries',
						value: 'aries',
					},
					{
						name: 'Cancer',
						value: 'cancer',
					},
					{
						name: 'Capricorn',
						value: 'capricorn',
					},
					{
						name: 'Gemini',
						value: 'gemini',
					},
					{
						name: 'Leo',
						value: 'leo',
					},
					{
						name: 'Libra',
						value: 'libra',
					},
					{
						name: 'Pisces',
						value: 'pisces',
					},
					{
						name: 'Sagittarius',
						value: 'sagittarius',
					},
					{
						name: 'Scorpio',
						value: 'scorpio',
					},
					{
						name: 'Taurus',
						value: 'taurus',
					},
					{
						name: 'Virgo',
						value: 'virgo',
					},
				],
				default: 'pisces',
				description:
					'Filter by zodiac sign, case-insensitive. Valid values: aries, taurus, gemini, cancer, leo, virgo, libra, scorpio, sagittarius, capricorn, aquarius, pisces.',
				routing: {
					send: {
						type: 'query',
						property: 'zodiac',
					},
				},
			},
		],
	},
	{
		displayName: 'Query',
		name: 'q',
		type: 'string',
		default: '',
		placeholder: 'e.g. love',
		required: true,
		description:
			'Search query (2-50 characters). Matches against crystal names, keywords, descriptions, and meaning fields.',
		routing: {
			send: {
				type: 'query',
				property: 'q',
			},
		},
		displayOptions: {
			show: {
				resource: ['crystals'],
				operation: ['searchCrystals'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['crystals'],
				operation: ['searchCrystals'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Limit',
				name: 'maxResults',
				type: 'number',
				default: 20,
				typeOptions: {
					minValue: 1,
					maxValue: 50,
				},
				description: 'Maximum items to return per page. Range: 1-50, default 20.',
				routing: {
					send: {
						type: 'query',
						property: 'limit',
					},
				},
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: 0,
				},
				description: 'Number of items to skip for pagination. Default 0.',
				routing: {
					send: {
						type: 'query',
						property: 'offset',
					},
				},
			},
		],
	},
];
