// Generated by scripts/generate.mts from specs/openapi.json. Do not edit.
import type { INodeProperties } from 'n8n-workflow';

export const dreamsDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['dreams'],
			},
		},
		options: [
			{
				name: 'Get Daily Dream Symbol',
				value: 'getDailyDreamSymbol',
				action: 'Get daily dream symbol',
				description: 'Daily dream symbol: Dream symbol of the day API',
				routing: {
					request: {
						method: 'POST',
						url: '/dreams/daily',
					},
				},
			},
			{
				name: 'Get Dream Symbol',
				value: 'getDreamSymbol',
				action: 'Get dream symbol',
				description: 'Get dream symbol by ID: Dream interpretation API',
				routing: {
					request: {
						method: 'GET',
						url: '=/dreams/symbols/{{encodeURIComponent($parameter["id"])}}',
					},
				},
			},
			{
				name: 'Get Random Symbols',
				value: 'getRandomSymbols',
				action: 'Get random symbols',
				description: 'Random dream symbols: Dream symbol discovery API',
				routing: {
					request: {
						method: 'GET',
						url: '/dreams/symbols/random',
					},
				},
			},
			{
				name: 'Get Symbol Letter Counts',
				value: 'getSymbolLetterCounts',
				action: 'Get symbol letter counts',
				description: 'Symbol counts by letter: Dream dictionary index API',
				routing: {
					request: {
						method: 'GET',
						url: '/dreams/symbols/letters',
					},
				},
			},
			{
				name: 'Search Dream Symbols',
				value: 'searchDreamSymbols',
				action: 'Search dream symbols',
				description: 'List and search dream symbols: Dream dictionary API',
				routing: {
					request: {
						method: 'GET',
						url: '/dreams/symbols',
					},
				},
			},
		],
		default: 'getDailyDreamSymbol',
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['dreams'],
				operation: ['getDailyDreamSymbol'],
			},
		},
		options: [
			{
				displayName: 'Date',
				name: 'date',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-03-06',
				description: 'Date for the reading in YYYY-MM-DD format. Defaults to today (UTC).',
				routing: {
					send: {
						type: 'body',
						property: 'date',
					},
				},
			},
			{
				displayName: 'Seed',
				name: 'seed',
				type: 'string',
				default: '',
				placeholder: 'e.g. user123',
				description:
					'Optional seed for reproducible readings. Same seed + same date = same symbol every time.',
				routing: {
					send: {
						type: 'body',
						property: 'seed',
					},
				},
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		placeholder: 'e.g. snake',
		required: true,
		description:
			'Unique symbol identifier in kebab-case (e.g., "snake", "being-chased", "teeth-falling-out")',
		displayOptions: {
			show: {
				resource: ['dreams'],
				operation: ['getDreamSymbol'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['dreams'],
				operation: ['getRandomSymbols'],
			},
		},
		options: [
			{
				displayName: 'Count',
				name: 'count',
				type: 'number',
				default: 1,
				typeOptions: {
					minValue: 1,
					maxValue: 10,
				},
				description: 'Number of random symbols to return (1-10). Default: 1.',
				routing: {
					send: {
						type: 'query',
						property: 'count',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['dreams'],
				operation: ['searchDreamSymbols'],
			},
		},
		options: [
			{
				displayName: 'Letter',
				name: 'letter',
				type: 'string',
				default: '',
				placeholder: 'e.g. a',
				description: 'Filter symbols by starting letter (a-z). Case-insensitive.',
				routing: {
					send: {
						type: 'query',
						property: 'letter',
					},
				},
			},
			{
				displayName: 'Limit',
				name: 'maxResults',
				type: 'number',
				default: 20,
				typeOptions: {
					minValue: 1,
					maxValue: 50,
				},
				description: 'Maximum items to return per page. Range: 1-50, default 20.',
				routing: {
					send: {
						type: 'query',
						property: 'limit',
					},
				},
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: 0,
				},
				description: 'Number of items to skip for pagination. Default 0.',
				routing: {
					send: {
						type: 'query',
						property: 'offset',
					},
				},
			},
			{
				displayName: 'Q',
				name: 'q',
				type: 'string',
				default: '',
				placeholder: 'e.g. water',
				description: 'Search query to match against symbol names and meanings. Case-insensitive.',
				routing: {
					send: {
						type: 'query',
						property: 'q',
					},
				},
			},
		],
	},
];
