// Generated by scripts/generate.mts from specs/openapi.json. Do not edit.
import type { INodeProperties } from 'n8n-workflow';

export const forecastDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['forecast'],
			},
		},
		options: [
			{
				name: 'Find Significant Dates',
				value: 'findSignificantDates',
				action: 'Find significant dates',
				description: 'Significant dates: High-significance cross-domain forecast highlights',
				routing: {
					request: {
						method: 'POST',
						url: '/forecast/significant-dates',
					},
				},
			},
			{
				name: 'Forecast Solar Return',
				value: 'forecastSolarReturn',
				action: 'Forecast solar return',
				description: 'Solar return chart: Annual birthday forecast chart for a single subject',
				routing: {
					request: {
						method: 'POST',
						url: '/forecast/solar-return',
					},
				},
			},
			{
				name: 'Forecast Transits',
				value: 'forecastTransits',
				action: 'Forecast transits',
				description:
					'Western astrology forecast: aspects, ingresses, stations, eclipses, moon phases',
				routing: {
					request: {
						method: 'POST',
						url: '/forecast/transits',
					},
				},
			},
			{
				name: 'Generate Digest',
				value: 'generateDigest',
				action: 'Generate digest',
				description: 'Forecast digest: Pre-summarized next 24h, 7d, 30d, and 90d rollups',
				routing: {
					request: {
						method: 'POST',
						url: '/forecast/digest',
					},
				},
			},
			{
				name: 'Generate Timeline',
				value: 'generateTimeline',
				action: 'Generate timeline',
				description:
					'Cross-domain forecast timeline: Transits, ingresses, stations, dasha changes, critical days',
				routing: {
					request: {
						method: 'POST',
						url: '/forecast/timeline',
					},
				},
			},
		],
		default: 'findSignificantDates',
	},
	{
		displayName: 'Birth Data',
		name: 'birthData',
		type: 'json',
		default:
			'{\n  "date": "1990-07-15",\n  "time": "13:30:00",\n  "timezone": "America/New_York",\n  "latitude": 0,\n  "longitude": 0\n}',
		required: true,
		description:
			'The single birth subject this forecast is built for. One object only, never an array.',
		routing: {
			send: {
				type: 'body',
				property: 'birthData',
				value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['forecast'],
				operation: ['findSignificantDates'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['forecast'],
				operation: ['findSignificantDates'],
			},
		},
		options: [
			{
				displayName: 'Domain Weights',
				name: 'domainWeights',
				type: 'json',
				default: '{\n  "vedic": 1.5,\n  "biorhythm": 0.5\n}',
				description:
					'Per-domain significance multipliers applied before the significance floor and event cap. Bias which domains survive filtering and the cap.',
				routing: {
					send: {
						type: 'body',
						property: 'domainWeights',
						value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}',
					},
				},
			},
			{
				displayName: 'Domains',
				name: 'domains',
				type: 'multiOptions',
				options: [
					{
						name: 'Biorhythm',
						value: 'biorhythm',
					},
					{
						name: 'Vedic',
						value: 'vedic',
					},
					{
						name: 'Western',
						value: 'western',
					},
				],
				default: ['western', 'vedic', 'biorhythm'],
				description:
					'Which forecast domains to consider before filtering by significance. Defaults to all three.',
				routing: {
					send: {
						type: 'body',
						property: 'domains',
					},
				},
			},
			{
				displayName: 'End Date',
				name: 'endDate',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-08-30',
				description:
					'Last day of the window in YYYY-MM-DD format. Defaults to startDate plus 30 days.',
				routing: {
					send: {
						type: 'body',
						property: 'endDate',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Min Significance',
				name: 'minSignificance',
				type: 'number',
				default: 70,
				typeOptions: {
					minValue: 0,
					maxValue: 100,
					numberPrecision: 6,
				},
				description:
					'Significance floor from 0 to 100 for what counts as a significant date. Defaults to 70.',
				routing: {
					send: {
						type: 'body',
						property: 'minSignificance',
					},
				},
			},
			{
				displayName: 'Start Date',
				name: 'startDate',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-06-01',
				description: 'First day of the window in YYYY-MM-DD format. Defaults to today in UTC.',
				routing: {
					send: {
						type: 'body',
						property: 'startDate',
					},
				},
			},
		],
	},
	{
		displayName: 'Date',
		name: 'date',
		type: 'string',
		default: '',
		placeholder: 'e.g. 1990-07-15',
		required: true,
		description:
			'Birth date in YYYY-MM-DD format. Anchors the natal Sun longitude the transiting Sun returns to each year.',
		routing: {
			send: {
				type: 'body',
				property: 'date',
			},
		},
		displayOptions: {
			show: {
				resource: ['forecast'],
				operation: ['forecastSolarReturn'],
			},
		},
	},
	{
		displayName: 'Time',
		name: 'time',
		type: 'string',
		default: '',
		placeholder: 'e.g. 14:30:00',
		required: true,
		description:
			'Birth time in 24-hour HH:MM:SS format. Pins the exact natal Sun position that defines the solar return moment.',
		routing: {
			send: {
				type: 'body',
				property: 'time',
			},
		},
		displayOptions: {
			show: {
				resource: ['forecast'],
				operation: ['forecastSolarReturn'],
			},
		},
	},
	{
		displayName: 'Year',
		name: 'year',
		type: 'number',
		default: 2026,
		typeOptions: {
			minValue: 1900,
			maxValue: 2200,
		},
		required: true,
		description:
			'Year to cast the solar return for. The chart is erected for the moment in this year when the transiting Sun returns to the natal Sun longitude, on or within a day of the birthday.',
		routing: {
			send: {
				type: 'body',
				property: 'year',
			},
		},
		displayOptions: {
			show: {
				resource: ['forecast'],
				operation: ['forecastSolarReturn'],
			},
		},
	},
	{
		displayName: 'Latitude',
		name: 'latitude',
		type: 'number',
		default: 40.7128,
		typeOptions: {
			minValue: -90,
			maxValue: 90,
			numberPrecision: 6,
		},
		required: true,
		description:
			'Latitude of the solar return location in decimal degrees. The solar return is location-sensitive: use the birthplace to anchor the chart to natal geography, or the current city for a relocated solar return.',
		routing: {
			send: {
				type: 'body',
				property: 'latitude',
			},
		},
		displayOptions: {
			show: {
				resource: ['forecast'],
				operation: ['forecastSolarReturn'],
			},
		},
	},
	{
		displayName: 'Longitude',
		name: 'longitude',
		type: 'number',
		default: -74.006,
		typeOptions: {
			minValue: -180,
			maxValue: 180,
			numberPrecision: 6,
		},
		required: true,
		description:
			'Longitude of the solar return location in decimal degrees. Sets the local sidereal time, so it drives the Ascendant, Midheaven, and house cusps of the return chart.',
		routing: {
			send: {
				type: 'body',
				property: 'longitude',
			},
		},
		displayOptions: {
			show: {
				resource: ['forecast'],
				operation: ['forecastSolarReturn'],
			},
		},
	},
	{
		displayName: 'Timezone',
		name: 'timezone',
		type: 'string',
		default: '',
		placeholder: 'e.g. America/New_York or America/New_York',
		required: true,
		description:
			'IANA name (e.g. "America/New_York", "Europe/London", "UTC"), decimal hours (e.g. -5 for EST, 1 for CET), or a fixed UTC offset (e.g. "-05:00", "+01:00"). Prefer the IANA name: it is resolved to the offset in force at the birth date and time, historical daylight-saving rules included, while a...',
		routing: {
			send: {
				type: 'body',
				property: 'timezone',
				value: '={{ $value !== "" && !isNaN(Number($value)) ? Number($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['forecast'],
				operation: ['forecastSolarReturn'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['forecast'],
				operation: ['forecastSolarReturn'],
			},
		},
		options: [
			{
				displayName: 'House System',
				name: 'houseSystem',
				type: 'options',
				options: [
					{
						name: 'Equal',
						value: 'equal',
					},
					{
						name: 'Koch',
						value: 'koch',
					},
					{
						name: 'Placidus',
						value: 'placidus',
					},
					{
						name: 'Whole Sign',
						value: 'whole-sign',
					},
				],
				default: 'placidus',
				description:
					'House system for the return chart. placidus is the Western default. whole-sign, equal, and koch are also supported.',
				routing: {
					send: {
						type: 'body',
						property: 'houseSystem',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Birth Data',
		name: 'birthData',
		type: 'json',
		default:
			'{\n  "date": "1990-07-15",\n  "time": "13:30:00",\n  "timezone": "America/New_York",\n  "latitude": 0,\n  "longitude": 0\n}',
		required: true,
		description:
			'The single birth subject this transit forecast is built for. One object only, never an array.',
		routing: {
			send: {
				type: 'body',
				property: 'birthData',
				value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['forecast'],
				operation: ['forecastTransits'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['forecast'],
				operation: ['forecastTransits'],
			},
		},
		options: [
			{
				displayName: 'End Date',
				name: 'endDate',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-08-30',
				description:
					'Last day of the transit window in YYYY-MM-DD format. Defaults to startDate plus 30 days.',
				routing: {
					send: {
						type: 'body',
						property: 'endDate',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Min Significance',
				name: 'minSignificance',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: 0,
					maxValue: 100,
					numberPrecision: 6,
				},
				description:
					'Drop transit events scoring below this significance threshold from 0 to 100. Defaults to 0.',
				routing: {
					send: {
						type: 'body',
						property: 'minSignificance',
					},
				},
			},
			{
				displayName: 'Start Date',
				name: 'startDate',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-06-01',
				description:
					'First day of the transit window in YYYY-MM-DD format. Defaults to today in UTC.',
				routing: {
					send: {
						type: 'body',
						property: 'startDate',
					},
				},
			},
		],
	},
	{
		displayName: 'Birth Data',
		name: 'birthData',
		type: 'json',
		default:
			'{\n  "date": "1990-07-15",\n  "time": "13:30:00",\n  "timezone": "America/New_York",\n  "latitude": 0,\n  "longitude": 0\n}',
		required: true,
		description:
			'The single birth subject this digest is built for. One object only, never an array.',
		routing: {
			send: {
				type: 'body',
				property: 'birthData',
				value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['forecast'],
				operation: ['generateDigest'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['forecast'],
				operation: ['generateDigest'],
			},
		},
		options: [
			{
				displayName: 'Domain Weights',
				name: 'domainWeights',
				type: 'json',
				default: '{\n  "vedic": 1.5,\n  "biorhythm": 0.5\n}',
				description:
					'Per-domain significance multipliers applied before the significance floor and event cap. Bias which domains survive filtering and the cap.',
				routing: {
					send: {
						type: 'body',
						property: 'domainWeights',
						value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}',
					},
				},
			},
			{
				displayName: 'Domains',
				name: 'domains',
				type: 'multiOptions',
				options: [
					{
						name: 'Biorhythm',
						value: 'biorhythm',
					},
					{
						name: 'Vedic',
						value: 'vedic',
					},
					{
						name: 'Western',
						value: 'western',
					},
				],
				default: ['western', 'vedic', 'biorhythm'],
				description:
					'Which forecast domains to include before rolling up the windows. Defaults to all three.',
				routing: {
					send: {
						type: 'body',
						property: 'domains',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Min Significance',
				name: 'minSignificance',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: 0,
					maxValue: 100,
					numberPrecision: 6,
				},
				description:
					'Drop events scoring below this significance threshold from 0 to 100 before the rollup. Defaults to 0.',
				routing: {
					send: {
						type: 'body',
						property: 'minSignificance',
					},
				},
			},
			{
				displayName: 'Start Date',
				name: 'startDate',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-06-01',
				description:
					'Start anchor for every window in YYYY-MM-DD format. The next 24h, 7d, 30d, and 90d windows are measured forward from this date at 00:00:00 UTC.',
				routing: {
					send: {
						type: 'body',
						property: 'startDate',
					},
				},
			},
			{
				displayName: 'Top',
				name: 'top',
				type: 'number',
				default: 3,
				typeOptions: {
					minValue: 0,
					maxValue: 20,
				},
				description:
					'Number of highest-significance events to surface per window. Defaults to 3, capped at 20.',
				routing: {
					send: {
						type: 'body',
						property: 'top',
					},
				},
			},
		],
	},
	{
		displayName: 'Birth Data',
		name: 'birthData',
		type: 'json',
		default:
			'{\n  "date": "1990-07-15",\n  "time": "13:30:00",\n  "timezone": "America/New_York",\n  "latitude": 0,\n  "longitude": 0\n}',
		required: true,
		description:
			'The single birth subject this forecast is built for. One object only, never an array.',
		routing: {
			send: {
				type: 'body',
				property: 'birthData',
				value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['forecast'],
				operation: ['generateTimeline'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['forecast'],
				operation: ['generateTimeline'],
			},
		},
		options: [
			{
				displayName: 'Domain Weights',
				name: 'domainWeights',
				type: 'json',
				default: '{\n  "vedic": 1.5,\n  "biorhythm": 0.5\n}',
				description:
					'Per-domain significance multipliers applied before the significance floor and event cap. Bias which domains survive filtering and the cap.',
				routing: {
					send: {
						type: 'body',
						property: 'domainWeights',
						value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}',
					},
				},
			},
			{
				displayName: 'Domains',
				name: 'domains',
				type: 'multiOptions',
				options: [
					{
						name: 'Biorhythm',
						value: 'biorhythm',
					},
					{
						name: 'Vedic',
						value: 'vedic',
					},
					{
						name: 'Western',
						value: 'western',
					},
				],
				default: ['western', 'vedic', 'biorhythm'],
				description: 'Which forecast domains to include. Defaults to all three.',
				routing: {
					send: {
						type: 'body',
						property: 'domains',
					},
				},
			},
			{
				displayName: 'End Date',
				name: 'endDate',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-08-30',
				description:
					'Last day of the forecast window in YYYY-MM-DD format. Defaults to startDate plus 30 days.',
				routing: {
					send: {
						type: 'body',
						property: 'endDate',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Min Significance',
				name: 'minSignificance',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: 0,
					maxValue: 100,
					numberPrecision: 6,
				},
				description:
					'Drop events scoring below this significance threshold from 0 to 100. Defaults to 0, keeping all events.',
				routing: {
					send: {
						type: 'body',
						property: 'minSignificance',
					},
				},
			},
			{
				displayName: 'Start Date',
				name: 'startDate',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-06-01',
				description:
					'First day of the forecast window in YYYY-MM-DD format. Defaults to today in UTC.',
				routing: {
					send: {
						type: 'body',
						property: 'startDate',
					},
				},
			},
		],
	},
];
