// Generated by scripts/generate.mts from specs/openapi.json. Do not edit.
import type { INodeProperties } from 'n8n-workflow';

export const humanDesignDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['humanDesign'],
			},
		},
		options: [
			{
				name: 'Calculate Centers',
				value: 'calculateCenters',
				action: 'Calculate centers',
				description: 'Calculate the nine Human Design centers',
				routing: {
					request: {
						method: 'POST',
						url: '/human-design/centers',
					},
				},
			},
			{
				name: 'Calculate Channels',
				value: 'calculateChannels',
				action: 'Calculate channels',
				description: 'Calculate the defined Human Design channels',
				routing: {
					request: {
						method: 'POST',
						url: '/human-design/channels',
					},
				},
			},
			{
				name: 'Calculate Connection',
				value: 'calculateConnection',
				action: 'Calculate connection',
				description:
					'Calculate Human Design connection chart: Two-person composite bodygraph compatibility',
				routing: {
					request: {
						method: 'POST',
						url: '/human-design/connection',
					},
				},
			},
			{
				name: 'Calculate Gates',
				value: 'calculateGates',
				action: 'Calculate gates',
				description: 'Calculate the 26 Human Design gate activations',
				routing: {
					request: {
						method: 'POST',
						url: '/human-design/gates',
					},
				},
			},
			{
				name: 'Calculate Penta',
				value: 'calculatePenta',
				action: 'Calculate penta',
				description:
					'Calculate Human Design Penta: Small-group BG5 operating system for three to five people',
				routing: {
					request: {
						method: 'POST',
						url: '/human-design/penta',
					},
				},
			},
			{
				name: 'Calculate Profile',
				value: 'calculateProfile',
				action: 'Calculate profile',
				description: 'Calculate the Human Design profile and line keynotes',
				routing: {
					request: {
						method: 'POST',
						url: '/human-design/profile',
					},
				},
			},
			{
				name: 'Calculate Type',
				value: 'calculateType',
				action: 'Calculate type',
				description: 'Calculate Human Design type, authority and profile',
				routing: {
					request: {
						method: 'POST',
						url: '/human-design/type',
					},
				},
			},
			{
				name: 'Calculate Variables',
				value: 'calculateVariables',
				action: 'Calculate variables',
				description:
					'Calculate Human Design Variables: The four arrows and Color, Tone, Base substructure',
				routing: {
					request: {
						method: 'POST',
						url: '/human-design/variables',
					},
				},
			},
			{
				name: 'Generate Bodygraph',
				value: 'generateBodygraph',
				action: 'Generate bodygraph',
				description:
					'Generate full Human Design bodygraph: Type, authority, profile, centers, channels, gates',
				routing: {
					request: {
						method: 'POST',
						url: '/human-design/bodygraph',
					},
				},
			},
			{
				name: 'Generate Transit',
				value: 'generateTransit',
				action: 'Generate transit',
				description:
					'Generate Human Design transit overlay: Current planetary activations on a natal bodygraph',
				routing: {
					request: {
						method: 'POST',
						url: '/human-design/transit',
					},
				},
			},
			{
				name: 'Get Center',
				value: 'getCenter',
				action: 'Get center',
				description: 'Look up a Human Design center by ID',
				routing: {
					request: {
						method: 'GET',
						url: '=/human-design/centers/{{encodeURIComponent($parameter["id"])}}',
					},
				},
			},
			{
				name: 'Get Gate',
				value: 'getGate',
				action: 'Get gate',
				description: 'Look up a Human Design gate by number',
				routing: {
					request: {
						method: 'GET',
						url: '=/human-design/gates/{{encodeURIComponent($parameter["number"])}}',
					},
				},
			},
		],
		default: 'calculateCenters',
	},
	{
		displayName: 'Date',
		name: 'date',
		type: 'string',
		default: '',
		placeholder: 'e.g. 1990-07-15',
		required: true,
		description:
			'Birth date in YYYY-MM-DD format. The anchor for both the Personality activations at birth and the Design activations 88 degrees of solar arc earlier.',
		routing: {
			send: {
				type: 'body',
				property: 'date',
			},
		},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculateCenters'],
			},
		},
	},
	{
		displayName: 'Time',
		name: 'time',
		type: 'string',
		default: '',
		placeholder: 'e.g. 13:00:00',
		required: true,
		description:
			'Birth time in 24-hour HH:MM:SS format. Precision matters: the profile lines and gate boundaries shift with the exact minute of birth.',
		routing: {
			send: {
				type: 'body',
				property: 'time',
			},
		},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculateCenters'],
			},
		},
	},
	{
		displayName: 'Timezone',
		name: 'timezone',
		type: 'string',
		default: '',
		placeholder: 'e.g. America/New_York or -5',
		required: true,
		description:
			'IANA name (e.g. "America/New_York", "Europe/London", "UTC"), decimal hours (e.g. -5 for EST, 1 for CET), or a fixed UTC offset (e.g. "-05:00", "+01:00").',
		routing: {
			send: {
				type: 'body',
				property: 'timezone',
				value: '={{ $value !== "" && !isNaN(Number($value)) ? Number($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculateCenters'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculateCenters'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Latitude',
				name: 'latitude',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: -90,
					maxValue: 90,
					numberPrecision: 6,
				},
				description:
					'Birth latitude in decimal degrees. Optional and does not affect the bodygraph, which depends only on ecliptic longitudes.',
				routing: {
					send: {
						type: 'body',
						property: 'latitude',
					},
				},
			},
			{
				displayName: 'Longitude',
				name: 'longitude',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: -180,
					maxValue: 180,
					numberPrecision: 6,
				},
				description:
					'Birth longitude in decimal degrees. Optional and does not affect the bodygraph.',
				routing: {
					send: {
						type: 'body',
						property: 'longitude',
					},
				},
			},
			{
				displayName: 'Node Type',
				name: 'nodeType',
				type: 'options',
				options: [
					{
						name: 'Mean',
						value: 'mean',
					},
					{
						name: 'True',
						value: 'true',
					},
				],
				default: 'true',
				description:
					'Lunar node convention. "mean" is the smoothed average node, which always moves retrograde; "true" is the osculating node, which tracks the real perturbed node, oscillates up to about 1.5 degrees either side of the mean on a 173-day cycle, and can briefly turn direct.',
				routing: {
					send: {
						type: 'body',
						property: 'nodeType',
					},
				},
			},
		],
	},
	{
		displayName: 'Date',
		name: 'date',
		type: 'string',
		default: '',
		placeholder: 'e.g. 1990-07-15',
		required: true,
		description:
			'Birth date in YYYY-MM-DD format. The anchor for both the Personality activations at birth and the Design activations 88 degrees of solar arc earlier.',
		routing: {
			send: {
				type: 'body',
				property: 'date',
			},
		},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculateChannels'],
			},
		},
	},
	{
		displayName: 'Time',
		name: 'time',
		type: 'string',
		default: '',
		placeholder: 'e.g. 13:00:00',
		required: true,
		description:
			'Birth time in 24-hour HH:MM:SS format. Precision matters: the profile lines and gate boundaries shift with the exact minute of birth.',
		routing: {
			send: {
				type: 'body',
				property: 'time',
			},
		},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculateChannels'],
			},
		},
	},
	{
		displayName: 'Timezone',
		name: 'timezone',
		type: 'string',
		default: '',
		placeholder: 'e.g. America/New_York or -5',
		required: true,
		description:
			'IANA name (e.g. "America/New_York", "Europe/London", "UTC"), decimal hours (e.g. -5 for EST, 1 for CET), or a fixed UTC offset (e.g. "-05:00", "+01:00").',
		routing: {
			send: {
				type: 'body',
				property: 'timezone',
				value: '={{ $value !== "" && !isNaN(Number($value)) ? Number($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculateChannels'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculateChannels'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Latitude',
				name: 'latitude',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: -90,
					maxValue: 90,
					numberPrecision: 6,
				},
				description:
					'Birth latitude in decimal degrees. Optional and does not affect the bodygraph, which depends only on ecliptic longitudes.',
				routing: {
					send: {
						type: 'body',
						property: 'latitude',
					},
				},
			},
			{
				displayName: 'Longitude',
				name: 'longitude',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: -180,
					maxValue: 180,
					numberPrecision: 6,
				},
				description:
					'Birth longitude in decimal degrees. Optional and does not affect the bodygraph.',
				routing: {
					send: {
						type: 'body',
						property: 'longitude',
					},
				},
			},
			{
				displayName: 'Node Type',
				name: 'nodeType',
				type: 'options',
				options: [
					{
						name: 'Mean',
						value: 'mean',
					},
					{
						name: 'True',
						value: 'true',
					},
				],
				default: 'true',
				description:
					'Lunar node convention. "mean" is the smoothed average node, which always moves retrograde; "true" is the osculating node, which tracks the real perturbed node, oscillates up to about 1.5 degrees either side of the mean on a 173-day cycle, and can briefly turn direct.',
				routing: {
					send: {
						type: 'body',
						property: 'nodeType',
					},
				},
			},
		],
	},
	{
		displayName: 'Person A',
		name: 'personA',
		type: 'json',
		default:
			'{\n  "date": "1990-07-15",\n  "time": "13:00:00",\n  "timezone": "America/New_York",\n  "latitude": 0,\n  "longitude": 0,\n  "nodeType": "true"\n}',
		required: true,
		description: 'Birth moment of the first person in the connection',
		routing: {
			send: {
				type: 'body',
				property: 'personA',
				value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculateConnection'],
			},
		},
	},
	{
		displayName: 'Person B',
		name: 'personB',
		type: 'json',
		default:
			'{\n  "date": "1990-07-15",\n  "time": "13:00:00",\n  "timezone": "America/New_York",\n  "latitude": 0,\n  "longitude": 0,\n  "nodeType": "true"\n}',
		required: true,
		description: 'Birth moment of the second person in the connection',
		routing: {
			send: {
				type: 'body',
				property: 'personB',
				value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculateConnection'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculateConnection'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Date',
		name: 'date',
		type: 'string',
		default: '',
		placeholder: 'e.g. 1990-07-15',
		required: true,
		description:
			'Birth date in YYYY-MM-DD format. The anchor for both the Personality activations at birth and the Design activations 88 degrees of solar arc earlier.',
		routing: {
			send: {
				type: 'body',
				property: 'date',
			},
		},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculateGates'],
			},
		},
	},
	{
		displayName: 'Time',
		name: 'time',
		type: 'string',
		default: '',
		placeholder: 'e.g. 13:00:00',
		required: true,
		description:
			'Birth time in 24-hour HH:MM:SS format. Precision matters: the profile lines and gate boundaries shift with the exact minute of birth.',
		routing: {
			send: {
				type: 'body',
				property: 'time',
			},
		},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculateGates'],
			},
		},
	},
	{
		displayName: 'Timezone',
		name: 'timezone',
		type: 'string',
		default: '',
		placeholder: 'e.g. America/New_York or -5',
		required: true,
		description:
			'IANA name (e.g. "America/New_York", "Europe/London", "UTC"), decimal hours (e.g. -5 for EST, 1 for CET), or a fixed UTC offset (e.g. "-05:00", "+01:00").',
		routing: {
			send: {
				type: 'body',
				property: 'timezone',
				value: '={{ $value !== "" && !isNaN(Number($value)) ? Number($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculateGates'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculateGates'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Latitude',
				name: 'latitude',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: -90,
					maxValue: 90,
					numberPrecision: 6,
				},
				description:
					'Birth latitude in decimal degrees. Optional and does not affect the bodygraph, which depends only on ecliptic longitudes.',
				routing: {
					send: {
						type: 'body',
						property: 'latitude',
					},
				},
			},
			{
				displayName: 'Longitude',
				name: 'longitude',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: -180,
					maxValue: 180,
					numberPrecision: 6,
				},
				description:
					'Birth longitude in decimal degrees. Optional and does not affect the bodygraph.',
				routing: {
					send: {
						type: 'body',
						property: 'longitude',
					},
				},
			},
			{
				displayName: 'Node Type',
				name: 'nodeType',
				type: 'options',
				options: [
					{
						name: 'Mean',
						value: 'mean',
					},
					{
						name: 'True',
						value: 'true',
					},
				],
				default: 'true',
				description:
					'Lunar node convention. "mean" is the smoothed average node, which always moves retrograde; "true" is the osculating node, which tracks the real perturbed node, oscillates up to about 1.5 degrees either side of the mean on a 173-day cycle, and can briefly turn direct.',
				routing: {
					send: {
						type: 'body',
						property: 'nodeType',
					},
				},
			},
		],
	},
	{
		displayName: 'Members',
		name: 'members',
		type: 'json',
		default:
			'[\n  {\n    "date": "1990-07-15",\n    "time": "13:00:00",\n    "timezone": "America/New_York",\n    "latitude": 0,\n    "longitude": 0,\n    "nodeType": "true"\n  }\n]',
		required: true,
		description:
			'Birth moments of the three to five people in the group. Below three no Penta forms; above five a second Penta emerges.',
		routing: {
			send: {
				type: 'body',
				property: 'members',
				value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculatePenta'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculatePenta'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Date',
		name: 'date',
		type: 'string',
		default: '',
		placeholder: 'e.g. 1990-07-15',
		required: true,
		description:
			'Birth date in YYYY-MM-DD format. The anchor for both the Personality activations at birth and the Design activations 88 degrees of solar arc earlier.',
		routing: {
			send: {
				type: 'body',
				property: 'date',
			},
		},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculateProfile'],
			},
		},
	},
	{
		displayName: 'Time',
		name: 'time',
		type: 'string',
		default: '',
		placeholder: 'e.g. 13:00:00',
		required: true,
		description:
			'Birth time in 24-hour HH:MM:SS format. Precision matters: the profile lines and gate boundaries shift with the exact minute of birth.',
		routing: {
			send: {
				type: 'body',
				property: 'time',
			},
		},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculateProfile'],
			},
		},
	},
	{
		displayName: 'Timezone',
		name: 'timezone',
		type: 'string',
		default: '',
		placeholder: 'e.g. America/New_York or -5',
		required: true,
		description:
			'IANA name (e.g. "America/New_York", "Europe/London", "UTC"), decimal hours (e.g. -5 for EST, 1 for CET), or a fixed UTC offset (e.g. "-05:00", "+01:00").',
		routing: {
			send: {
				type: 'body',
				property: 'timezone',
				value: '={{ $value !== "" && !isNaN(Number($value)) ? Number($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculateProfile'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculateProfile'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Latitude',
				name: 'latitude',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: -90,
					maxValue: 90,
					numberPrecision: 6,
				},
				description:
					'Birth latitude in decimal degrees. Optional and does not affect the bodygraph, which depends only on ecliptic longitudes.',
				routing: {
					send: {
						type: 'body',
						property: 'latitude',
					},
				},
			},
			{
				displayName: 'Longitude',
				name: 'longitude',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: -180,
					maxValue: 180,
					numberPrecision: 6,
				},
				description:
					'Birth longitude in decimal degrees. Optional and does not affect the bodygraph.',
				routing: {
					send: {
						type: 'body',
						property: 'longitude',
					},
				},
			},
			{
				displayName: 'Node Type',
				name: 'nodeType',
				type: 'options',
				options: [
					{
						name: 'Mean',
						value: 'mean',
					},
					{
						name: 'True',
						value: 'true',
					},
				],
				default: 'true',
				description:
					'Lunar node convention. "mean" is the smoothed average node, which always moves retrograde; "true" is the osculating node, which tracks the real perturbed node, oscillates up to about 1.5 degrees either side of the mean on a 173-day cycle, and can briefly turn direct.',
				routing: {
					send: {
						type: 'body',
						property: 'nodeType',
					},
				},
			},
		],
	},
	{
		displayName: 'Date',
		name: 'date',
		type: 'string',
		default: '',
		placeholder: 'e.g. 1990-07-15',
		required: true,
		description:
			'Birth date in YYYY-MM-DD format. The anchor for both the Personality activations at birth and the Design activations 88 degrees of solar arc earlier.',
		routing: {
			send: {
				type: 'body',
				property: 'date',
			},
		},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculateType'],
			},
		},
	},
	{
		displayName: 'Time',
		name: 'time',
		type: 'string',
		default: '',
		placeholder: 'e.g. 13:00:00',
		required: true,
		description:
			'Birth time in 24-hour HH:MM:SS format. Precision matters: the profile lines and gate boundaries shift with the exact minute of birth.',
		routing: {
			send: {
				type: 'body',
				property: 'time',
			},
		},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculateType'],
			},
		},
	},
	{
		displayName: 'Timezone',
		name: 'timezone',
		type: 'string',
		default: '',
		placeholder: 'e.g. America/New_York or -5',
		required: true,
		description:
			'IANA name (e.g. "America/New_York", "Europe/London", "UTC"), decimal hours (e.g. -5 for EST, 1 for CET), or a fixed UTC offset (e.g. "-05:00", "+01:00").',
		routing: {
			send: {
				type: 'body',
				property: 'timezone',
				value: '={{ $value !== "" && !isNaN(Number($value)) ? Number($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculateType'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculateType'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Latitude',
				name: 'latitude',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: -90,
					maxValue: 90,
					numberPrecision: 6,
				},
				description:
					'Birth latitude in decimal degrees. Optional and does not affect the bodygraph, which depends only on ecliptic longitudes.',
				routing: {
					send: {
						type: 'body',
						property: 'latitude',
					},
				},
			},
			{
				displayName: 'Longitude',
				name: 'longitude',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: -180,
					maxValue: 180,
					numberPrecision: 6,
				},
				description:
					'Birth longitude in decimal degrees. Optional and does not affect the bodygraph.',
				routing: {
					send: {
						type: 'body',
						property: 'longitude',
					},
				},
			},
			{
				displayName: 'Node Type',
				name: 'nodeType',
				type: 'options',
				options: [
					{
						name: 'Mean',
						value: 'mean',
					},
					{
						name: 'True',
						value: 'true',
					},
				],
				default: 'true',
				description:
					'Lunar node convention. "mean" is the smoothed average node, which always moves retrograde; "true" is the osculating node, which tracks the real perturbed node, oscillates up to about 1.5 degrees either side of the mean on a 173-day cycle, and can briefly turn direct.',
				routing: {
					send: {
						type: 'body',
						property: 'nodeType',
					},
				},
			},
		],
	},
	{
		displayName: 'Date',
		name: 'date',
		type: 'string',
		default: '',
		placeholder: 'e.g. 1990-07-15',
		required: true,
		description:
			'Birth date in YYYY-MM-DD format. The anchor for both the Personality activations at birth and the Design activations 88 degrees of solar arc earlier.',
		routing: {
			send: {
				type: 'body',
				property: 'date',
			},
		},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculateVariables'],
			},
		},
	},
	{
		displayName: 'Time',
		name: 'time',
		type: 'string',
		default: '',
		placeholder: 'e.g. 13:00:00',
		required: true,
		description:
			'Birth time in 24-hour HH:MM:SS format. Precision matters: the profile lines and gate boundaries shift with the exact minute of birth.',
		routing: {
			send: {
				type: 'body',
				property: 'time',
			},
		},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculateVariables'],
			},
		},
	},
	{
		displayName: 'Timezone',
		name: 'timezone',
		type: 'string',
		default: '',
		placeholder: 'e.g. America/New_York or -5',
		required: true,
		description:
			'IANA name (e.g. "America/New_York", "Europe/London", "UTC"), decimal hours (e.g. -5 for EST, 1 for CET), or a fixed UTC offset (e.g. "-05:00", "+01:00").',
		routing: {
			send: {
				type: 'body',
				property: 'timezone',
				value: '={{ $value !== "" && !isNaN(Number($value)) ? Number($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculateVariables'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['calculateVariables'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Latitude',
				name: 'latitude',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: -90,
					maxValue: 90,
					numberPrecision: 6,
				},
				description:
					'Birth latitude in decimal degrees. Optional and does not affect the bodygraph, which depends only on ecliptic longitudes.',
				routing: {
					send: {
						type: 'body',
						property: 'latitude',
					},
				},
			},
			{
				displayName: 'Longitude',
				name: 'longitude',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: -180,
					maxValue: 180,
					numberPrecision: 6,
				},
				description:
					'Birth longitude in decimal degrees. Optional and does not affect the bodygraph.',
				routing: {
					send: {
						type: 'body',
						property: 'longitude',
					},
				},
			},
			{
				displayName: 'Node Type',
				name: 'nodeType',
				type: 'options',
				options: [
					{
						name: 'Mean',
						value: 'mean',
					},
					{
						name: 'True',
						value: 'true',
					},
				],
				default: 'true',
				description:
					'Lunar node convention. "mean" is the smoothed average node, which always moves retrograde; "true" is the osculating node, which tracks the real perturbed node, oscillates up to about 1.5 degrees either side of the mean on a 173-day cycle, and can briefly turn direct.',
				routing: {
					send: {
						type: 'body',
						property: 'nodeType',
					},
				},
			},
		],
	},
	{
		displayName: 'Date',
		name: 'date',
		type: 'string',
		default: '',
		placeholder: 'e.g. 1990-07-15',
		required: true,
		description:
			'Birth date in YYYY-MM-DD format. The anchor for both the Personality activations at birth and the Design activations 88 degrees of solar arc earlier.',
		routing: {
			send: {
				type: 'body',
				property: 'date',
			},
		},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['generateBodygraph'],
			},
		},
	},
	{
		displayName: 'Time',
		name: 'time',
		type: 'string',
		default: '',
		placeholder: 'e.g. 13:00:00',
		required: true,
		description:
			'Birth time in 24-hour HH:MM:SS format. Precision matters: the profile lines and gate boundaries shift with the exact minute of birth.',
		routing: {
			send: {
				type: 'body',
				property: 'time',
			},
		},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['generateBodygraph'],
			},
		},
	},
	{
		displayName: 'Timezone',
		name: 'timezone',
		type: 'string',
		default: '',
		placeholder: 'e.g. America/New_York or -5',
		required: true,
		description:
			'IANA name (e.g. "America/New_York", "Europe/London", "UTC"), decimal hours (e.g. -5 for EST, 1 for CET), or a fixed UTC offset (e.g. "-05:00", "+01:00").',
		routing: {
			send: {
				type: 'body',
				property: 'timezone',
				value: '={{ $value !== "" && !isNaN(Number($value)) ? Number($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['generateBodygraph'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['generateBodygraph'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Latitude',
				name: 'latitude',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: -90,
					maxValue: 90,
					numberPrecision: 6,
				},
				description:
					'Birth latitude in decimal degrees. Optional and does not affect the bodygraph, which depends only on ecliptic longitudes.',
				routing: {
					send: {
						type: 'body',
						property: 'latitude',
					},
				},
			},
			{
				displayName: 'Longitude',
				name: 'longitude',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: -180,
					maxValue: 180,
					numberPrecision: 6,
				},
				description:
					'Birth longitude in decimal degrees. Optional and does not affect the bodygraph.',
				routing: {
					send: {
						type: 'body',
						property: 'longitude',
					},
				},
			},
			{
				displayName: 'Node Type',
				name: 'nodeType',
				type: 'options',
				options: [
					{
						name: 'Mean',
						value: 'mean',
					},
					{
						name: 'True',
						value: 'true',
					},
				],
				default: 'true',
				description:
					'Lunar node convention. "mean" is the smoothed average node, which always moves retrograde; "true" is the osculating node, which tracks the real perturbed node, oscillates up to about 1.5 degrees either side of the mean on a 173-day cycle, and can briefly turn direct.',
				routing: {
					send: {
						type: 'body',
						property: 'nodeType',
					},
				},
			},
		],
	},
	{
		displayName: 'Birth Data',
		name: 'birthData',
		type: 'json',
		default:
			'{\n  "date": "1990-07-15",\n  "time": "13:00:00",\n  "timezone": "America/New_York",\n  "latitude": 0,\n  "longitude": 0,\n  "nodeType": "true"\n}',
		required: true,
		description: 'Birth moment whose natal bodygraph the transit is overlaid on',
		routing: {
			send: {
				type: 'body',
				property: 'birthData',
				value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['generateTransit'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['generateTransit'],
			},
		},
		options: [
			{
				displayName: 'Date',
				name: 'date',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-05-23',
				description: 'Transit date in YYYY-MM-DD UTC. Optional.',
				routing: {
					send: {
						type: 'body',
						property: 'date',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Time',
				name: 'time',
				type: 'string',
				default: '',
				placeholder: 'e.g. 12:00:00',
				description: 'Transit time in HH:MM:SS UTC. Optional.',
				routing: {
					send: {
						type: 'body',
						property: 'time',
					},
				},
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'options',
		options: [
			{
				name: 'Ajna',
				value: 'ajna',
			},
			{
				name: 'G',
				value: 'g',
			},
			{
				name: 'Head',
				value: 'head',
			},
			{
				name: 'Heart',
				value: 'heart',
			},
			{
				name: 'Root',
				value: 'root',
			},
			{
				name: 'Sacral',
				value: 'sacral',
			},
			{
				name: 'Solar Plexus',
				value: 'solar-plexus',
			},
			{
				name: 'Spleen',
				value: 'spleen',
			},
			{
				name: 'Throat',
				value: 'throat',
			},
		],
		default: 'sacral',
		required: true,
		description:
			'Center ID. One of head, ajna, throat, g, heart, sacral, solar-plexus, spleen, root.',
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['getCenter'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['getCenter'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Number',
		name: 'number',
		type: 'number',
		default: 34,
		typeOptions: {
			minValue: 1,
			maxValue: 64,
		},
		required: true,
		description: 'Gate number from 1 to 64',
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['getGate'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['humanDesign'],
				operation: ['getGate'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
];
