// Generated by scripts/generate.mts from specs/openapi.json. Do not edit.
import type { INodeProperties } from 'n8n-workflow';

export const kabbalahDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['kabbalah'],
			},
		},
		options: [
			{
				name: 'Calculate Gematria',
				value: 'calculateGematria',
				action: 'Calculate gematria',
				description: 'Calculate gematria: Hebrew gematria calculator API with every spelling shown',
				routing: {
					request: {
						method: 'POST',
						url: '/kabbalah/gematria',
					},
				},
			},
			{
				name: 'Calculate Name Compatibility',
				value: 'calculateNameCompatibility',
				action: 'Calculate name compatibility',
				description:
					'Compare two names: gematria name compatibility API with every component published',
				routing: {
					request: {
						method: 'POST',
						url: '/kabbalah/compatibility',
					},
				},
			},
			{
				name: 'Generate Birth Profile',
				value: 'generateBirthProfile',
				action: 'Generate birth profile',
				description: 'Generate a birth profile: Hebrew birthday and birth angel API',
				routing: {
					request: {
						method: 'POST',
						url: '/kabbalah/birth-profile',
					},
				},
			},
			{
				name: 'Generate Name Profile',
				value: 'generateNameProfile',
				action: 'Generate name profile',
				description:
					'Generate a name profile: Kabbalah name numerology API with the spelling shown',
				routing: {
					request: {
						method: 'POST',
						url: '/kabbalah/name-profile',
					},
				},
			},
			{
				name: 'Get Daily Sephirah',
				value: 'getDailySephirah',
				action: 'Get daily sephirah',
				description: 'Get the sephirah of the day: Omer count API with the sephirot pairing',
				routing: {
					request: {
						method: 'GET',
						url: '/kabbalah/daily',
					},
				},
			},
			{
				name: 'Get Hebrew Letter',
				value: 'getHebrewLetter',
				action: 'Get hebrew letter',
				description: 'Get one Hebrew letter: Hebrew letter meaning API',
				routing: {
					request: {
						method: 'GET',
						url: '=/kabbalah/letters/{{encodeURIComponent($parameter["id"])}}',
					},
				},
			},
			{
				name: 'Get Sephirah',
				value: 'getSephirah',
				action: 'Get sephirah',
				description: 'Get one sephirah: sefirot meaning API with the paths that touch it',
				routing: {
					request: {
						method: 'GET',
						url: '=/kabbalah/sephirot/{{encodeURIComponent($parameter["id"])}}',
					},
				},
			},
			{
				name: 'Get Shem Name',
				value: 'getShemName',
				action: 'Get shem name',
				description: 'Get one of the 72 names: 72 names of God API by index',
				routing: {
					request: {
						method: 'GET',
						url: '=/kabbalah/names/{{encodeURIComponent($parameter["number"])}}',
					},
				},
			},
			{
				name: 'Get Tree of Life',
				value: 'getTreeOfLife',
				action: 'Get tree of life',
				description: 'Get the Tree of Life: sephirot and 22 paths API with typed school variants',
				routing: {
					request: {
						method: 'GET',
						url: '/kabbalah/tree',
					},
				},
			},
			{
				name: 'List Gematria Ciphers',
				value: 'listGematriaCiphers',
				action: 'List gematria ciphers',
				description: 'List gematria ciphers: gematria methods API with provenance on every row',
				routing: {
					request: {
						method: 'GET',
						url: '/kabbalah/ciphers',
					},
				},
			},
			{
				name: 'List Hebrew Letters',
				value: 'listHebrewLetters',
				action: 'List hebrew letters',
				description:
					'List the Hebrew letters: Hebrew alphabet API with the Sefer Yetzirah attributions',
				routing: {
					request: {
						method: 'GET',
						url: '/kabbalah/letters',
					},
				},
			},
			{
				name: 'List Shem Names',
				value: 'listShemNames',
				action: 'List shem names',
				description: 'List the 72 names: Shem HaMephorash API derived from the verses',
				routing: {
					request: {
						method: 'GET',
						url: '/kabbalah/names',
					},
				},
			},
		],
		default: 'calculateGematria',
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['kabbalah'],
				operation: ['calculateGematria'],
			},
		},
		options: [
			{
				displayName: 'Atbash Output',
				name: 'atbashOutput',
				type: 'options',
				options: [
					{
						name: 'Both',
						value: 'both',
					},
					{
						name: 'String',
						value: 'string',
					},
					{
						name: 'Value',
						value: 'value',
					},
				],
				default: 'both',
				description:
					'What AtBash and Albam return: the substituted Hebrew string, its standard value, or both. The biblical witness for AtBash is a substituted WORD rather than a number, which is why the string is available on its own.',
				routing: {
					send: {
						type: 'body',
						property: 'atbashOutput',
					},
				},
			},
			{
				displayName: 'Ciphers',
				name: 'ciphers',
				type: 'multiOptions',
				options: [
					{
						name: 'Kolel',
						value: 'kolel',
					},
					{
						name: 'Mispar Gadol',
						value: 'mispar-gadol',
					},
					{
						name: 'Mispar Ha Merubah Ha Klali',
						value: 'mispar-ha-merubah-ha-klali',
					},
					{
						name: 'Mispar Hechrachi',
						value: 'mispar-hechrachi',
					},
					{
						name: 'Mispar Katan',
						value: 'mispar-katan',
					},
					{
						name: 'Mispar Kidmi',
						value: 'mispar-kidmi',
					},
					{
						name: 'Mispar Meshulash',
						value: 'mispar-meshulash',
					},
					{
						name: 'Mispar Musafi',
						value: 'mispar-musafi',
					},
					{
						name: 'Mispar Prati',
						value: 'mispar-prati',
					},
					{
						name: 'Otiyot Be Milui',
						value: 'otiyot-be-milui',
					},
				],
				default: ['mispar-hechrachi', 'mispar-gadol'],
				description: 'Which ciphers to return, by identifier. Omit for every computed cipher.',
				routing: {
					send: {
						type: 'body',
						property: 'ciphers',
					},
				},
			},
			{
				displayName: 'Include Matches',
				name: 'includeMatches',
				type: 'boolean',
				default: true,
				description:
					'Whether to return the curated equal value entries for the chosen spelling. Set false to skip the lookup when only the numbers are wanted.',
				routing: {
					send: {
						type: 'body',
						property: 'includeMatches',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Latin Ciphers',
				name: 'latinCiphers',
				type: 'boolean',
				default: false,
				description:
					'Whether to also score the Latin text with the three Latin alphabet ciphers. They are Renaissance Christian and modern in lineage rather than rabbinic, and the response labels each one.',
				routing: {
					send: {
						type: 'body',
						property: 'latinCiphers',
					},
				},
			},
			{
				displayName: 'Mispar Gadol',
				name: 'misparGadol',
				type: 'options',
				options: [
					{
						name: 'Finals 500 900',
						value: 'finals-500-900',
					},
					{
						name: 'Milui',
						value: 'milui',
					},
				],
				default: 'finals-500-900',
				description:
					'Which method the name mispar gadol means, because the sources use it for two. Use finals-500-900 to score the five word final letters as 500 to 900, or milui to score each letter as the value of its own spelled out name.',
				routing: {
					send: {
						type: 'body',
						property: 'misparGadol',
					},
				},
			},
			{
				displayName: 'Text',
				name: 'text',
				type: 'string',
				default: '',
				placeholder: 'e.g. Sarah',
				description:
					'Latin text to write in Hebrew and then score, up to 200 characters. Non Latin scripts are folded to Latin first, so a Cyrillic or Devanagari name works.',
				routing: {
					send: {
						type: 'body',
						property: 'text',
					},
				},
			},
			{
				displayName: 'Text Hebrew',
				name: 'textHebrew',
				type: 'string',
				default: '',
				description:
					'Hebrew text to score, up to 200 characters. Anything outside the Hebrew script is rejected.',
				routing: {
					send: {
						type: 'body',
						property: 'textHebrew',
					},
				},
			},
			{
				displayName: 'Transliteration',
				name: 'transliteration',
				type: 'options',
				options: [
					{
						name: 'Letter Map Mathers',
						value: 'letter-map-mathers',
					},
					{
						name: 'Letter Map Modern',
						value: 'letter-map-modern',
					},
				],
				default: 'letter-map-mathers',
				description:
					'How a Latin name is written in Hebrew before it is scored. Two members. letter-map-mathers is the 1887 Hermetic letter map, with e read as its author practised it: a point inside a word and alef at the start of one.',
				routing: {
					send: {
						type: 'body',
						property: 'transliteration',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['kabbalah'],
				operation: ['calculateNameCompatibility'],
			},
		},
		options: [
			{
				displayName: 'First Name',
				name: 'firstName',
				type: 'string',
				default: '',
				placeholder: 'e.g. Sarah',
				description:
					'First name in Latin script. Send firstNameHebrew instead to control the spelling.',
				routing: {
					send: {
						type: 'body',
						property: 'firstName',
					},
				},
			},
			{
				displayName: 'First Name Hebrew',
				name: 'firstNameHebrew',
				type: 'string',
				default: '',
				description: 'First name already in Hebrew, which skips the transliteration step',
				routing: {
					send: {
						type: 'body',
						property: 'firstNameHebrew',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Mispar Gadol',
				name: 'misparGadol',
				type: 'options',
				options: [
					{
						name: 'Finals 500 900',
						value: 'finals-500-900',
					},
					{
						name: 'Milui',
						value: 'milui',
					},
				],
				default: 'finals-500-900',
				description:
					'Which method the name mispar gadol means, because the sources use it for two. Use finals-500-900 to score the five word final letters as 500 to 900, or milui to score each letter as the value of its own spelled out name.',
				routing: {
					send: {
						type: 'body',
						property: 'misparGadol',
					},
				},
			},
			{
				displayName: 'Second Name',
				name: 'secondName',
				type: 'string',
				default: '',
				placeholder: 'e.g. David',
				description:
					'Second name in Latin script. Send secondNameHebrew instead to control the spelling.',
				routing: {
					send: {
						type: 'body',
						property: 'secondName',
					},
				},
			},
			{
				displayName: 'Second Name Hebrew',
				name: 'secondNameHebrew',
				type: 'string',
				default: '',
				description: 'Second name already in Hebrew, which skips the transliteration step',
				routing: {
					send: {
						type: 'body',
						property: 'secondNameHebrew',
					},
				},
			},
			{
				displayName: 'Transliteration',
				name: 'transliteration',
				type: 'options',
				options: [
					{
						name: 'Letter Map Mathers',
						value: 'letter-map-mathers',
					},
					{
						name: 'Letter Map Modern',
						value: 'letter-map-modern',
					},
				],
				default: 'letter-map-mathers',
				description:
					'How a Latin name is written in Hebrew before it is scored. Two members. letter-map-mathers is the 1887 Hermetic letter map, with e read as its author practised it: a point inside a word and alef at the start of one.',
				routing: {
					send: {
						type: 'body',
						property: 'transliteration',
					},
				},
			},
		],
	},
	{
		displayName: 'Date',
		name: 'date',
		type: 'string',
		default: '',
		placeholder: 'e.g. 1990-06-15',
		required: true,
		description:
			'Birth date in YYYY-MM-DD, proleptic Gregorian. Dates before the 1582 reform are read on the same proleptic reckoning rather than switched to the Julian calendar.',
		routing: {
			send: {
				type: 'body',
				property: 'date',
			},
		},
		displayOptions: {
			show: {
				resource: ['kabbalah'],
				operation: ['generateBirthProfile'],
			},
		},
	},
	{
		displayName: 'Timezone',
		name: 'timezone',
		type: 'string',
		default: '',
		placeholder: 'e.g. America/New_York or -5',
		required: true,
		description:
			'IANA name (e.g. "America/New_York", "Europe/London", "UTC"), decimal hours (e.g. -5 for EST, 1 for CET), or a fixed UTC offset (e.g. "-05:00", "+01:00").',
		routing: {
			send: {
				type: 'body',
				property: 'timezone',
				value: '={{ $value !== "" && !isNaN(Number($value)) ? Number($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['kabbalah'],
				operation: ['generateBirthProfile'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['kabbalah'],
				operation: ['generateBirthProfile'],
			},
		},
		options: [
			{
				displayName: 'After Sunset',
				name: 'afterSunset',
				type: 'boolean',
				default: false,
				description:
					'Whether the moment falls after nightfall, which advances the Hebrew date by one day because the Hebrew day begins in the evening. It is a caller assertion rather than a computation, since sunset depends on a place and this conversion takes none.',
				routing: {
					send: {
						type: 'body',
						property: 'afterSunset',
					},
				},
			},
			{
				displayName: 'Angel Dating',
				name: 'angelDating',
				type: 'options',
				options: [
					{
						name: 'Lenain Blocks',
						value: 'lenain-blocks',
					},
					{
						name: 'Solar Longitude',
						value: 'solar-longitude',
					},
				],
				default: 'solar-longitude',
				description:
					'How the name of the day is found. Use solar-longitude for the exact five degree arc the Sun stood in at the birth moment, or lenain-blocks for the fixed civil calendar of five day periods.',
				routing: {
					send: {
						type: 'body',
						property: 'angelDating',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Leap Day Policy',
				name: 'leapDayPolicy',
				type: 'options',
				options: [
					{
						name: 'Extend Previous',
						value: 'extend-previous',
					},
					{
						name: 'Next Angel',
						value: 'next-angel',
					},
				],
				default: 'extend-previous',
				description:
					'Where 29 February falls. The civil wheel was built for a 365 day year and has no slot for it, so published tables differ: extend-previous reads the day as part of the period ending 28 February, next-angel reads it as the opening of the period starting 1 March.',
				routing: {
					send: {
						type: 'body',
						property: 'leapDayPolicy',
					},
				},
			},
			{
				displayName: 'Time',
				name: 'time',
				type: 'string',
				default: '',
				placeholder: 'e.g. 14:30:00',
				description:
					'Birth time in HH:MM:SS local to the timezone field. Defaults to noon when omitted, which is stated because the name read from the hour changes every twenty minutes and a defaulted time cannot be precise.',
				routing: {
					send: {
						type: 'body',
						property: 'time',
					},
				},
			},
			{
				displayName: 'Year Start',
				name: 'yearStart',
				type: 'options',
				options: [
					{
						name: 'March 20',
						value: 'march-20',
					},
					{
						name: 'March 21',
						value: 'march-21',
					},
				],
				default: 'march-21',
				description:
					'Which date the civil wheel of five day periods opens on. Both are conventions rather than facts: the equinox itself moves inside a window that covers both days, and it fell on 20 March in 2026. march-21 is the pinned published wheel and march-20 is that wheel shifted one day.',
				routing: {
					send: {
						type: 'body',
						property: 'yearStart',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['kabbalah'],
				operation: ['generateNameProfile'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Mispar Gadol',
				name: 'misparGadol',
				type: 'options',
				options: [
					{
						name: 'Finals 500 900',
						value: 'finals-500-900',
					},
					{
						name: 'Milui',
						value: 'milui',
					},
				],
				default: 'finals-500-900',
				description:
					'Which method the name mispar gadol means, because the sources use it for two. Use finals-500-900 to score the five word final letters as 500 to 900, or milui to score each letter as the value of its own spelled out name.',
				routing: {
					send: {
						type: 'body',
						property: 'misparGadol',
					},
				},
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				placeholder: 'e.g. Sarah',
				description:
					'The name in Latin script, to be written in Hebrew and then scored. Non Latin scripts are folded to Latin first.',
				routing: {
					send: {
						type: 'body',
						property: 'name',
					},
				},
			},
			{
				displayName: 'Name Hebrew',
				name: 'nameHebrew',
				type: 'string',
				default: '',
				description:
					'The name already in Hebrew, which skips the transliteration step entirely and scores exactly the spelling you sent',
				routing: {
					send: {
						type: 'body',
						property: 'nameHebrew',
					},
				},
			},
			{
				displayName: 'Transliteration',
				name: 'transliteration',
				type: 'options',
				options: [
					{
						name: 'Letter Map Mathers',
						value: 'letter-map-mathers',
					},
					{
						name: 'Letter Map Modern',
						value: 'letter-map-modern',
					},
				],
				default: 'letter-map-mathers',
				description:
					'How a Latin name is written in Hebrew before it is scored. Two members. letter-map-mathers is the 1887 Hermetic letter map, with e read as its author practised it: a point inside a word and alef at the start of one.',
				routing: {
					send: {
						type: 'body',
						property: 'transliteration',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['kabbalah'],
				operation: ['getDailySephirah'],
			},
		},
		options: [
			{
				displayName: 'After Sunset',
				name: 'afterSunset',
				type: 'string',
				default: '',
				placeholder: 'e.g. false',
				description:
					'Set true when the moment falls after nightfall, which advances the Hebrew date by one day because the Hebrew day begins in the evening. It is a caller assertion rather than a computation, since sunset depends on a place and this route takes none.',
				routing: {
					send: {
						type: 'query',
						property: 'afterSunset',
					},
				},
			},
			{
				displayName: 'Date',
				name: 'date',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-04-04',
				description:
					'Date in YYYY-MM-DD. Defaults to the current UTC date when omitted, so a caller that wants a fixed answer should send one.',
				routing: {
					send: {
						type: 'query',
						property: 'date',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Timezone',
				name: 'timezone',
				type: 'string',
				default: '',
				placeholder: 'e.g. Asia/Jerusalem',
				description:
					'IANA name or decimal offset, used only to decide which calendar date it is where the caller is when date is omitted. It does not move the count, which is a calendar count rather than a clock one.',
				routing: {
					send: {
						type: 'query',
						property: 'timezone',
					},
				},
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'options',
		options: [
			{
				name: 'Alef',
				value: 'alef',
			},
			{
				name: 'Ayin',
				value: 'ayin',
			},
			{
				name: 'Bet',
				value: 'bet',
			},
			{
				name: 'Chet',
				value: 'chet',
			},
			{
				name: 'Dalet',
				value: 'dalet',
			},
			{
				name: 'Gimel',
				value: 'gimel',
			},
			{
				name: 'He',
				value: 'he',
			},
			{
				name: 'Kaf',
				value: 'kaf',
			},
			{
				name: 'Lamed',
				value: 'lamed',
			},
			{
				name: 'Mem',
				value: 'mem',
			},
			{
				name: 'Nun',
				value: 'nun',
			},
			{
				name: 'Pe',
				value: 'pe',
			},
			{
				name: 'Qof',
				value: 'qof',
			},
			{
				name: 'Resh',
				value: 'resh',
			},
			{
				name: 'Samekh',
				value: 'samekh',
			},
			{
				name: 'Shin',
				value: 'shin',
			},
			{
				name: 'Tav',
				value: 'tav',
			},
			{
				name: 'Tet',
				value: 'tet',
			},
			{
				name: 'Tzadi',
				value: 'tzadi',
			},
			{
				name: 'Vav',
				value: 'vav',
			},
			{
				name: 'Yod',
				value: 'yod',
			},
			{
				name: 'Zayin',
				value: 'zayin',
			},
		],
		default: 'shin',
		required: true,
		description:
			'Letter identifier, one of alef, bet, gimel, dalet, he, vav, zayin, chet, tet, yod, kaf, lamed, mem, nun, samekh, ayin, pe, tzadi, qof, resh, shin, tav. Matching folds case and punctuation.',
		displayOptions: {
			show: {
				resource: ['kabbalah'],
				operation: ['getHebrewLetter'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['kabbalah'],
				operation: ['getHebrewLetter'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Letter Attribution',
				name: 'letterAttribution',
				type: 'options',
				options: [
					{
						name: 'Golden Dawn',
						value: 'golden-dawn',
					},
					{
						name: 'Sefer Yetzirah Gra',
						value: 'sefer-yetzirah-gra',
					},
					{
						name: 'Sefer Yetzirah Saadia',
						value: 'sefer-yetzirah-saadia',
					},
					{
						name: 'Sefer Yetzirah Short',
						value: 'sefer-yetzirah-short',
					},
				],
				default: 'sefer-yetzirah-gra',
				description:
					'Which reading assigns the element, planet or sign to each letter. The seven double letters are the contested column and the four readings genuinely disagree on them; the twelve simple letters run in natural zodiacal order in all four.',
				routing: {
					send: {
						type: 'query',
						property: 'letterAttribution',
					},
				},
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'options',
		options: [
			{
				name: 'Binah',
				value: 'binah',
			},
			{
				name: 'Chesed',
				value: 'chesed',
			},
			{
				name: 'Chokhmah',
				value: 'chokhmah',
			},
			{
				name: 'Daat',
				value: 'daat',
			},
			{
				name: 'Gevurah',
				value: 'gevurah',
			},
			{
				name: 'Hod',
				value: 'hod',
			},
			{
				name: 'Keter',
				value: 'keter',
			},
			{
				name: 'Malkuth',
				value: 'malkuth',
			},
			{
				name: 'Netzach',
				value: 'netzach',
			},
			{
				name: 'Tiferet',
				value: 'tiferet',
			},
			{
				name: 'Yesod',
				value: 'yesod',
			},
		],
		default: 'tiferet',
		required: true,
		description:
			'Sephirah identifier, one of keter, chokhmah, binah, chesed, gevurah, tiferet, netzach, hod, yesod, malkuth, daat. Matching folds case and punctuation.',
		displayOptions: {
			show: {
				resource: ['kabbalah'],
				operation: ['getSephirah'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['kabbalah'],
				operation: ['getSephirah'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Letter Attribution',
				name: 'letterAttribution',
				type: 'options',
				options: [
					{
						name: 'Golden Dawn',
						value: 'golden-dawn',
					},
					{
						name: 'Sefer Yetzirah Gra',
						value: 'sefer-yetzirah-gra',
					},
					{
						name: 'Sefer Yetzirah Saadia',
						value: 'sefer-yetzirah-saadia',
					},
					{
						name: 'Sefer Yetzirah Short',
						value: 'sefer-yetzirah-short',
					},
				],
				default: 'sefer-yetzirah-gra',
				description:
					'Which reading assigns the element, planet or sign to each letter. The seven double letters are the contested column and the four readings genuinely disagree on them; the twelve simple letters run in natural zodiacal order in all four.',
				routing: {
					send: {
						type: 'query',
						property: 'letterAttribution',
					},
				},
			},
			{
				displayName: 'Sephirot System',
				name: 'sephirotSystem',
				type: 'options',
				options: [
					{
						name: 'Classical',
						value: 'classical',
					},
					{
						name: 'Golden Dawn',
						value: 'golden-dawn',
					},
				],
				default: 'classical',
				description:
					'Which reading assigns a sphere to each sephirah. The two were compared row by row and agree on all ten, so the answer is the same either way; the parameter exists so a caller knows which one produced it rather than assuming.',
				routing: {
					send: {
						type: 'query',
						property: 'sephirotSystem',
					},
				},
			},
		],
	},
	{
		displayName: 'Number',
		name: 'number',
		type: 'number',
		default: 27,
		typeOptions: {
			minValue: 1,
			maxValue: 72,
		},
		required: true,
		description: 'Index of the name, 1 to 72',
		displayOptions: {
			show: {
				resource: ['kabbalah'],
				operation: ['getShemName'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['kabbalah'],
				operation: ['getShemName'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['kabbalah'],
				operation: ['getTreeOfLife'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Letter Attribution',
				name: 'letterAttribution',
				type: 'options',
				options: [
					{
						name: 'Golden Dawn',
						value: 'golden-dawn',
					},
					{
						name: 'Sefer Yetzirah Gra',
						value: 'sefer-yetzirah-gra',
					},
					{
						name: 'Sefer Yetzirah Saadia',
						value: 'sefer-yetzirah-saadia',
					},
					{
						name: 'Sefer Yetzirah Short',
						value: 'sefer-yetzirah-short',
					},
				],
				default: 'sefer-yetzirah-gra',
				description:
					'Which reading assigns the element, planet or sign to each letter. The seven double letters are the contested column and the four readings genuinely disagree on them; the twelve simple letters run in natural zodiacal order in all four.',
				routing: {
					send: {
						type: 'query',
						property: 'letterAttribution',
					},
				},
			},
			{
				displayName: 'Sephirot System',
				name: 'sephirotSystem',
				type: 'options',
				options: [
					{
						name: 'Classical',
						value: 'classical',
					},
					{
						name: 'Golden Dawn',
						value: 'golden-dawn',
					},
				],
				default: 'classical',
				description:
					'Which reading assigns a sphere to each sephirah. The two were compared row by row and agree on all ten, so the answer is the same either way; the parameter exists so a caller knows which one produced it rather than assuming.',
				routing: {
					send: {
						type: 'query',
						property: 'sephirotSystem',
					},
				},
			},
			{
				displayName: 'Tree Variant',
				name: 'treeVariant',
				type: 'options',
				options: [
					{
						name: 'Kircher',
						value: 'kircher',
					},
				],
				default: 'kircher',
				description:
					'Which arrangement of the twenty two paths. The 1652 arrangement, in which Malkuth carries three paths, is the only one with a published table that letters every path, so it is the only member.',
				routing: {
					send: {
						type: 'query',
						property: 'treeVariant',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['kabbalah'],
				operation: ['listGematriaCiphers'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['kabbalah'],
				operation: ['listHebrewLetters'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Letter Attribution',
				name: 'letterAttribution',
				type: 'options',
				options: [
					{
						name: 'Golden Dawn',
						value: 'golden-dawn',
					},
					{
						name: 'Sefer Yetzirah Gra',
						value: 'sefer-yetzirah-gra',
					},
					{
						name: 'Sefer Yetzirah Saadia',
						value: 'sefer-yetzirah-saadia',
					},
					{
						name: 'Sefer Yetzirah Short',
						value: 'sefer-yetzirah-short',
					},
				],
				default: 'sefer-yetzirah-gra',
				description:
					'Which reading assigns the element, planet or sign to each letter. The seven double letters are the contested column and the four readings genuinely disagree on them; the twelve simple letters run in natural zodiacal order in all four.',
				routing: {
					send: {
						type: 'query',
						property: 'letterAttribution',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['kabbalah'],
				operation: ['listShemNames'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Limit',
				name: 'maxResults',
				type: 'number',
				default: 20,
				typeOptions: {
					minValue: 1,
					maxValue: 72,
				},
				description: 'Maximum items to return per page. Range: 1-72, default 20.',
				routing: {
					send: {
						type: 'query',
						property: 'limit',
					},
				},
			},
			{
				displayName: 'Longitude',
				name: 'longitude',
				type: 'number',
				default: 131.18,
				typeOptions: {
					minValue: 0,
					numberPrecision: 6,
				},
				description:
					'Ecliptic longitude in degrees, 0 inclusive to 360 exclusive, measured from 0 Aries. Returns the single name governing that degree instead of the list. 360 is rejected because it is the same point as 0 and the arcs are half open at the top.',
				routing: {
					send: {
						type: 'query',
						property: 'longitude',
					},
				},
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: 0,
				},
				description: 'Number of items to skip for pagination. Default 0.',
				routing: {
					send: {
						type: 'query',
						property: 'offset',
					},
				},
			},
		],
	},
];
