// Generated by scripts/generate.mts from specs/openapi.json. Do not edit.
import type { INodeProperties } from 'n8n-workflow';

export const locationDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['location'],
			},
		},
		options: [
			{
				name: 'Get Cities by Country',
				value: 'getCitiesByCountry',
				action: 'Get cities by country',
				description: 'Get cities in a country: Geocoding directory sorted by population',
				routing: {
					request: {
						method: 'GET',
						url: '=/location/countries/{{encodeURIComponent($parameter["iso2"])}}',
					},
				},
			},
			{
				name: 'List Countries',
				value: 'listCountries',
				action: 'List countries',
				description: 'List all countries: ISO codes and city coverage',
				routing: {
					request: {
						method: 'GET',
						url: '/location/countries',
					},
				},
			},
			{
				name: 'Search Cities',
				value: 'searchCities',
				action: 'Search cities',
				description:
					'Search cities worldwide: Geocoding autocomplete with coordinates and timezone',
				routing: {
					request: {
						method: 'GET',
						url: '/location/search',
					},
				},
			},
		],
		default: 'getCitiesByCountry',
	},
	{
		displayName: 'ISO2',
		name: 'iso2',
		type: 'string',
		default: '',
		placeholder: 'e.g. DE',
		required: true,
		description:
			'ISO 3166-1 alpha-2 country code, case-insensitive. Common codes: DE (Germany), FR (France), GB (United Kingdom), US (United States), ES (Spain), IT (Italy), NL (Netherlands), IN (India), BR (Brazil), JP (Japan).',
		displayOptions: {
			show: {
				resource: ['location'],
				operation: ['getCitiesByCountry'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['location'],
				operation: ['getCitiesByCountry'],
			},
		},
		options: [
			{
				displayName: 'Limit',
				name: 'maxResults',
				type: 'number',
				default: 20,
				typeOptions: {
					minValue: 1,
					maxValue: 100,
				},
				description: 'Maximum items to return per page. Range: 1-100, default 20.',
				routing: {
					send: {
						type: 'query',
						property: 'limit',
					},
				},
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: 0,
				},
				description: 'Number of items to skip for pagination. Default 0.',
				routing: {
					send: {
						type: 'query',
						property: 'offset',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['location'],
				operation: ['listCountries'],
			},
		},
		options: [
			{
				displayName: 'Limit',
				name: 'maxResults',
				type: 'number',
				default: 50,
				typeOptions: {
					minValue: 1,
					maxValue: 250,
				},
				description: 'Maximum items to return per page. Range: 1-250, default 50.',
				routing: {
					send: {
						type: 'query',
						property: 'limit',
					},
				},
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: 0,
				},
				description: 'Number of items to skip for pagination. Default 0.',
				routing: {
					send: {
						type: 'query',
						property: 'offset',
					},
				},
			},
		],
	},
	{
		displayName: 'Query',
		name: 'q',
		type: 'string',
		default: '',
		placeholder: 'e.g. berlin',
		required: true,
		description:
			'Place to search for, written the way a person would. Accepts a bare city (berlin), a city plus country (berlin germany), a comma-qualified place (richfield, utah), a fully qualified place (richfield, utah, united states), or a historic name (bombay, peking, constantinople).',
		routing: {
			send: {
				type: 'query',
				property: 'q',
			},
		},
		displayOptions: {
			show: {
				resource: ['location'],
				operation: ['searchCities'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['location'],
				operation: ['searchCities'],
			},
		},
		options: [
			{
				displayName: 'Limit',
				name: 'maxResults',
				type: 'number',
				default: 10,
				typeOptions: {
					minValue: 1,
					maxValue: 50,
				},
				description: 'Maximum items to return per page. Range: 1-50, default 10.',
				routing: {
					send: {
						type: 'query',
						property: 'limit',
					},
				},
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: 0,
				},
				description: 'Number of items to skip for pagination. Default 0.',
				routing: {
					send: {
						type: 'query',
						property: 'offset',
					},
				},
			},
		],
	},
];
