// Generated by scripts/generate.mts from specs/openapi.json. Do not edit.
import type { INodeProperties } from 'n8n-workflow';

export const mesoamericanAstrologyDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
			},
		},
		options: [
			{
				name: 'Calculate Mayan Compatibility',
				value: 'calculateMayanCompatibility',
				action: 'Calculate mayan compatibility',
				description: 'Mayan nawal compatibility: Tzolkin pair analysis API',
				routing: {
					request: {
						method: 'POST',
						url: '/mesoamerican-astrology/mayan/compatibility',
					},
				},
			},
			{
				name: 'Calculate Tonalpohualli',
				value: 'calculateTonalpohualli',
				action: 'Calculate tonalpohualli',
				description: 'Aztec day sign for a date: Tonalpohualli calculator API',
				routing: {
					request: {
						method: 'POST',
						url: '/mesoamerican-astrology/aztec/tonalpohualli',
					},
				},
			},
			{
				name: 'Calculate Tzolkin',
				value: 'calculateTzolkin',
				action: 'Calculate tzolkin',
				description: 'Mayan day sign for a date: Tzolkin calculator API',
				routing: {
					request: {
						method: 'POST',
						url: '/mesoamerican-astrology/mayan/tzolkin',
					},
				},
			},
			{
				name: 'Convert Long Count',
				value: 'convertLongCount',
				action: 'Convert long count',
				description: 'Convert a Maya Long Count: Long Count calendar converter API',
				routing: {
					request: {
						method: 'POST',
						url: '/mesoamerican-astrology/mayan/long-count/convert',
					},
				},
			},
			{
				name: 'Generate Mayan Chart',
				value: 'generateMayanChart',
				action: 'Generate mayan chart',
				description: 'Generate a Mayan chart: Tzolkin, Haab and Long Count calculator API',
				routing: {
					request: {
						method: 'POST',
						url: '/mesoamerican-astrology/mayan/chart',
					},
				},
			},
			{
				name: 'Get Aztec Day Sign',
				value: 'getAztecDaySign',
				action: 'Get aztec day sign',
				description: 'Get one Aztec day sign: Tonalpohualli sign profile API',
				routing: {
					request: {
						method: 'GET',
						url: '=/mesoamerican-astrology/aztec/day-signs/{{encodeURIComponent($parameter["id"])}}',
					},
				},
			},
			{
				name: 'Get Aztec Trecena',
				value: 'getAztecTrecena',
				action: 'Get aztec trecena',
				description: 'Get one Aztec trecena: Tonalpohualli period profile API',
				routing: {
					request: {
						method: 'GET',
						url: '=/mesoamerican-astrology/aztec/trecenas/{{encodeURIComponent($parameter["number"])}}',
					},
				},
			},
			{
				name: 'Get Daily Aztec Reading',
				value: 'getDailyAztecReading',
				action: 'Get daily aztec reading',
				description: 'Daily Aztec energy reading: Tonalpohualli day sign of the day API',
				routing: {
					request: {
						method: 'GET',
						url: '/mesoamerican-astrology/aztec/daily',
					},
				},
			},
			{
				name: 'Get Daily Mayan Reading',
				value: 'getDailyMayanReading',
				action: 'Get daily mayan reading',
				description: 'Daily Mayan energy reading: Tzolkin day sign of the day API',
				routing: {
					request: {
						method: 'GET',
						url: '/mesoamerican-astrology/mayan/daily',
					},
				},
			},
			{
				name: 'Get Haab Month',
				value: 'getHaabMonth',
				action: 'Get haab month',
				description: 'Get one Haab period: Maya solar calendar month profile API',
				routing: {
					request: {
						method: 'GET',
						url: '=/mesoamerican-astrology/mayan/haab-months/{{encodeURIComponent($parameter["id"])}}',
					},
				},
			},
			{
				name: 'Get Mayan Day Sign',
				value: 'getMayanDaySign',
				action: 'Get mayan day sign',
				description: 'Get one Mayan day sign: Nawal profile API',
				routing: {
					request: {
						method: 'GET',
						url: '=/mesoamerican-astrology/mayan/day-signs/{{encodeURIComponent($parameter["id"])}}',
					},
				},
			},
			{
				name: 'Get Monthly Tzolkin Calendar',
				value: 'getMonthlyTzolkinCalendar',
				action: 'Get monthly tzolkin calendar',
				description: 'Monthly Tzolkin calendar grid: Maya calendar month API',
				routing: {
					request: {
						method: 'GET',
						url: '/mesoamerican-astrology/mayan/calendar/monthly',
					},
				},
			},
			{
				name: 'Get Trecena',
				value: 'getTrecena',
				action: 'Get trecena',
				description: 'Get one Mayan trecena: Thirteen day period profile API',
				routing: {
					request: {
						method: 'GET',
						url: '=/mesoamerican-astrology/mayan/trecenas/{{encodeURIComponent($parameter["number"])}}',
					},
				},
			},
			{
				name: 'List Aztec Day Signs',
				value: 'listAztecDaySigns',
				action: 'List aztec day signs',
				description: 'List the 20 Aztec day signs: Tonalpohualli sign catalogue API',
				routing: {
					request: {
						method: 'GET',
						url: '/mesoamerican-astrology/aztec/day-signs',
					},
				},
			},
			{
				name: 'List Aztec Trecenas',
				value: 'listAztecTrecenas',
				action: 'List aztec trecenas',
				description: 'List the 20 Aztec trecenas: Tonalpohualli thirteen day period API',
				routing: {
					request: {
						method: 'GET',
						url: '/mesoamerican-astrology/aztec/trecenas',
					},
				},
			},
			{
				name: 'List Haab Months',
				value: 'listHaabMonths',
				action: 'List haab months',
				description: 'List the 19 Haab periods: Maya solar calendar month API',
				routing: {
					request: {
						method: 'GET',
						url: '/mesoamerican-astrology/mayan/haab-months',
					},
				},
			},
			{
				name: 'List Mayan Day Signs',
				value: 'listMayanDaySigns',
				action: 'List mayan day signs',
				description: 'List the 20 Mayan day signs: Tzolkin nawal catalogue API',
				routing: {
					request: {
						method: 'GET',
						url: '/mesoamerican-astrology/mayan/day-signs',
					},
				},
			},
			{
				name: 'List Trecenas',
				value: 'listTrecenas',
				action: 'List trecenas',
				description: 'List the 20 Mayan trecenas: Tzolkin thirteen day period API',
				routing: {
					request: {
						method: 'GET',
						url: '/mesoamerican-astrology/mayan/trecenas',
					},
				},
			},
		],
		default: 'calculateMayanCompatibility',
	},
	{
		displayName: 'Person A',
		name: 'personA',
		type: 'json',
		default: '{\n  "date": "2012-12-21"\n}',
		required: true,
		description:
			'The first person, by birth date. Only a date is needed: the Tzolkin is a day count, so no time, timezone or place changes the answer.',
		routing: {
			send: {
				type: 'body',
				property: 'personA',
				value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
				operation: ['calculateMayanCompatibility'],
			},
		},
	},
	{
		displayName: 'Person B',
		name: 'personB',
		type: 'json',
		default: '{\n  "date": "2012-12-21"\n}',
		required: true,
		description:
			'The second person, by birth date. The comparison is symmetric except for the cross tie, which is checked in both directions.',
		routing: {
			send: {
				type: 'body',
				property: 'personB',
				value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
				operation: ['calculateMayanCompatibility'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
				operation: ['calculateMayanCompatibility'],
			},
		},
		options: [
			{
				displayName: 'Correlation',
				name: 'correlation',
				type: 'options',
				options: [
					{
						name: 'Astronomical 584285',
						value: 'astronomical-584285',
					},
					{
						name: 'Gmt 584283',
						value: 'gmt-584283',
					},
					{
						name: 'Martin Skidmore 584286',
						value: 'martin-skidmore-584286',
					},
					{
						name: 'Martinez Hernandez 584281',
						value: 'martinez-hernandez-584281',
					},
				],
				default: 'gmt-584283',
				description:
					'Which correlation constant ties the day count to a civil date. This is the single choice that shifts every value in the response, so it is a parameter rather than a hidden default, and the resolved value comes back under conventions. "gmt-584283" is the commonly accepted constant and the...',
				routing: {
					send: {
						type: 'body',
						property: 'correlation',
					},
				},
			},
			{
				displayName: 'Direction Scheme',
				name: 'directionScheme',
				type: 'options',
				options: [
					{
						name: 'Landa',
						value: 'landa',
					},
					{
						name: 'Madrid Codex',
						value: 'madrid-codex',
					},
				],
				default: 'madrid-codex',
				description:
					'Which reading of the world direction and colour to serve for a day sign. The two published assignments differ by exactly one quarter turn on all twenty signs, so neither is a rounding of the other and a silent pick would be a school choice. "madrid-codex" is the codex reading and the default;...',
				routing: {
					send: {
						type: 'body',
						property: 'directionScheme',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Date',
		name: 'date',
		type: 'string',
		default: '',
		placeholder: 'e.g. 2012-12-21',
		required: true,
		description:
			'Date in YYYY-MM-DD format, in the PROLEPTIC GREGORIAN calendar, extended backwards unchanged through the 1582 reform. Years 1 to 4000 are accepted.',
		routing: {
			send: {
				type: 'body',
				property: 'date',
			},
		},
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
				operation: ['calculateTonalpohualli'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
				operation: ['calculateTonalpohualli'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Date',
		name: 'date',
		type: 'string',
		default: '',
		placeholder: 'e.g. 2012-12-21',
		required: true,
		description:
			'Date in YYYY-MM-DD format, in the PROLEPTIC GREGORIAN calendar, extended backwards unchanged through the 1582 reform. Years 1 to 4000 are accepted.',
		routing: {
			send: {
				type: 'body',
				property: 'date',
			},
		},
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
				operation: ['calculateTzolkin'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
				operation: ['calculateTzolkin'],
			},
		},
		options: [
			{
				displayName: 'Correlation',
				name: 'correlation',
				type: 'options',
				options: [
					{
						name: 'Astronomical 584285',
						value: 'astronomical-584285',
					},
					{
						name: 'Gmt 584283',
						value: 'gmt-584283',
					},
					{
						name: 'Martin Skidmore 584286',
						value: 'martin-skidmore-584286',
					},
					{
						name: 'Martinez Hernandez 584281',
						value: 'martinez-hernandez-584281',
					},
				],
				default: 'gmt-584283',
				description:
					'Which correlation constant ties the day count to a civil date. This is the single choice that shifts every value in the response, so it is a parameter rather than a hidden default, and the resolved value comes back under conventions. "gmt-584283" is the commonly accepted constant and the...',
				routing: {
					send: {
						type: 'body',
						property: 'correlation',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
				operation: ['convertLongCount'],
			},
		},
		options: [
			{
				displayName: 'Correlation',
				name: 'correlation',
				type: 'options',
				options: [
					{
						name: 'Astronomical 584285',
						value: 'astronomical-584285',
					},
					{
						name: 'Gmt 584283',
						value: 'gmt-584283',
					},
					{
						name: 'Martin Skidmore 584286',
						value: 'martin-skidmore-584286',
					},
					{
						name: 'Martinez Hernandez 584281',
						value: 'martinez-hernandez-584281',
					},
				],
				default: 'gmt-584283',
				description:
					'Which correlation constant ties the day count to a civil date. This is the single choice that shifts every value in the response, so it is a parameter rather than a hidden default, and the resolved value comes back under conventions. "gmt-584283" is the commonly accepted constant and the...',
				routing: {
					send: {
						type: 'body',
						property: 'correlation',
					},
				},
			},
			{
				displayName: 'Date',
				name: 'date',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2012-12-21',
				description:
					'Proleptic Gregorian date to convert INTO a Long Count. Supply this or longCount, never both and never neither.',
				routing: {
					send: {
						type: 'body',
						property: 'date',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Long Count',
				name: 'longCount',
				type: 'string',
				default: '',
				placeholder: 'e.g. 13.0.0.0.0',
				description:
					'Dotted Long Count to convert INTO a date, written baktun.katun.tun.winal.kin. Each position is bounded by its own base, and the winal counts to 17 rather than to 19 because eighteen winal make a tun, so 9.12.11.18.0 is rejected as a date that does not exist.',
				routing: {
					send: {
						type: 'body',
						property: 'longCount',
					},
				},
			},
		],
	},
	{
		displayName: 'Date',
		name: 'date',
		type: 'string',
		default: '',
		placeholder: 'e.g. 2012-12-21',
		required: true,
		description:
			'Date in YYYY-MM-DD format, in the PROLEPTIC GREGORIAN calendar, extended backwards unchanged through the 1582 reform. Years 1 to 4000 are accepted.',
		routing: {
			send: {
				type: 'body',
				property: 'date',
			},
		},
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
				operation: ['generateMayanChart'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
				operation: ['generateMayanChart'],
			},
		},
		options: [
			{
				displayName: 'Correlation',
				name: 'correlation',
				type: 'options',
				options: [
					{
						name: 'Astronomical 584285',
						value: 'astronomical-584285',
					},
					{
						name: 'Gmt 584283',
						value: 'gmt-584283',
					},
					{
						name: 'Martin Skidmore 584286',
						value: 'martin-skidmore-584286',
					},
					{
						name: 'Martinez Hernandez 584281',
						value: 'martinez-hernandez-584281',
					},
				],
				default: 'gmt-584283',
				description:
					'Which correlation constant ties the day count to a civil date. This is the single choice that shifts every value in the response, so it is a parameter rather than a hidden default, and the resolved value comes back under conventions. "gmt-584283" is the commonly accepted constant and the...',
				routing: {
					send: {
						type: 'body',
						property: 'correlation',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Year Bearer System',
				name: 'yearBearerSystem',
				type: 'options',
				options: [
					{
						name: 'Campeche',
						value: 'campeche',
					},
					{
						name: 'Classic',
						value: 'classic',
					},
					{
						name: 'Colonial Yucatec',
						value: 'colonial-yucatec',
					},
				],
				default: 'classic',
				description:
					'Which Haab day is read as the start of the year when naming its Year Bearer. Only four of the twenty day signs can ever carry a year, and which four depends entirely on this choice, so the three schools never agree. "classic" reads the seating of Pop and is the default, because it is the set...',
				routing: {
					send: {
						type: 'body',
						property: 'yearBearerSystem',
					},
				},
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'options',
		options: [
			{
				name: 'Acatl',
				value: 'acatl',
			},
			{
				name: 'Atl',
				value: 'atl',
			},
			{
				name: 'Calli',
				value: 'calli',
			},
			{
				name: 'Cipactli',
				value: 'cipactli',
			},
			{
				name: 'Coatl',
				value: 'coatl',
			},
			{
				name: 'Cozcacuauhtli',
				value: 'cozcacuauhtli',
			},
			{
				name: 'Cuauhtli',
				value: 'cuauhtli',
			},
			{
				name: 'Cuetzpalin',
				value: 'cuetzpalin',
			},
			{
				name: 'Ehecatl',
				value: 'ehecatl',
			},
			{
				name: 'Itzcuintli',
				value: 'itzcuintli',
			},
			{
				name: 'Malinalli',
				value: 'malinalli',
			},
			{
				name: 'Mazatl',
				value: 'mazatl',
			},
			{
				name: 'Miquiztli',
				value: 'miquiztli',
			},
			{
				name: 'Ocelotl',
				value: 'ocelotl',
			},
			{
				name: 'Ollin',
				value: 'ollin',
			},
			{
				name: 'Ozomahtli',
				value: 'ozomahtli',
			},
			{
				name: 'Quiahuitl',
				value: 'quiahuitl',
			},
			{
				name: 'Tecpatl',
				value: 'tecpatl',
			},
			{
				name: 'Tochtli',
				value: 'tochtli',
			},
			{
				name: 'Xochitl',
				value: 'xochitl',
			},
		],
		default: 'cipactli',
		required: true,
		description:
			'Day sign ID, case-insensitive and punctuation-insensitive. One of cipactli, ehecatl, calli, cuetzpalin, coatl, miquiztli, mazatl, tochtli, atl, itzcuintli, ozomahtli, malinalli, acatl, ocelotl, cuauhtli, cozcacuauhtli, ollin, tecpatl, quiahuitl, xochitl.',
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
				operation: ['getAztecDaySign'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
				operation: ['getAztecDaySign'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Number',
		name: 'number',
		type: 'number',
		default: 1,
		required: true,
		description:
			'Trecena number, 1 to 20. Trecena 1 opens on 1 Cipactli, trecena 2 on 1 Ocelotl, and each subsequent period opens thirteen signs further round the twenty.',
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
				operation: ['getAztecTrecena'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
				operation: ['getAztecTrecena'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
				operation: ['getDailyAztecReading'],
			},
		},
		options: [
			{
				displayName: 'Date',
				name: 'date',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-09-02',
				description:
					'Date in YYYY-MM-DD format, in the PROLEPTIC GREGORIAN calendar, extended backwards unchanged through the 1582 reform. Years 1 to 4000 are accepted.',
				routing: {
					send: {
						type: 'query',
						property: 'date',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
				operation: ['getDailyMayanReading'],
			},
		},
		options: [
			{
				displayName: 'Correlation',
				name: 'correlation',
				type: 'options',
				options: [
					{
						name: 'Astronomical 584285',
						value: 'astronomical-584285',
					},
					{
						name: 'Gmt 584283',
						value: 'gmt-584283',
					},
					{
						name: 'Martin Skidmore 584286',
						value: 'martin-skidmore-584286',
					},
					{
						name: 'Martinez Hernandez 584281',
						value: 'martinez-hernandez-584281',
					},
				],
				default: 'gmt-584283',
				description:
					'Which correlation constant ties the day count to a civil date. This is the single choice that shifts every value in the response, so it is a parameter rather than a hidden default, and the resolved value comes back under conventions. "gmt-584283" is the commonly accepted constant and the...',
				routing: {
					send: {
						type: 'query',
						property: 'correlation',
					},
				},
			},
			{
				displayName: 'Date',
				name: 'date',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-09-02',
				description:
					'Date in YYYY-MM-DD format, in the PROLEPTIC GREGORIAN calendar, extended backwards unchanged through the 1582 reform. Years 1 to 4000 are accepted.',
				routing: {
					send: {
						type: 'query',
						property: 'date',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'options',
		options: [
			{
				name: 'Chen',
				value: 'chen',
			},
			{
				name: 'Kankin',
				value: 'kankin',
			},
			{
				name: 'Kayab',
				value: 'kayab',
			},
			{
				name: 'Keh',
				value: 'keh',
			},
			{
				name: 'Kumku',
				value: 'kumku',
			},
			{
				name: 'Mak',
				value: 'mak',
			},
			{
				name: 'Mol',
				value: 'mol',
			},
			{
				name: 'Muwan',
				value: 'muwan',
			},
			{
				name: 'Pax',
				value: 'pax',
			},
			{
				name: 'Pop',
				value: 'pop',
			},
			{
				name: 'Sak',
				value: 'sak',
			},
			{
				name: 'Sek',
				value: 'sek',
			},
			{
				name: 'Sip',
				value: 'sip',
			},
			{
				name: 'Sotz',
				value: 'sotz',
			},
			{
				name: 'Wayeb',
				value: 'wayeb',
			},
			{
				name: 'Wo',
				value: 'wo',
			},
			{
				name: 'Xul',
				value: 'xul',
			},
			{
				name: 'Yax',
				value: 'yax',
			},
			{
				name: 'Yaxkin',
				value: 'yaxkin',
			},
		],
		default: 'pop',
		required: true,
		description:
			'Haab period ID, case-insensitive and punctuation-insensitive. One of pop, wo, sip, sotz, sek, xul, yaxkin, mol, chen, yax, sak, keh, mak, kankin, muwan, pax, kayab, kumku, wayeb.',
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
				operation: ['getHaabMonth'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
				operation: ['getHaabMonth'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'options',
		options: [
			{
				name: 'Ajaw',
				value: 'ajaw',
			},
			{
				name: 'Akbal',
				value: 'akbal',
			},
			{
				name: 'Ben',
				value: 'ben',
			},
			{
				name: 'Chikchan',
				value: 'chikchan',
			},
			{
				name: 'Chuwen',
				value: 'chuwen',
			},
			{
				name: 'Eb',
				value: 'eb',
			},
			{
				name: 'Etznab',
				value: 'etznab',
			},
			{
				name: 'Ik',
				value: 'ik',
			},
			{
				name: 'Imix',
				value: 'imix',
			},
			{
				name: 'Ix',
				value: 'ix',
			},
			{
				name: 'Kaban',
				value: 'kaban',
			},
			{
				name: 'Kan',
				value: 'kan',
			},
			{
				name: 'Kawak',
				value: 'kawak',
			},
			{
				name: 'Kib',
				value: 'kib',
			},
			{
				name: 'Kimi',
				value: 'kimi',
			},
			{
				name: 'Lamat',
				value: 'lamat',
			},
			{
				name: 'Manik',
				value: 'manik',
			},
			{
				name: 'Men',
				value: 'men',
			},
			{
				name: 'Muluk',
				value: 'muluk',
			},
			{
				name: 'Ok',
				value: 'ok',
			},
		],
		default: 'imix',
		required: true,
		description:
			'Day sign ID, case-insensitive and punctuation-insensitive. One of imix, ik, akbal, kan, chikchan, kimi, manik, lamat, muluk, ok, chuwen, eb, ben, ix, men, kib, kaban, etznab, kawak, ajaw.',
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
				operation: ['getMayanDaySign'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
				operation: ['getMayanDaySign'],
			},
		},
		options: [
			{
				displayName: 'Direction Scheme',
				name: 'directionScheme',
				type: 'options',
				options: [
					{
						name: 'Landa',
						value: 'landa',
					},
					{
						name: 'Madrid Codex',
						value: 'madrid-codex',
					},
				],
				default: 'madrid-codex',
				description:
					'Which reading of the world direction and colour to serve for a day sign. The two published assignments differ by exactly one quarter turn on all twenty signs, so neither is a rounding of the other and a silent pick would be a school choice. "madrid-codex" is the codex reading and the default;...',
				routing: {
					send: {
						type: 'query',
						property: 'directionScheme',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
				operation: ['getMonthlyTzolkinCalendar'],
			},
		},
		options: [
			{
				displayName: 'Correlation',
				name: 'correlation',
				type: 'options',
				options: [
					{
						name: 'Astronomical 584285',
						value: 'astronomical-584285',
					},
					{
						name: 'Gmt 584283',
						value: 'gmt-584283',
					},
					{
						name: 'Martin Skidmore 584286',
						value: 'martin-skidmore-584286',
					},
					{
						name: 'Martinez Hernandez 584281',
						value: 'martinez-hernandez-584281',
					},
				],
				default: 'gmt-584283',
				description:
					'Which correlation constant ties the day count to a civil date. This is the single choice that shifts every value in the response, so it is a parameter rather than a hidden default, and the resolved value comes back under conventions. "gmt-584283" is the commonly accepted constant and the...',
				routing: {
					send: {
						type: 'query',
						property: 'correlation',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Month',
				name: 'month',
				type: 'number',
				default: 9,
				typeOptions: {
					minValue: 1,
					maxValue: 12,
				},
				description: 'Calendar month of the grid, 1 to 12. Defaults to the current month in UTC.',
				routing: {
					send: {
						type: 'query',
						property: 'month',
					},
				},
			},
			{
				displayName: 'Year',
				name: 'year',
				type: 'number',
				default: 2026,
				typeOptions: {
					minValue: 1900,
					maxValue: 2100,
				},
				description:
					'Gregorian year of the grid, 1900 to 2100. Defaults to the current year in UTC.',
				routing: {
					send: {
						type: 'query',
						property: 'year',
					},
				},
			},
		],
	},
	{
		displayName: 'Number',
		name: 'number',
		type: 'number',
		default: 1,
		required: true,
		description:
			'Trecena number, 1 to 20. Trecena 1 opens on 1 Imix, trecena 2 on 1 Ix, and each subsequent period opens thirteen signs further round the twenty.',
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
				operation: ['getTrecena'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
				operation: ['getTrecena'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
				operation: ['listAztecDaySigns'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Limit',
				name: 'maxResults',
				type: 'number',
				default: 20,
				typeOptions: {
					minValue: 1,
					maxValue: 20,
				},
				description: 'Maximum items to return per page. Range: 1-20, default 20.',
				routing: {
					send: {
						type: 'query',
						property: 'limit',
					},
				},
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: 0,
				},
				description: 'Number of items to skip for pagination. Default 0.',
				routing: {
					send: {
						type: 'query',
						property: 'offset',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
				operation: ['listAztecTrecenas'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Limit',
				name: 'maxResults',
				type: 'number',
				default: 20,
				typeOptions: {
					minValue: 1,
					maxValue: 20,
				},
				description: 'Maximum items to return per page. Range: 1-20, default 20.',
				routing: {
					send: {
						type: 'query',
						property: 'limit',
					},
				},
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: 0,
				},
				description: 'Number of items to skip for pagination. Default 0.',
				routing: {
					send: {
						type: 'query',
						property: 'offset',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
				operation: ['listHaabMonths'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Limit',
				name: 'maxResults',
				type: 'number',
				default: 19,
				typeOptions: {
					minValue: 1,
					maxValue: 19,
				},
				description: 'Maximum items to return per page. Range: 1-19, default 19.',
				routing: {
					send: {
						type: 'query',
						property: 'limit',
					},
				},
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: 0,
				},
				description: 'Number of items to skip for pagination. Default 0.',
				routing: {
					send: {
						type: 'query',
						property: 'offset',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
				operation: ['listMayanDaySigns'],
			},
		},
		options: [
			{
				displayName: 'Direction Scheme',
				name: 'directionScheme',
				type: 'options',
				options: [
					{
						name: 'Landa',
						value: 'landa',
					},
					{
						name: 'Madrid Codex',
						value: 'madrid-codex',
					},
				],
				default: 'madrid-codex',
				description:
					'Which reading of the world direction and colour to serve for a day sign. The two published assignments differ by exactly one quarter turn on all twenty signs, so neither is a rounding of the other and a silent pick would be a school choice. "madrid-codex" is the codex reading and the default;...',
				routing: {
					send: {
						type: 'query',
						property: 'directionScheme',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Limit',
				name: 'maxResults',
				type: 'number',
				default: 20,
				typeOptions: {
					minValue: 1,
					maxValue: 20,
				},
				description: 'Maximum items to return per page. Range: 1-20, default 20.',
				routing: {
					send: {
						type: 'query',
						property: 'limit',
					},
				},
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: 0,
				},
				description: 'Number of items to skip for pagination. Default 0.',
				routing: {
					send: {
						type: 'query',
						property: 'offset',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['mesoamericanAstrology'],
				operation: ['listTrecenas'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Limit',
				name: 'maxResults',
				type: 'number',
				default: 20,
				typeOptions: {
					minValue: 1,
					maxValue: 20,
				},
				description: 'Maximum items to return per page. Range: 1-20, default 20.',
				routing: {
					send: {
						type: 'query',
						property: 'limit',
					},
				},
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: 0,
				},
				description: 'Number of items to skip for pagination. Default 0.',
				routing: {
					send: {
						type: 'query',
						property: 'offset',
					},
				},
			},
		],
	},
];
