// Generated by scripts/generate.mts from specs/openapi.json. Do not edit.
import type { INodeProperties } from 'n8n-workflow';

export const numerologyDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['numerology'],
			},
		},
		options: [
			{
				name: 'Analyze Karmic Lessons',
				value: 'analyzeKarmicLessons',
				action: 'Analyze karmic lessons',
				description: 'Analyze Karmic Lessons: Missing numbers numerology API',
				routing: {
					request: {
						method: 'POST',
						url: '/numerology/karmic-lessons',
					},
				},
			},
			{
				name: 'Calculate Birth Day',
				value: 'calculateBirthDay',
				action: 'Calculate birth day',
				description: 'Calculate Birth Day number: Birthday numerology API',
				routing: {
					request: {
						method: 'POST',
						url: '/numerology/birth-day',
					},
				},
			},
			{
				name: 'Calculate Bridge Numbers',
				value: 'calculateBridgeNumbers',
				action: 'Calculate bridge numbers',
				description: 'Calculate Bridge Numbers: Numerology bridge numbers API',
				routing: {
					request: {
						method: 'POST',
						url: '/numerology/bridge',
					},
				},
			},
			{
				name: 'Calculate Business Name',
				value: 'calculateBusinessName',
				action: 'Calculate business name',
				description: 'Calculate business name numerology: Brand name numerology API',
				routing: {
					request: {
						method: 'POST',
						url: '/numerology/business-name',
					},
				},
			},
			{
				name: 'Calculate Chaldean',
				value: 'calculateChaldean',
				action: 'Calculate chaldean',
				description: 'Calculate Chaldean numerology: Chaldean name number calculator API',
				routing: {
					request: {
						method: 'POST',
						url: '/numerology/chaldean',
					},
				},
			},
			{
				name: 'Calculate Dual',
				value: 'calculateDual',
				action: 'Calculate dual',
				description: 'Calculate dual numerology: Pythagorean and Chaldean name number API',
				routing: {
					request: {
						method: 'POST',
						url: '/numerology/dual',
					},
				},
			},
			{
				name: 'Calculate Expression',
				value: 'calculateExpression',
				action: 'Calculate expression',
				description: 'Calculate Expression number: Destiny number calculator API',
				routing: {
					request: {
						method: 'POST',
						url: '/numerology/expression',
					},
				},
			},
			{
				name: 'Calculate Life Path',
				value: 'calculateLifePath',
				action: 'Calculate life path',
				description: 'Calculate Life Path number: Calculator and meaning API',
				routing: {
					request: {
						method: 'POST',
						url: '/numerology/life-path',
					},
				},
			},
			{
				name: 'Calculate Maturity',
				value: 'calculateMaturity',
				action: 'Calculate maturity',
				description: 'Calculate Maturity number: Realization number numerology API',
				routing: {
					request: {
						method: 'POST',
						url: '/numerology/maturity',
					},
				},
			},
			{
				name: 'Calculate Numerology Compatibility',
				value: 'calculateNumCompatibility',
				action: 'Calculate numerology compatibility',
				description: 'Calculate numerology compatibility: Love match scoring API',
				routing: {
					request: {
						method: 'POST',
						url: '/numerology/compatibility',
					},
				},
			},
			{
				name: 'Calculate Personal Day',
				value: 'calculatePersonalDay',
				action: 'Calculate personal day',
				description: 'Calculate Personal Day: Daily numerology forecast API',
				routing: {
					request: {
						method: 'POST',
						url: '/numerology/personal-day',
					},
				},
			},
			{
				name: 'Calculate Personal Month',
				value: 'calculatePersonalMonth',
				action: 'Calculate personal month',
				description: 'Calculate Personal Month: Monthly numerology forecast API',
				routing: {
					request: {
						method: 'POST',
						url: '/numerology/personal-month',
					},
				},
			},
			{
				name: 'Calculate Personal Year',
				value: 'calculatePersonalYear',
				action: 'Calculate personal year',
				description: 'Calculate Personal Year: Personal Year number forecast API',
				routing: {
					request: {
						method: 'POST',
						url: '/numerology/personal-year',
					},
				},
			},
			{
				name: 'Calculate Personality',
				value: 'calculatePersonality',
				action: 'Calculate personality',
				description: 'Calculate Personality number: Outer personality numerology API',
				routing: {
					request: {
						method: 'POST',
						url: '/numerology/personality',
					},
				},
			},
			{
				name: 'Calculate Soul Urge',
				value: 'calculateSoulUrge',
				action: 'Calculate soul urge',
				description: 'Calculate Soul Urge number: Heart Desire number calculator API',
				routing: {
					request: {
						method: 'POST',
						url: '/numerology/soul-urge',
					},
				},
			},
			{
				name: 'Check Karmic Debt',
				value: 'checkKarmicDebt',
				action: 'Check karmic debt',
				description: 'Detect Karmic Debt numbers: Karmic debt 13, 14, 16, 19 API',
				routing: {
					request: {
						method: 'POST',
						url: '/numerology/karmic-debt',
					},
				},
			},
			{
				name: 'Generate Numerology Chart',
				value: 'generateNumerologyChart',
				action: 'Generate numerology chart',
				description: 'Generate numerology chart: Complete numerology reading API',
				routing: {
					request: {
						method: 'POST',
						url: '/numerology/chart',
					},
				},
			},
			{
				name: 'Get Compound Number',
				value: 'getCompoundNumber',
				action: 'Get compound number',
				description: 'Get compound number meaning: Chaldean compound numbers 10 to 52 API',
				routing: {
					request: {
						method: 'GET',
						url: '=/numerology/compound-number/{{encodeURIComponent($parameter["number"])}}',
					},
				},
			},
			{
				name: 'Get Daily Number',
				value: 'getDailyNumber',
				action: 'Get daily number',
				description: 'Get daily numerology number: Number of the Day API',
				routing: {
					request: {
						method: 'POST',
						url: '/numerology/daily',
					},
				},
			},
			{
				name: 'Get Number Meaning',
				value: 'getNumberMeaning',
				action: 'Get number meaning',
				description: 'Get number meaning: Numerology number meanings API',
				routing: {
					request: {
						method: 'GET',
						url: '=/numerology/meanings/{{encodeURIComponent($parameter["number"])}}',
					},
				},
			},
		],
		default: 'analyzeKarmicLessons',
	},
	{
		displayName: 'Full Name',
		name: 'fullName',
		type: 'string',
		default: '',
		placeholder: 'e.g. John William Smith',
		required: true,
		description:
			'Full birth name to analyze for missing numbers. A name in any script is converted to Latin letters before it is counted, Cyrillic and Greek as the passport spelling and accents folded to the base letter, and the calculation lists the letters counted.',
		routing: {
			send: {
				type: 'body',
				property: 'fullName',
			},
		},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['analyzeKarmicLessons'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['analyzeKarmicLessons'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Day',
		name: 'day',
		type: 'number',
		default: 23,
		typeOptions: {
			minValue: 1,
			maxValue: 31,
		},
		required: true,
		description: 'Day of birth (1-31)',
		routing: {
			send: {
				type: 'body',
				property: 'day',
			},
		},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculateBirthDay'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculateBirthDay'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Full Name',
		name: 'fullName',
		type: 'string',
		default: '',
		placeholder: 'e.g. John William Smith',
		required: true,
		description:
			'Full birth name as it appears on the birth certificate, first, middle and last names separated by spaces. Used to calculate the Expression, Soul Urge and Personality numbers.',
		routing: {
			send: {
				type: 'body',
				property: 'fullName',
			},
		},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculateBridgeNumbers'],
			},
		},
	},
	{
		displayName: 'Year',
		name: 'year',
		type: 'number',
		default: 1990,
		typeOptions: {
			minValue: 100,
			maxValue: 2100,
		},
		required: true,
		description:
			'Birth year between 100 and 2100. Used to calculate the Life Path number via Pythagorean reduction.',
		routing: {
			send: {
				type: 'body',
				property: 'year',
			},
		},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculateBridgeNumbers'],
			},
		},
	},
	{
		displayName: 'Month',
		name: 'month',
		type: 'number',
		default: 7,
		typeOptions: {
			minValue: 1,
			maxValue: 12,
		},
		required: true,
		description: 'Birth month (1 to 12)',
		routing: {
			send: {
				type: 'body',
				property: 'month',
			},
		},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculateBridgeNumbers'],
			},
		},
	},
	{
		displayName: 'Day',
		name: 'day',
		type: 'number',
		default: 15,
		typeOptions: {
			minValue: 1,
			maxValue: 31,
		},
		required: true,
		description: 'Birth day (1 to 31)',
		routing: {
			send: {
				type: 'body',
				property: 'day',
			},
		},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculateBridgeNumbers'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculateBridgeNumbers'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		default: '',
		placeholder: 'e.g. Ford',
		required: true,
		description:
			'The business or brand name to evaluate. A name in any script is converted to Latin letters before it is counted, Cyrillic and Greek as the passport spelling and accents folded to the base letter, and the calculation lists the letters counted.',
		routing: {
			send: {
				type: 'body',
				property: 'name',
			},
		},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculateBusinessName'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculateBusinessName'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		default: '',
		placeholder: 'e.g. Helen',
		required: true,
		description:
			'The name to analyze. Chaldean tradition uses the name a person is most known by, not necessarily the full legal birth name.',
		routing: {
			send: {
				type: 'body',
				property: 'name',
			},
		},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculateChaldean'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculateChaldean'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		default: '',
		placeholder: 'e.g. David',
		required: true,
		description:
			'The name to analyze in both systems. A name in any script is converted to Latin letters before it is counted, Cyrillic and Greek as the passport spelling and accents folded to the base letter, and the calculation lists the letters counted.',
		routing: {
			send: {
				type: 'body',
				property: 'name',
			},
		},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculateDual'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculateDual'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Full Name',
		name: 'fullName',
		type: 'string',
		default: '',
		placeholder: 'e.g. John William Smith',
		required: true,
		description:
			'Full birth name (first, middle, last). A name in any script is converted to Latin letters before it is counted, Cyrillic and Greek as the passport spelling and accents folded to the base letter, and the calculation lists the letters counted.',
		routing: {
			send: {
				type: 'body',
				property: 'fullName',
			},
		},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculateExpression'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculateExpression'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Year',
		name: 'year',
		type: 'number',
		default: 1990,
		typeOptions: {
			minValue: 100,
			maxValue: 2100,
		},
		required: true,
		description:
			'Birth year between 100 and 2100. Supports historical figures like Einstein (1879) and Shakespeare (1564).',
		routing: {
			send: {
				type: 'body',
				property: 'year',
			},
		},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculateLifePath'],
			},
		},
	},
	{
		displayName: 'Month',
		name: 'month',
		type: 'number',
		default: 7,
		typeOptions: {
			minValue: 1,
			maxValue: 12,
		},
		required: true,
		description: 'Birth month (1-12)',
		routing: {
			send: {
				type: 'body',
				property: 'month',
			},
		},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculateLifePath'],
			},
		},
	},
	{
		displayName: 'Day',
		name: 'day',
		type: 'number',
		default: 15,
		typeOptions: {
			minValue: 1,
			maxValue: 31,
		},
		required: true,
		description: 'Birth day (1-31)',
		routing: {
			send: {
				type: 'body',
				property: 'day',
			},
		},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculateLifePath'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculateLifePath'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculateMaturity'],
			},
		},
		options: [
			{
				displayName: 'Day',
				name: 'day',
				type: 'number',
				default: 15,
				typeOptions: {
					minValue: 1,
					maxValue: 31,
				},
				description:
					'Birth day (1-31). Required with year and month for automatic Life Path calculation.',
				routing: {
					send: {
						type: 'body',
						property: 'day',
					},
				},
			},
			{
				displayName: 'Expression',
				name: 'expression',
				type: 'number',
				default: 7,
				typeOptions: {
					minValue: 1,
					maxValue: 33,
				},
				description: 'Your Expression number (1-9, 11, 22, 33). Optional if fullName is provided.',
				routing: {
					send: {
						type: 'body',
						property: 'expression',
					},
				},
			},
			{
				displayName: 'Full Name',
				name: 'fullName',
				type: 'string',
				default: '',
				placeholder: 'e.g. John William Smith',
				description:
					'Full birth name to calculate the Expression number automatically. Use instead of passing expression directly.',
				routing: {
					send: {
						type: 'body',
						property: 'fullName',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Life Path',
				name: 'lifePath',
				type: 'number',
				default: 5,
				typeOptions: {
					minValue: 1,
					maxValue: 33,
				},
				description:
					'Your Life Path number (1-9, 11, 22, 33). Optional if year, month, day are provided.',
				routing: {
					send: {
						type: 'body',
						property: 'lifePath',
					},
				},
			},
			{
				displayName: 'Month',
				name: 'month',
				type: 'number',
				default: 7,
				typeOptions: {
					minValue: 1,
					maxValue: 12,
				},
				description:
					'Birth month (1-12). Required with year and day for automatic Life Path calculation.',
				routing: {
					send: {
						type: 'body',
						property: 'month',
					},
				},
			},
			{
				displayName: 'Year',
				name: 'year',
				type: 'number',
				default: 1990,
				typeOptions: {
					minValue: 100,
					maxValue: 2100,
				},
				description:
					'Birth year to calculate Life Path automatically. Use with month and day instead of passing lifePath directly.',
				routing: {
					send: {
						type: 'body',
						property: 'year',
					},
				},
			},
		],
	},
	{
		displayName: 'Person1',
		name: 'person1',
		type: 'json',
		default:
			'{\n  "fullName": "John William Smith",\n  "year": 1990,\n  "month": 7,\n  "day": 15,\n  "lifePath": 5,\n  "expression": 7,\n  "soulUrge": 6\n}',
		required: true,
		routing: {
			send: {
				type: 'body',
				property: 'person1',
				value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculateNumCompatibility'],
			},
		},
	},
	{
		displayName: 'Person2',
		name: 'person2',
		type: 'json',
		default:
			'{\n  "fullName": "Jane Marie Doe",\n  "year": 1992,\n  "month": 3,\n  "day": 22,\n  "lifePath": 3,\n  "expression": 9,\n  "soulUrge": 2\n}',
		required: true,
		routing: {
			send: {
				type: 'body',
				property: 'person2',
				value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculateNumCompatibility'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculateNumCompatibility'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Month',
		name: 'month',
		type: 'number',
		default: 7,
		typeOptions: {
			minValue: 1,
			maxValue: 12,
		},
		required: true,
		description: 'Birth month (1-12)',
		routing: {
			send: {
				type: 'body',
				property: 'month',
			},
		},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculatePersonalDay'],
			},
		},
	},
	{
		displayName: 'Day',
		name: 'day',
		type: 'number',
		default: 18,
		typeOptions: {
			minValue: 1,
			maxValue: 31,
		},
		required: true,
		description: 'Birth day (1-31)',
		routing: {
			send: {
				type: 'body',
				property: 'day',
			},
		},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculatePersonalDay'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculatePersonalDay'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Target Date',
				name: 'targetDate',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-04-04',
				description:
					'Target date in YYYY-MM-DD format, in the years 100 to 2100. Defaults to today (UTC).',
				routing: {
					send: {
						type: 'body',
						property: 'targetDate',
					},
				},
			},
		],
	},
	{
		displayName: 'Month',
		name: 'month',
		type: 'number',
		default: 7,
		typeOptions: {
			minValue: 1,
			maxValue: 12,
		},
		required: true,
		description: 'Birth month (1-12)',
		routing: {
			send: {
				type: 'body',
				property: 'month',
			},
		},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculatePersonalMonth'],
			},
		},
	},
	{
		displayName: 'Day',
		name: 'day',
		type: 'number',
		default: 18,
		typeOptions: {
			minValue: 1,
			maxValue: 31,
		},
		required: true,
		description: 'Birth day (1-31)',
		routing: {
			send: {
				type: 'body',
				property: 'day',
			},
		},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculatePersonalMonth'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculatePersonalMonth'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Target Month',
				name: 'targetMonth',
				type: 'number',
				default: 4,
				typeOptions: {
					minValue: 1,
					maxValue: 12,
				},
				description:
					'Target calendar month to forecast (1 to 12). Defaults to the current UTC month.',
				routing: {
					send: {
						type: 'body',
						property: 'targetMonth',
					},
				},
			},
			{
				displayName: 'Year',
				name: 'year',
				type: 'number',
				default: 2026,
				typeOptions: {
					minValue: 100,
					maxValue: 2100,
				},
				description: 'Target year. Defaults to the current UTC year.',
				routing: {
					send: {
						type: 'body',
						property: 'year',
					},
				},
			},
		],
	},
	{
		displayName: 'Month',
		name: 'month',
		type: 'number',
		default: 7,
		typeOptions: {
			minValue: 1,
			maxValue: 12,
		},
		required: true,
		description: 'Birth month (1-12)',
		routing: {
			send: {
				type: 'body',
				property: 'month',
			},
		},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculatePersonalYear'],
			},
		},
	},
	{
		displayName: 'Day',
		name: 'day',
		type: 'number',
		default: 15,
		typeOptions: {
			minValue: 1,
			maxValue: 31,
		},
		required: true,
		description: 'Birth day (1-31)',
		routing: {
			send: {
				type: 'body',
				property: 'day',
			},
		},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculatePersonalYear'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculatePersonalYear'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Year',
				name: 'year',
				type: 'number',
				default: 2025,
				typeOptions: {
					minValue: 100,
					maxValue: 2100,
				},
				description:
					'Year to forecast. Defaults to the current UTC year; the Personal Year turns over on 1 January.',
				routing: {
					send: {
						type: 'body',
						property: 'year',
					},
				},
			},
		],
	},
	{
		displayName: 'Full Name',
		name: 'fullName',
		type: 'string',
		default: '',
		placeholder: 'e.g. John William Smith',
		required: true,
		description:
			'Full birth name. Its consonants give the Personality number, so a name with none is refused.',
		routing: {
			send: {
				type: 'body',
				property: 'fullName',
			},
		},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculatePersonality'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculatePersonality'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Full Name',
		name: 'fullName',
		type: 'string',
		default: '',
		placeholder: 'e.g. John William Smith',
		required: true,
		description:
			'Full birth name. Its vowels A, E, I, O and U give the Soul Urge, so a name with none is refused.',
		routing: {
			send: {
				type: 'body',
				property: 'fullName',
			},
		},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculateSoulUrge'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['calculateSoulUrge'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['checkKarmicDebt'],
			},
		},
		options: [
			{
				displayName: 'Day',
				name: 'day',
				type: 'number',
				default: 15,
				typeOptions: {
					minValue: 1,
					maxValue: 31,
				},
				description: 'Birth day (checks Birth Day on its own, and Life Path with year and month)',
				routing: {
					send: {
						type: 'body',
						property: 'day',
					},
				},
			},
			{
				displayName: 'Full Name',
				name: 'fullName',
				type: 'string',
				default: '',
				placeholder: 'e.g. John William Smith',
				description:
					'Full birth name (checks Expression, Soul Urge, Personality). A name in any script is converted to Latin letters before it is counted, Cyrillic and Greek as the passport spelling and accents folded to the base letter, and the calculation lists the letters counted.',
				routing: {
					send: {
						type: 'body',
						property: 'fullName',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Month',
				name: 'month',
				type: 'number',
				default: 7,
				typeOptions: {
					minValue: 1,
					maxValue: 12,
				},
				description: 'Birth month (checks Life Path)',
				routing: {
					send: {
						type: 'body',
						property: 'month',
					},
				},
			},
			{
				displayName: 'Year',
				name: 'year',
				type: 'number',
				default: 1990,
				typeOptions: {
					minValue: 100,
					maxValue: 2100,
				},
				description: 'Birth year (checks Life Path)',
				routing: {
					send: {
						type: 'body',
						property: 'year',
					},
				},
			},
		],
	},
	{
		displayName: 'Full Name',
		name: 'fullName',
		type: 'string',
		default: '',
		placeholder: 'e.g. John William Smith',
		required: true,
		description:
			'Full birth name as it appears on the birth certificate. Used for every letter-based number in the chart: Expression, Soul Urge, Personality, Karmic Lessons, Hidden Passion, Subconscious Self and the special letters.',
		routing: {
			send: {
				type: 'body',
				property: 'fullName',
			},
		},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['generateNumerologyChart'],
			},
		},
	},
	{
		displayName: 'Year',
		name: 'year',
		type: 'number',
		default: 1990,
		typeOptions: {
			minValue: 100,
			maxValue: 2100,
		},
		required: true,
		description:
			'Birth year between 100 and 2100. Supports historical figures like Einstein (1879) and Shakespeare (1564).',
		routing: {
			send: {
				type: 'body',
				property: 'year',
			},
		},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['generateNumerologyChart'],
			},
		},
	},
	{
		displayName: 'Month',
		name: 'month',
		type: 'number',
		default: 7,
		typeOptions: {
			minValue: 1,
			maxValue: 12,
		},
		required: true,
		description: 'Birth month (1-12)',
		routing: {
			send: {
				type: 'body',
				property: 'month',
			},
		},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['generateNumerologyChart'],
			},
		},
	},
	{
		displayName: 'Day',
		name: 'day',
		type: 'number',
		default: 15,
		typeOptions: {
			minValue: 1,
			maxValue: 31,
		},
		required: true,
		description: 'Birth day (1-31)',
		routing: {
			send: {
				type: 'body',
				property: 'day',
			},
		},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['generateNumerologyChart'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['generateNumerologyChart'],
			},
		},
		options: [
			{
				displayName: 'Current Year',
				name: 'currentYear',
				type: 'number',
				default: 2025,
				typeOptions: {
					minValue: 100,
					maxValue: 2100,
				},
				description:
					'Calendar year for the Personal Year, defaults to the current UTC year. It moves the Personal Year only: the nested personalMonth and maturityStatus.currentAge always read the current UTC date.',
				routing: {
					send: {
						type: 'body',
						property: 'currentYear',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Number',
		name: 'number',
		type: 'string',
		default: '',
		placeholder: 'e.g. 23',
		required: true,
		description: 'Compound number from 10 to 52',
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['getCompoundNumber'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['getCompoundNumber'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['getDailyNumber'],
			},
		},
		options: [
			{
				displayName: 'Date',
				name: 'date',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-03-06',
				description: 'Date for the reading in YYYY-MM-DD format. Defaults to today (UTC).',
				routing: {
					send: {
						type: 'body',
						property: 'date',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Seed',
				name: 'seed',
				type: 'string',
				default: '',
				placeholder: 'e.g. user123',
				description:
					'Optional seed for reproducible readings. Same seed + same date = same number every time.',
				routing: {
					send: {
						type: 'body',
						property: 'seed',
					},
				},
			},
		],
	},
	{
		displayName: 'Number',
		name: 'number',
		type: 'string',
		default: '',
		placeholder: 'e.g. 5',
		required: true,
		description: 'Numerology number (1-9, 11, 22, 33)',
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['getNumberMeaning'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['numerology'],
				operation: ['getNumberMeaning'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
];
