// Generated by scripts/generate.mts from specs/openapi.json. Do not edit.
import type { INodeProperties } from 'n8n-workflow';

export const tarotDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['tarot'],
			},
		},
		options: [
			{
				name: 'Cast Career Spread',
				value: 'castCareerSpread',
				action: 'Cast career spread',
				description: 'Career spread, 7 cards: Career tarot reading API',
				routing: {
					request: {
						method: 'POST',
						url: '/tarot/spreads/career',
					},
				},
			},
			{
				name: 'Cast Celtic Cross',
				value: 'castCelticCross',
				action: 'Cast celtic cross',
				description: 'Celtic Cross spread, 10 cards: Tarot spread API',
				routing: {
					request: {
						method: 'POST',
						url: '/tarot/spreads/celtic-cross',
					},
				},
			},
			{
				name: 'Cast Custom Spread',
				value: 'castCustomSpread',
				action: 'Cast custom spread',
				description: 'Custom spread builder: Configurable tarot spread API',
				routing: {
					request: {
						method: 'POST',
						url: '/tarot/spreads/custom',
					},
				},
			},
			{
				name: 'Cast Love Spread',
				value: 'castLoveSpread',
				action: 'Cast love spread',
				description: 'Love spread, 5 cards: Relationship tarot reading API',
				routing: {
					request: {
						method: 'POST',
						url: '/tarot/spreads/love',
					},
				},
			},
			{
				name: 'Cast Three Card',
				value: 'castThreeCard',
				action: 'Cast three card',
				description: 'Three card spread, past present future: Tarot spread API',
				routing: {
					request: {
						method: 'POST',
						url: '/tarot/spreads/three-card',
					},
				},
			},
			{
				name: 'Cast Yes No',
				value: 'castYesNo',
				action: 'Cast yes no',
				description: 'Yes or no answer: Yes no tarot reading API',
				routing: {
					request: {
						method: 'POST',
						url: '/tarot/yes-no',
					},
				},
			},
			{
				name: 'Draw Cards',
				value: 'drawCards',
				action: 'Draw cards',
				description: 'Draw tarot cards: Seeded tarot draw API',
				routing: {
					request: {
						method: 'POST',
						url: '/tarot/draw',
					},
				},
			},
			{
				name: 'Get Card',
				value: 'getCard',
				action: 'Get card',
				description: 'Get tarot card by ID: Tarot card meaning API',
				routing: {
					request: {
						method: 'GET',
						url: '=/tarot/cards/{{encodeURIComponent($parameter["id"])}}',
					},
				},
			},
			{
				name: 'Get Daily Card',
				value: 'getDailyCard',
				action: 'Get daily card',
				description: 'Daily tarot card: Card of the day API',
				routing: {
					request: {
						method: 'POST',
						url: '/tarot/daily',
					},
				},
			},
			{
				name: 'List Cards',
				value: 'listCards',
				action: 'List cards',
				description: 'List all 78 tarot cards: Tarot deck catalog API',
				routing: {
					request: {
						method: 'GET',
						url: '/tarot/cards',
					},
				},
			},
		],
		default: 'castCareerSpread',
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['tarot'],
				operation: ['castCareerSpread'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Question',
				name: 'question',
				type: 'string',
				default: '',
				placeholder: 'e.g. What do I need to know about my career path?',
				description:
					'Optional querent question to focus the career spread. It is echoed back on the reading and gives the seven career positions their context.',
				routing: {
					send: {
						type: 'body',
						property: 'question',
					},
				},
			},
			{
				displayName: 'Seed',
				name: 'seed',
				type: 'string',
				default: '',
				placeholder: 'e.g. reading-2f9c1a',
				description:
					'Optional seed for reproducible results. The same seed always draws the same seven cards into the same career positions, which is what lets a reading be shared or re-rendered.',
				routing: {
					send: {
						type: 'body',
						property: 'seed',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['tarot'],
				operation: ['castCelticCross'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Question',
				name: 'question',
				type: 'string',
				default: '',
				placeholder: 'e.g. What should I know about this situation?',
				description:
					'Optional querent question to focus the Celtic Cross. It is echoed back on the reading and gives the ten positions their context.',
				routing: {
					send: {
						type: 'body',
						property: 'question',
					},
				},
			},
			{
				displayName: 'Seed',
				name: 'seed',
				type: 'string',
				default: '',
				placeholder: 'e.g. reading-2f9c1a',
				description:
					'Optional seed for reproducible results. The same seed always draws the same ten cards into the same Celtic Cross positions, which is what lets a reading be shared or re-rendered.',
				routing: {
					send: {
						type: 'body',
						property: 'seed',
					},
				},
			},
		],
	},
	{
		displayName: 'Positions',
		name: 'positions',
		type: 'json',
		default:
			'[\n  {\n    "name": "Core Issue",\n    "interpretation": "What is really going on"\n  },\n  {\n    "name": "Hidden Factor",\n    "interpretation": "What you cannot see"\n  },\n  {\n    "name": "Best Action",\n    "interpretation": "What to do next"\n  }\n]',
		required: true,
		description:
			'Array of 1-10 custom position definitions for your tarot spread. Each position gets one drawn card with a position-specific interpretation.',
		routing: {
			send: {
				type: 'body',
				property: 'positions',
				value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['tarot'],
				operation: ['castCustomSpread'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['tarot'],
				operation: ['castCustomSpread'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Question',
				name: 'question',
				type: 'string',
				default: '',
				placeholder: 'e.g. How do I move forward with this project?',
				description:
					'Optional querent question to focus the custom tarot reading. Provides context for position-specific interpretations.',
				routing: {
					send: {
						type: 'body',
						property: 'question',
					},
				},
			},
			{
				displayName: 'Seed',
				name: 'seed',
				type: 'string',
				default: '',
				placeholder: 'e.g. reading-2f9c1a',
				description:
					'Optional seed for reproducible results. Same seed with the same positions produces identical card draws for consistent divination.',
				routing: {
					send: {
						type: 'body',
						property: 'seed',
					},
				},
			},
			{
				displayName: 'Spread Name',
				name: 'spreadName',
				type: 'string',
				default: '',
				placeholder: 'e.g. My Custom Spread',
				description:
					'Optional name for your custom tarot spread layout. Used as the spread identifier in the response.',
				routing: {
					send: {
						type: 'body',
						property: 'spreadName',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['tarot'],
				operation: ['castLoveSpread'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Question',
				name: 'question',
				type: 'string',
				default: '',
				placeholder: 'e.g. What do I need to know about my relationship?',
				description:
					'Optional querent question to focus the love spread. It is echoed back on the reading and gives the five relationship positions their context.',
				routing: {
					send: {
						type: 'body',
						property: 'question',
					},
				},
			},
			{
				displayName: 'Seed',
				name: 'seed',
				type: 'string',
				default: '',
				placeholder: 'e.g. reading-2f9c1a',
				description:
					'Optional seed for reproducible results. The same seed always draws the same five cards into the same love positions, which is what lets a reading be shared or re-rendered.',
				routing: {
					send: {
						type: 'body',
						property: 'seed',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['tarot'],
				operation: ['castThreeCard'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Question',
				name: 'question',
				type: 'string',
				default: '',
				placeholder: 'e.g. What do I need to know about my career?',
				description:
					'Optional specific question to focus the reading. Examples: "What should I know about my relationship?", "How can I improve my finances?", "What is blocking my creative growth?" Leave empty for general guidance.',
				routing: {
					send: {
						type: 'body',
						property: 'question',
					},
				},
			},
			{
				displayName: 'Seed',
				name: 'seed',
				type: 'string',
				default: '',
				placeholder: 'e.g. reading-2f9c1a',
				description:
					'Optional seed for reproducible results. Same seed = same 3 cards in same positions.',
				routing: {
					send: {
						type: 'body',
						property: 'seed',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['tarot'],
				operation: ['castYesNo'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Question',
				name: 'question',
				type: 'string',
				default: '',
				placeholder: 'e.g. Should I accept the job offer?',
				description: 'Your specific yes/no question. Be clear and focused.',
				routing: {
					send: {
						type: 'body',
						property: 'question',
					},
				},
			},
			{
				displayName: 'Seed',
				name: 'seed',
				type: 'string',
				default: '',
				placeholder: 'e.g. reading-2f9c1a',
				description:
					'Optional seed for reproducible results. Same seed + same question = same answer.',
				routing: {
					send: {
						type: 'body',
						property: 'seed',
					},
				},
			},
		],
	},
	{
		displayName: 'Count',
		name: 'count',
		type: 'number',
		default: 3,
		typeOptions: {
			minValue: 1,
			maxValue: 78,
		},
		required: true,
		description:
			'Number of cards to draw (1-78). Common values: 1 for daily card, 3 for past-present-future, 5 for relationship spread, 10 for Celtic Cross.',
		routing: {
			send: {
				type: 'body',
				property: 'count',
			},
		},
		displayOptions: {
			show: {
				resource: ['tarot'],
				operation: ['drawCards'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['tarot'],
				operation: ['drawCards'],
			},
		},
		options: [
			{
				displayName: 'Allow Duplicates',
				name: 'allowDuplicates',
				type: 'boolean',
				default: false,
				description:
					'Whether same card can be drawn multiple times. Set false for traditional deck behavior (each card drawn only once).',
				routing: {
					send: {
						type: 'body',
						property: 'allowDuplicates',
					},
				},
			},
			{
				displayName: 'Allow Reversals',
				name: 'allowReversals',
				type: 'boolean',
				default: true,
				description:
					'Whether cards can appear reversed (upside down). Reversed cards have different meanings.',
				routing: {
					send: {
						type: 'body',
						property: 'allowReversals',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Seed',
				name: 'seed',
				type: 'string',
				default: '',
				placeholder: 'e.g. user123-2025-12-27',
				description:
					'Optional seed for reproducible results. Same seed = same cards in same order.',
				routing: {
					send: {
						type: 'body',
						property: 'seed',
					},
				},
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		placeholder: 'e.g. fool',
		required: true,
		description: 'Card identifier. Major arcana: "fool", "magician", "death".',
		displayOptions: {
			show: {
				resource: ['tarot'],
				operation: ['getCard'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['tarot'],
				operation: ['getCard'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['tarot'],
				operation: ['getDailyCard'],
			},
		},
		options: [
			{
				displayName: 'Date',
				name: 'date',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-03-06',
				description: 'Date for the reading in YYYY-MM-DD format. Defaults to today (UTC).',
				routing: {
					send: {
						type: 'body',
						property: 'date',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Seed',
				name: 'seed',
				type: 'string',
				default: '',
				placeholder: 'e.g. user123',
				description:
					'Optional seed for reproducible readings. Same seed + same date = same card every time.',
				routing: {
					send: {
						type: 'body',
						property: 'seed',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['tarot'],
				operation: ['listCards'],
			},
		},
		options: [
			{
				displayName: 'Arcana',
				name: 'arcana',
				type: 'options',
				options: [
					{
						name: 'Major',
						value: 'major',
					},
					{
						name: 'Minor',
						value: 'minor',
					},
				],
				default: 'major',
				description:
					'Filter by arcana type. Major arcana (0-21) represents life lessons and spiritual themes.',
				routing: {
					send: {
						type: 'query',
						property: 'arcana',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Limit',
				name: 'maxResults',
				type: 'number',
				default: 20,
				typeOptions: {
					minValue: 1,
					maxValue: 100,
				},
				description: 'Maximum items to return per page. Range: 1-100, default 20.',
				routing: {
					send: {
						type: 'query',
						property: 'limit',
					},
				},
			},
			{
				displayName: 'Number',
				name: 'number',
				type: 'number',
				default: 1,
				typeOptions: {
					minValue: 0,
					maxValue: 21,
				},
				description: 'Filter by card number. Major Arcana: 0 (The Fool) through 21 (The World).',
				routing: {
					send: {
						type: 'query',
						property: 'number',
					},
				},
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: 0,
				},
				description: 'Number of items to skip for pagination. Default 0.',
				routing: {
					send: {
						type: 'query',
						property: 'offset',
					},
				},
			},
			{
				displayName: 'Suit',
				name: 'suit',
				type: 'options',
				options: [
					{
						name: 'Cups',
						value: 'cups',
					},
					{
						name: 'Pentacles',
						value: 'pentacles',
					},
					{
						name: 'Swords',
						value: 'swords',
					},
					{
						name: 'Wands',
						value: 'wands',
					},
				],
				default: 'cups',
				description:
					'Filter minor arcana by suit. Cups=emotions/relationships, Wands=creativity/passion, Swords=intellect/conflict, Pentacles=material/finances.',
				routing: {
					send: {
						type: 'query',
						property: 'suit',
					},
				},
			},
		],
	},
];
