// Generated by scripts/generate.mts from specs/openapi.json. Do not edit.
import type { INodeProperties } from 'n8n-workflow';

export const vastuDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['vastu'],
			},
		},
		options: [
			{
				name: 'Calculate Ayadi',
				value: 'calculateAyadi',
				action: 'Calculate ayadi',
				description: 'Calculate Ayadi shadvarga: Vastu proportion and yoni calculator API',
				routing: {
					request: {
						method: 'POST',
						url: '/vastu/ayadi',
					},
				},
			},
			{
				name: 'Calculate Entrance Pada',
				value: 'calculateEntrancePada',
				action: 'Calculate entrance pada',
				description: 'Calculate entrance pada: Vastu main door direction API',
				routing: {
					request: {
						method: 'POST',
						url: '/vastu/entrance',
					},
				},
			},
			{
				name: 'Calculate Plot Analysis',
				value: 'calculatePlotAnalysis',
				action: 'Calculate plot analysis',
				description: 'Analyse a plot: Vastu land and site assessment API',
				routing: {
					request: {
						method: 'POST',
						url: '/vastu/plot',
					},
				},
			},
			{
				name: 'Calculate Room Compliance',
				value: 'calculateRoomCompliance',
				action: 'Calculate room compliance',
				description: 'Check room placement: Vastu room direction compliance API',
				routing: {
					request: {
						method: 'POST',
						url: '/vastu/rooms',
					},
				},
			},
			{
				name: 'Find Griha Pravesh Dates',
				value: 'findGrihaPraveshDates',
				action: 'Find griha pravesh dates',
				description: 'Find griha pravesh dates: Vastu house warming muhurta API',
				routing: {
					request: {
						method: 'POST',
						url: '/vastu/timing/griha-pravesh',
					},
				},
			},
			{
				name: 'Generate Mandala',
				value: 'generateMandala',
				action: 'Generate mandala',
				description: 'Generate Vastu Purusha Mandala: 81 pada and 64 pada grid API',
				routing: {
					request: {
						method: 'POST',
						url: '/vastu/mandala',
					},
				},
			},
			{
				name: 'Get Devata',
				value: 'getDevata',
				action: 'Get devata',
				description: 'Look up one devata: Vastu mandala devata reference API',
				routing: {
					request: {
						method: 'GET',
						url: '=/vastu/devatas/{{encodeURIComponent($parameter["id"])}}',
					},
				},
			},
			{
				name: 'Get Dikpala Direction',
				value: 'getDikpalaDirection',
				action: 'Get dikpala direction',
				description: 'Look up one direction: Vastu dikpala reference API',
				routing: {
					request: {
						method: 'GET',
						url: '=/vastu/directions/{{encodeURIComponent($parameter["id"])}}',
					},
				},
			},
			{
				name: 'List Devatas',
				value: 'listDevatas',
				action: 'List devatas',
				description: 'List the 45 devatas: Vastu Purusha Mandala reference API',
				routing: {
					request: {
						method: 'GET',
						url: '/vastu/devatas',
					},
				},
			},
			{
				name: 'List Dikpala Directions',
				value: 'listDikpalaDirections',
				action: 'List dikpala directions',
				description: 'List the eight directions: Vastu dikpala and direction reference API',
				routing: {
					request: {
						method: 'GET',
						url: '/vastu/directions',
					},
				},
			},
		],
		default: 'calculateAyadi',
	},
	{
		displayName: 'Length',
		name: 'length',
		type: 'number',
		default: 11,
		typeOptions: {
			numberPrecision: 6,
		},
		required: true,
		description:
			'Length of the building or room, in the unit given. Under the Manasara family this is the measure the aya and rksha formulas multiply; under the perimeter family it only feeds the perimeter.',
		routing: {
			send: {
				type: 'body',
				property: 'length',
			},
		},
		displayOptions: {
			show: {
				resource: ['vastu'],
				operation: ['calculateAyadi'],
			},
		},
	},
	{
		displayName: 'Breadth',
		name: 'breadth',
		type: 'number',
		default: 11,
		typeOptions: {
			numberPrecision: 6,
		},
		required: true,
		description:
			'Breadth of the building or room, in the unit given. Under the Manasara family this is the measure the vyaya and yoni formulas multiply.',
		routing: {
			send: {
				type: 'body',
				property: 'breadth',
			},
		},
		displayOptions: {
			show: {
				resource: ['vastu'],
				operation: ['calculateAyadi'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['vastu'],
				operation: ['calculateAyadi'],
			},
		},
		options: [
			{
				displayName: 'Ayadi Text',
				name: 'ayadiText',
				type: 'options',
				options: [
					{
						name: 'Manasara',
						value: 'manasara',
					},
					{
						name: 'Perimeter Texts',
						value: 'perimeter-texts',
					},
					{
						name: 'Utpala',
						value: 'utpala',
					},
				],
				default: 'manasara',
				description:
					'Which family of Ayadi formulas to apply. manasara takes length, breadth and circumference separately and is double sourced. perimeter-texts runs every formula on the perimeter alone and is the family the usual worked example is printed for. utpala supplies a yoni formula from the length times...',
				routing: {
					send: {
						type: 'body',
						property: 'ayadiText',
					},
				},
			},
			{
				displayName: 'Circumference',
				name: 'circumference',
				type: 'number',
				default: 11,
				typeOptions: {
					numberPrecision: 6,
				},
				description:
					'Circumference or height, if the Manasara vara and tithi formulas should read something other than the perimeter. Defaults to the perimeter, which is what a rectangular plan supplies.',
				routing: {
					send: {
						type: 'body',
						property: 'circumference',
					},
				},
			},
			{
				displayName: 'Hasta Inches',
				name: 'hastaInches',
				type: 'number',
				default: 18,
				typeOptions: {
					numberPrecision: 6,
				},
				description:
					'Length of one hasta, the classical cubit, in inches. Defaults to 18, which is 24 angula at three quarters of an inch each and is the value three independent sources agree on.',
				routing: {
					send: {
						type: 'body',
						property: 'hastaInches',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Perimeter',
				name: 'perimeter',
				type: 'number',
				default: 11,
				typeOptions: {
					numberPrecision: 6,
				},
				description:
					'Perimeter of the plan, if it is not simply twice the length plus twice the breadth. The perimeter family runs every formula on this one measure, so it is the number that decides all six remainders there.',
				routing: {
					send: {
						type: 'body',
						property: 'perimeter',
					},
				},
			},
			{
				displayName: 'Unit',
				name: 'unit',
				type: 'options',
				options: [
					{
						name: 'Feet',
						value: 'feet',
					},
					{
						name: 'Hasta',
						value: 'hasta',
					},
					{
						name: 'Metres',
						value: 'metres',
					},
				],
				default: 'hasta',
				description:
					'Unit the Ayadi dimensions are given in. Every remainder is unit sensitive, so this is an input and never assumed: the same building measured in cubits and in feet gives different remainders. hasta is the classical cubit and needs no conversion; feet and metres are converted using hastaInches and...',
				routing: {
					send: {
						type: 'body',
						property: 'unit',
					},
				},
			},
			{
				displayName: 'Vyaya Formula',
				name: 'vyayaFormula',
				type: 'options',
				options: [
					{
						name: 'P3 14',
						value: 'p3-14',
					},
					{
						name: 'P9 10',
						value: 'p9-10',
					},
				],
				default: 'p9-10',
				description:
					'Which vyaya formula the perimeter family uses. The printed table gives two joined by the word or and states no rule for choosing. p9-10 multiplies by nine and divides by ten, which is the only divisor consistent with the ten member vyaya group, so its remainder can be placed in that group and it...',
				routing: {
					send: {
						type: 'body',
						property: 'vyayaFormula',
					},
				},
			},
		],
	},
	{
		displayName: 'Plot',
		name: 'plot',
		type: 'json',
		default: '{\n  "width": 30,\n  "depth": 40,\n  "unit": "feet"\n}',
		required: true,
		description:
			'The ground the mandala is projected over. Send width and depth for a compass-aligned rectangle, or polygon for anything else.',
		routing: {
			send: {
				type: 'body',
				property: 'plot',
				value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['vastu'],
				operation: ['calculateEntrancePada'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['vastu'],
				operation: ['calculateEntrancePada'],
			},
		},
		options: [
			{
				displayName: 'Door',
				name: 'door',
				type: 'json',
				default: '{\n  "x": 15,\n  "y": 0\n}',
				description:
					'Where the main door sits, in plot coordinates. The point is snapped to the nearest boundary of the plot, so a coordinate read off a drawing that lands slightly inside or outside still resolves.',
				routing: {
					send: {
						type: 'body',
						property: 'door',
						value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}',
					},
				},
			},
			{
				displayName: 'Door Position',
				name: 'doorPosition',
				type: 'number',
				default: 0.4,
				typeOptions: {
					minValue: 0,
					maxValue: 1,
					numberPrecision: 6,
				},
				description:
					'Where the main door sits along the facing side, as a fraction from 0 to 1 measured from the corner the chapter starts that side at: the north-east for an east facing, the south-east for a south facing, the south-west for a west facing and the north-west for a north facing. The side carries 8...',
				routing: {
					send: {
						type: 'body',
						property: 'doorPosition',
					},
				},
			},
			{
				displayName: 'Facing',
				name: 'facing',
				type: 'options',
				options: [
					{
						name: 'East',
						value: 'East',
					},
					{
						name: 'North',
						value: 'North',
					},
					{
						name: 'Northeast',
						value: 'Northeast',
					},
					{
						name: 'Northwest',
						value: 'Northwest',
					},
					{
						name: 'South',
						value: 'South',
					},
					{
						name: 'Southeast',
						value: 'Southeast',
					},
					{
						name: 'Southwest',
						value: 'Southwest',
					},
					{
						name: 'West',
						value: 'West',
					},
				],
				default: 'North',
				description:
					'Direction the front of the house looks out toward, one of the eight compass sectors. Case and punctuation are folded, so north-east, northeast and NorthEast all resolve.',
				routing: {
					send: {
						type: 'body',
						property: 'facing',
					},
				},
			},
			{
				displayName: 'Facing Degrees',
				name: 'facingDegrees',
				type: 'number',
				default: 15,
				typeOptions: {
					minValue: 0,
					maxValue: 360,
					numberPrecision: 6,
				},
				description:
					'Direction the front of the house looks out toward, as a compass bearing in degrees clockwise from true north, measured looking OUT from the building. The same convention the feng shui facing endpoints use, so a bearing works unchanged across the two domains.',
				routing: {
					send: {
						type: 'body',
						property: 'facingDegrees',
					},
				},
			},
			{
				displayName: 'Grid',
				name: 'grid',
				type: 'options',
				options: [
					{
						name: '64-pada',
						value: '64-pada',
					},
					{
						name: '81-pada',
						value: '81-pada',
					},
				],
				default: '81-pada',
				description:
					'Which division of the ground to read: 81-pada is the Paramasayika of Brihat Samhita 53.42, the grid the chapter numbers and names every devata on, and 64-pada is the Manduka of 53.55, for which the chapter gives structure only and no devata names. Defaults to 81-pada.',
				routing: {
					send: {
						type: 'body',
						property: 'grid',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Plot',
		name: 'plot',
		type: 'json',
		default: '{\n  "width": 30,\n  "depth": 40,\n  "unit": "feet"\n}',
		required: true,
		description:
			'The ground the mandala is projected over. Send width and depth for a compass-aligned rectangle, or polygon for anything else.',
		routing: {
			send: {
				type: 'body',
				property: 'plot',
				value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['vastu'],
				operation: ['calculatePlotAnalysis'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['vastu'],
				operation: ['calculatePlotAnalysis'],
			},
		},
		options: [
			{
				displayName: 'Cuts',
				name: 'cuts',
				type: 'multiOptions',
				options: [
					{
						name: 'East',
						value: 'East',
					},
					{
						name: 'North',
						value: 'North',
					},
					{
						name: 'Northeast',
						value: 'Northeast',
					},
					{
						name: 'Northwest',
						value: 'Northwest',
					},
					{
						name: 'South',
						value: 'South',
					},
					{
						name: 'Southeast',
						value: 'Southeast',
					},
					{
						name: 'Southwest',
						value: 'Southwest',
					},
					{
						name: 'West',
						value: 'West',
					},
				],
				default: ['Southwest'],
				description:
					'Quarters where a corner is missing from the rectangle. Every cut verdict is convention, for the same reason as the extensions.',
				routing: {
					send: {
						type: 'body',
						property: 'cuts',
					},
				},
			},
			{
				displayName: 'Extensions',
				name: 'extensions',
				type: 'multiOptions',
				options: [
					{
						name: 'East',
						value: 'East',
					},
					{
						name: 'North',
						value: 'North',
					},
					{
						name: 'Northeast',
						value: 'Northeast',
					},
					{
						name: 'Northwest',
						value: 'Northwest',
					},
					{
						name: 'South',
						value: 'South',
					},
					{
						name: 'Southeast',
						value: 'Southeast',
					},
					{
						name: 'Southwest',
						value: 'Southwest',
					},
					{
						name: 'West',
						value: 'West',
					},
				],
				default: ['Northeast'],
				description:
					'Quarters where the plot bulges out beyond a rectangle. Every extension verdict is convention: the chapter states no rule for a named corner and the nearest verses speak of a figure with a limb wanting.',
				routing: {
					send: {
						type: 'body',
						property: 'extensions',
					},
				},
			},
			{
				displayName: 'Facing',
				name: 'facing',
				type: 'options',
				options: [
					{
						name: 'East',
						value: 'East',
					},
					{
						name: 'North',
						value: 'North',
					},
					{
						name: 'Northeast',
						value: 'Northeast',
					},
					{
						name: 'Northwest',
						value: 'Northwest',
					},
					{
						name: 'South',
						value: 'South',
					},
					{
						name: 'Southeast',
						value: 'Southeast',
					},
					{
						name: 'Southwest',
						value: 'Southwest',
					},
					{
						name: 'West',
						value: 'West',
					},
				],
				default: 'North',
				description:
					'Direction the front of the house looks out toward, one of the eight compass sectors. Case and punctuation are folded, so north-east, northeast and NorthEast all resolve.',
				routing: {
					send: {
						type: 'body',
						property: 'facing',
					},
				},
			},
			{
				displayName: 'Facing Degrees',
				name: 'facingDegrees',
				type: 'number',
				default: 15,
				typeOptions: {
					minValue: 0,
					maxValue: 360,
					numberPrecision: 6,
				},
				description:
					'Direction the front of the house looks out toward, as a compass bearing in degrees clockwise from true north, measured looking OUT from the building. The same convention the feng shui facing endpoints use, so a bearing works unchanged across the two domains.',
				routing: {
					send: {
						type: 'body',
						property: 'facingDegrees',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Road',
				name: 'road',
				type: 'options',
				options: [
					{
						name: 'East',
						value: 'East',
					},
					{
						name: 'North',
						value: 'North',
					},
					{
						name: 'Northeast',
						value: 'Northeast',
					},
					{
						name: 'Northwest',
						value: 'Northwest',
					},
					{
						name: 'South',
						value: 'South',
					},
					{
						name: 'Southeast',
						value: 'Southeast',
					},
					{
						name: 'Southwest',
						value: 'Southwest',
					},
					{
						name: 'West',
						value: 'West',
					},
				],
				default: 'North',
				description:
					'Which side a road runs along. The verdict is convention: the chapter states no rule for the side a road is on, only that an obstruction facing the gate brings misery unless it lies beyond twice the height of the house.',
				routing: {
					send: {
						type: 'body',
						property: 'road',
					},
				},
			},
			{
				displayName: 'Slope Low Direction',
				name: 'slopeLowDirection',
				type: 'options',
				options: [
					{
						name: 'East',
						value: 'East',
					},
					{
						name: 'North',
						value: 'North',
					},
					{
						name: 'Northeast',
						value: 'Northeast',
					},
					{
						name: 'Northwest',
						value: 'Northwest',
					},
					{
						name: 'South',
						value: 'South',
					},
					{
						name: 'Southeast',
						value: 'Southeast',
					},
					{
						name: 'Southwest',
						value: 'Southwest',
					},
					{
						name: 'West',
						value: 'West',
					},
				],
				default: 'Northeast',
				description:
					'Which quarter of the plot the ground falls toward, that is where the LOW point is. The chapter states its rules in terms of the side that stands HIGHER, so the opposite of this value is what the verses are read against, and both are returned.',
				routing: {
					send: {
						type: 'body',
						property: 'slopeLowDirection',
					},
				},
			},
			{
				displayName: 'Slope School',
				name: 'slopeSchool',
				type: 'options',
				options: [
					{
						name: 'Brihat Samhita',
						value: 'brihat-samhita',
					},
					{
						name: 'Modern',
						value: 'modern',
					},
				],
				default: 'brihat-samhita',
				description:
					'Which reading of the ground level to lead with. brihat-samhita applies verses 115 to 117 as written, where a higher north-east is a loss, a higher east or north is permitted when level ground is unavoidable and still carries its stated cost, and a higher south or west carries its cost with no...',
				routing: {
					send: {
						type: 'body',
						property: 'slopeSchool',
					},
				},
			},
			{
				displayName: 'Water',
				name: 'water',
				type: 'options',
				options: [
					{
						name: 'East',
						value: 'East',
					},
					{
						name: 'North',
						value: 'North',
					},
					{
						name: 'Northeast',
						value: 'Northeast',
					},
					{
						name: 'Northwest',
						value: 'Northwest',
					},
					{
						name: 'South',
						value: 'South',
					},
					{
						name: 'Southeast',
						value: 'Southeast',
					},
					{
						name: 'Southwest',
						value: 'Southwest',
					},
					{
						name: 'West',
						value: 'West',
					},
				],
				default: 'Northeast',
				description:
					'Which quarter holds standing water, a well, a tank or a sump. This one IS sourced: 53.119 gives a distinct effect for each of the eight directions and calls only the north and the north-east favourable.',
				routing: {
					send: {
						type: 'body',
						property: 'water',
					},
				},
			},
		],
	},
	{
		displayName: 'Plot',
		name: 'plot',
		type: 'json',
		default: '{\n  "width": 30,\n  "depth": 40,\n  "unit": "feet"\n}',
		required: true,
		description:
			'The ground the mandala is projected over. Send width and depth for a compass-aligned rectangle, or polygon for anything else.',
		routing: {
			send: {
				type: 'body',
				property: 'plot',
				value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['vastu'],
				operation: ['calculateRoomCompliance'],
			},
		},
	},
	{
		displayName: 'Rooms',
		name: 'rooms',
		type: 'json',
		default:
			'[\n  {\n    "type": "kitchen",\n    "direction": "Southeast",\n    "polygon": [\n      {\n        "x": 20,\n        "y": 2\n      },\n      {\n        "x": 28,\n        "y": 2\n      },\n      {\n        "x": 28,\n        "y": 12\n      },\n      {\n        "x": 20,\n        "y": 12\n      }\n    ]\n  }\n]',
		required: true,
		description:
			'The rooms to check, 1 to 24 of them. Each carries a type and either the quarter it sits in or its outline.',
		routing: {
			send: {
				type: 'body',
				property: 'rooms',
				value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['vastu'],
				operation: ['calculateRoomCompliance'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['vastu'],
				operation: ['calculateRoomCompliance'],
			},
		},
		options: [
			{
				displayName: 'Facing',
				name: 'facing',
				type: 'options',
				options: [
					{
						name: 'East',
						value: 'East',
					},
					{
						name: 'North',
						value: 'North',
					},
					{
						name: 'Northeast',
						value: 'Northeast',
					},
					{
						name: 'Northwest',
						value: 'Northwest',
					},
					{
						name: 'South',
						value: 'South',
					},
					{
						name: 'Southeast',
						value: 'Southeast',
					},
					{
						name: 'Southwest',
						value: 'Southwest',
					},
					{
						name: 'West',
						value: 'West',
					},
				],
				default: 'North',
				description:
					'Direction the front of the house looks out toward, one of the eight compass sectors. Case and punctuation are folded, so north-east, northeast and NorthEast all resolve.',
				routing: {
					send: {
						type: 'body',
						property: 'facing',
					},
				},
			},
			{
				displayName: 'Facing Degrees',
				name: 'facingDegrees',
				type: 'number',
				default: 15,
				typeOptions: {
					minValue: 0,
					maxValue: 360,
					numberPrecision: 6,
				},
				description:
					'Direction the front of the house looks out toward, as a compass bearing in degrees clockwise from true north, measured looking OUT from the building. The same convention the feng shui facing endpoints use, so a bearing works unchanged across the two domains.',
				routing: {
					send: {
						type: 'body',
						property: 'facingDegrees',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Start Date',
		name: 'startDate',
		type: 'string',
		default: '',
		placeholder: 'e.g. 2027-01-20',
		required: true,
		description:
			'First day of the search window, in YYYY-MM-DD. Every limb is read at sunrise of the local day, because the Hindu day begins at sunrise rather than at midnight.',
		routing: {
			send: {
				type: 'body',
				property: 'startDate',
			},
		},
		displayOptions: {
			show: {
				resource: ['vastu'],
				operation: ['findGrihaPraveshDates'],
			},
		},
	},
	{
		displayName: 'End Date',
		name: 'endDate',
		type: 'string',
		default: '',
		placeholder: 'e.g. 2027-03-20',
		required: true,
		description:
			'Last day of the search window, in YYYY-MM-DD, inclusive. The window is capped at 93 days, which is a full season and the same cap the Vedic auspicious day search carries.',
		routing: {
			send: {
				type: 'body',
				property: 'endDate',
			},
		},
		displayOptions: {
			show: {
				resource: ['vastu'],
				operation: ['findGrihaPraveshDates'],
			},
		},
	},
	{
		displayName: 'Latitude',
		name: 'latitude',
		type: 'number',
		default: 28.6139,
		typeOptions: {
			minValue: -90,
			maxValue: 90,
			numberPrecision: 6,
		},
		required: true,
		description:
			'Latitude of the house, in decimal degrees, positive north. Sunrise decides where one day ends and the next begins, so a nakshatra running out during the morning changes which day it counts for.',
		routing: {
			send: {
				type: 'body',
				property: 'latitude',
			},
		},
		displayOptions: {
			show: {
				resource: ['vastu'],
				operation: ['findGrihaPraveshDates'],
			},
		},
	},
	{
		displayName: 'Longitude',
		name: 'longitude',
		type: 'number',
		default: 77.209,
		typeOptions: {
			minValue: -180,
			maxValue: 180,
			numberPrecision: 6,
		},
		required: true,
		description: 'Longitude of the house, in decimal degrees, positive east',
		routing: {
			send: {
				type: 'body',
				property: 'longitude',
			},
		},
		displayOptions: {
			show: {
				resource: ['vastu'],
				operation: ['findGrihaPraveshDates'],
			},
		},
	},
	{
		displayName: 'Timezone',
		name: 'timezone',
		type: 'string',
		default: '',
		placeholder: 'e.g. America/New_York or America/New_York',
		required: true,
		description:
			'IANA name (e.g. "America/New_York", "Europe/London", "UTC"), decimal hours (e.g. -5 for EST, 1 for CET), or a fixed UTC offset (e.g. "-05:00", "+01:00"). Prefer the IANA name: it is resolved to the offset in force at the birth date and time, historical daylight-saving rules included, while a...',
		routing: {
			send: {
				type: 'body',
				property: 'timezone',
				value: '={{ $value !== "" && !isNaN(Number($value)) ? Number($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['vastu'],
				operation: ['findGrihaPraveshDates'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['vastu'],
				operation: ['findGrihaPraveshDates'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Muhurta Text',
				name: 'muhurtaText',
				type: 'options',
				options: [
					{
						name: 'Kalaprakasika',
						value: 'kalaprakasika',
					},
					{
						name: 'Muhurta Chintamani',
						value: 'muhurta-chintamani',
					},
				],
				default: 'muhurta-chintamani',
				description:
					'Which Muhurta text supplies the admissible nakshatras for entering a new house. muhurta-chintamani admits eight and kalaprakasika admits twelve; seven overlap and are the high confidence core, one is unique to the first and five to the second. The two texts are independent witnesses, which is...',
				routing: {
					send: {
						type: 'body',
						property: 'muhurtaText',
					},
				},
			},
		],
	},
	{
		displayName: 'Plot',
		name: 'plot',
		type: 'json',
		default: '{\n  "width": 30,\n  "depth": 40,\n  "unit": "feet"\n}',
		required: true,
		description:
			'The ground the mandala is projected over. Send width and depth for a compass-aligned rectangle, or polygon for anything else.',
		routing: {
			send: {
				type: 'body',
				property: 'plot',
				value: '={{ typeof $value === "string" ? JSON.parse($value) : $value }}',
			},
		},
		displayOptions: {
			show: {
				resource: ['vastu'],
				operation: ['generateMandala'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['vastu'],
				operation: ['generateMandala'],
			},
		},
		options: [
			{
				displayName: 'Grid',
				name: 'grid',
				type: 'options',
				options: [
					{
						name: '64-pada',
						value: '64-pada',
					},
					{
						name: '81-pada',
						value: '81-pada',
					},
				],
				default: '81-pada',
				description:
					'Which division of the ground to read: 81-pada is the Paramasayika of Brihat Samhita 53.42, the grid the chapter numbers and names every devata on, and 64-pada is the Manduka of 53.55, for which the chapter gives structure only and no devata names. Defaults to 81-pada.',
				routing: {
					send: {
						type: 'body',
						property: 'grid',
					},
				},
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'options',
		options: [
			{
				name: 'Aditi',
				value: 'aditi',
			},
			{
				name: 'Agni',
				value: 'agni',
			},
			{
				name: 'Ahi',
				value: 'ahi',
			},
			{
				name: 'Antariksha',
				value: 'antariksha',
			},
			{
				name: 'Apa',
				value: 'apa',
			},
			{
				name: 'Apavatsa',
				value: 'apavatsa',
			},
			{
				name: 'Aryaman',
				value: 'aryaman',
			},
			{
				name: 'Asura',
				value: 'asura',
			},
			{
				name: 'Bhallata',
				value: 'bhallata',
			},
			{
				name: 'Bhringaraja',
				value: 'bhringaraja',
			},
			{
				name: 'Bhrisa',
				value: 'bhrisa',
			},
			{
				name: 'Bhujaga',
				value: 'bhujaga',
			},
			{
				name: 'Brahma',
				value: 'brahma',
			},
			{
				name: 'Brihatkshata',
				value: 'brihatkshata',
			},
			{
				name: 'Dauvarika',
				value: 'dauvarika',
			},
			{
				name: 'Diti',
				value: 'diti',
			},
			{
				name: 'Gandharva',
				value: 'gandharva',
			},
			{
				name: 'Indra Inner',
				value: 'indra-inner',
			},
			{
				name: 'Indra Outer',
				value: 'indra-outer',
			},
			{
				name: 'Jaya',
				value: 'jaya',
			},
			{
				name: 'Jayanta',
				value: 'jayanta',
			},
			{
				name: 'Kusumadanta',
				value: 'kusumadanta',
			},
			{
				name: 'Mitra',
				value: 'mitra',
			},
			{
				name: 'Mriga',
				value: 'mriga',
			},
			{
				name: 'Mukhya',
				value: 'mukhya',
			},
			{
				name: 'Papayakshma',
				value: 'papayakshma',
			},
			{
				name: 'Parjanya',
				value: 'parjanya',
			},
			{
				name: 'Pitri',
				value: 'pitri',
			},
			{
				name: 'Prthvidhara',
				value: 'prthvidhara',
			},
			{
				name: 'Pusha',
				value: 'pusha',
			},
			{
				name: 'Rajayakshma',
				value: 'rajayakshma',
			},
			{
				name: 'Roga',
				value: 'roga',
			},
			{
				name: 'Rudra',
				value: 'rudra',
			},
			{
				name: 'Satya',
				value: 'satya',
			},
			{
				name: 'Savita',
				value: 'savita',
			},
			{
				name: 'Savitra',
				value: 'savitra',
			},
			{
				name: 'Soma',
				value: 'soma',
			},
			{
				name: 'Sosha',
				value: 'sosha',
			},
			{
				name: 'Sugriva',
				value: 'sugriva',
			},
			{
				name: 'Surya',
				value: 'surya',
			},
			{
				name: 'Varuna',
				value: 'varuna',
			},
			{
				name: 'Vayu',
				value: 'vayu',
			},
			{
				name: 'Vitatha',
				value: 'vitatha',
			},
			{
				name: 'Vivasvan',
				value: 'vivasvan',
			},
			{
				name: 'Yama',
				value: 'yama',
			},
		],
		default: 'jayanta',
		required: true,
		description:
			'Devata ID, lower case transliteration. The two Indras are indra-outer for the east perimeter square and indra-inner for the inner ring one.',
		displayOptions: {
			show: {
				resource: ['vastu'],
				operation: ['getDevata'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['vastu'],
				operation: ['getDevata'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'options',
		options: [
			{
				name: 'East',
				value: 'East',
			},
			{
				name: 'North',
				value: 'North',
			},
			{
				name: 'Northeast',
				value: 'Northeast',
			},
			{
				name: 'Northwest',
				value: 'Northwest',
			},
			{
				name: 'South',
				value: 'South',
			},
			{
				name: 'Southeast',
				value: 'Southeast',
			},
			{
				name: 'Southwest',
				value: 'Southwest',
			},
			{
				name: 'West',
				value: 'West',
			},
		],
		default: 'Northeast',
		required: true,
		description:
			'Direction ID, one of North, Northeast, East, Southeast, South, Southwest, West, Northwest. Case and punctuation are folded.',
		displayOptions: {
			show: {
				resource: ['vastu'],
				operation: ['getDikpalaDirection'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['vastu'],
				operation: ['getDikpalaDirection'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['vastu'],
				operation: ['listDevatas'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Limit',
				name: 'maxResults',
				type: 'number',
				default: 45,
				typeOptions: {
					minValue: 1,
					maxValue: 45,
				},
				description: 'Maximum items to return per page. Range: 1-45, default 45.',
				routing: {
					send: {
						type: 'query',
						property: 'limit',
					},
				},
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: 0,
				},
				description: 'Number of items to skip for pagination. Default 0.',
				routing: {
					send: {
						type: 'query',
						property: 'offset',
					},
				},
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['vastu'],
				operation: ['listDikpalaDirections'],
			},
		},
		options: [
			{
				displayName: 'Language',
				name: 'lang',
				type: 'options',
				options: [
					{
						name: 'English',
						value: 'en',
					},
					{
						name: 'French',
						value: 'fr',
					},
					{
						name: 'German',
						value: 'de',
					},
					{
						name: 'Hindi',
						value: 'hi',
					},
					{
						name: 'Portuguese',
						value: 'pt',
					},
					{
						name: 'Russian',
						value: 'ru',
					},
					{
						name: 'Simplified Chinese',
						value: 'zh-Hans',
					},
					{
						name: 'Spanish',
						value: 'es',
					},
					{
						name: 'Traditional Chinese',
						value: 'zh-Hant',
					},
					{
						name: 'Turkish',
						value: 'tr',
					},
				],
				default: 'en',
				description:
					'Response language (BCP 47). Supported: en, tr, de, es, hi, pt, fr, ru, zh-Hans, zh-Hant.',
				routing: {
					send: {
						type: 'query',
						property: 'lang',
					},
				},
			},
			{
				displayName: 'Limit',
				name: 'maxResults',
				type: 'number',
				default: 8,
				typeOptions: {
					minValue: 1,
					maxValue: 8,
				},
				description: 'Maximum items to return per page. Range: 1-8, default 8.',
				routing: {
					send: {
						type: 'query',
						property: 'limit',
					},
				},
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: 0,
				},
				description: 'Number of items to skip for pagination. Default 0.',
				routing: {
					send: {
						type: 'query',
						property: 'offset',
					},
				},
			},
		],
	},
];
